package main

import (
	"fmt"
	"strings"
)

// csOpMethodName converts a Request class name to a C# method name:
// "AuthLoginRequest" -> "AuthLogin"; falls back to the class name.
func csOpMethodName(reqClassName string) string {
	n := strings.TrimSuffix(reqClassName, "Request")
	if n == "" {
		return reqClassName
	}
	return n
}

// hasServerEvent reports whether a server-event class with the given bare
// name is registered (used to conditionally wire OperationError intercept).
func hasServerEvent(schema ProtocolSchema, bareName string) bool {
	for _, st := range schema.ServerEventTypes {
		if csReflectClassName(st.Name) == bareName {
			return true
		}
	}
	return false
}

// hasClientInput reports whether a client-input class with the given bare
// name is registered (used to conditionally wire the WorldDelta auto-ACK).
func hasClientInput(schema ProtocolSchema, bareName string) bool {
	for _, ct := range schema.ClientInputTypes {
		if csReflectClassName(ct.Name) == bareName {
			return true
		}
	}
	return false
}

// genClient emits Client.cs: the stateless <Game>Client facade over UdpTransport.
func (b csharpBackend) genClient(schema ProtocolSchema) string {
	gameName := titleCase(schema.Game)
	hasEvents := len(schema.BroadcastTypes) > 0 || len(schema.ServerEventTypes) > 0
	hasOps := len(schema.Operations) > 0
	hasInputs := len(schema.ClientInputTypes) > 0
	hasOpError := hasOps && hasServerEvent(schema, "OperationError")
	// The C# client is the only UDP client, so it is the only one that needs
	// to acknowledge replication frames. TS is WebSocket-only: the server
	// classifies that as reliable-ordered and never selects explicit ACK for
	// it, so a TS auto-ack would be dead code.
	autoAck := hasClientInput(schema, "ReplicationAck") && hasServerEvent(schema, "WorldDelta")

	var sb strings.Builder
	sb.WriteString("// GENERATED by sdkgen — do not edit.\n\n")
	sb.WriteString("using System;\nusing System.Collections.Generic;\nusing System.Threading;\nusing System.Threading.Tasks;\nusing Mmokit.Sdk.Core;\n\n")
	fmt.Fprintf(&sb, "namespace %s\n{\n", b.namespace)

	if hasOpError {
		sb.WriteString("    /// Thrown when an operation returns a framework OperationError. Carries\n")
		sb.WriteString("    /// the server-supplied Code + Message so callers can branch on the reason\n")
		sb.WriteString("    /// (e.g. a duplicate-active login) instead of parsing a string.\n")
		sb.WriteString("    public sealed class OperationException : System.Exception\n    {\n")
		sb.WriteString("        public uint Code { get; }\n")
		sb.WriteString("        public OperationException(uint code, string message) : base(message) { Code = code; }\n")
		sb.WriteString("    }\n\n")
	}

	sb.WriteString("    /// Stateless high-level client. Owns transport + decode + dispatch;\n")
	sb.WriteString("    /// the CONSUMER owns accumulated world state (Unity GameObjects / a bot's\n")
	sb.WriteString("    /// store). Decode a WorldDelta via OnWorldDelta(m => Decoder.Decode(m.body)).\n")
	fmt.Fprintf(&sb, "    public sealed class %sClient\n    {\n", gameName)
	sb.WriteString("        UdpTransport? _transport;\n")
	sb.WriteString("        CancellationTokenSource? _pumpCts;\n")
	fmt.Fprintf(&sb, "        public %sDeltaDecoder Decoder { get; } = new();\n", gameName)
	if hasEvents {
		sb.WriteString("        public TypedDispatcher TypedEvents { get; } = new();\n")
	}
	if hasOps {
		sb.WriteString("        readonly Dictionary<ulong, TaskCompletionSource<byte[]>> _pendingOps = new();\n")
		sb.WriteString("        readonly object _opLock = new();\n")
		sb.WriteString("        long _nextReqId;\n")
	}
	sb.WriteString("\n")

	// Connect / Disconnect.
	//
	// ConnectAsync is the whole client handshake and the entry point callers
	// should reach for: authenticate over HTTPS, draw a UDP session key, then
	// open the socket. Connect stays public for applications that run their
	// own login and already hold a key.
	sb.WriteString("        /// Authenticate over HTTPS and open an authenticated UDP session.\n")
	sb.WriteString("        ///\n")
	sb.WriteString("        /// baseUrl is the gateway's HTTP origin (e.g. \"https://game.example:8080\").\n")
	sb.WriteString("        /// This logs in, draws a short-lived key from POST /auth/udp-key, and hands\n")
	sb.WriteString("        /// it to Connect. The server binds the player from that key, so the session\n")
	sb.WriteString("        /// is authenticated from its first datagram and there is no post-connect\n")
	sb.WriteString("        /// auth step.\n")
	sb.WriteString("        ///\n")
	sb.WriteString("        /// registerIfMissing defaults to false: connecting does not create an\n")
	sb.WriteString("        /// account as a side effect. Pass true for a bot or demo that owns its own\n")
	sb.WriteString("        /// account namespace.\n")
	sb.WriteString("        ///\n")
	sb.WriteString("        /// Over plain http:// the server issues a key only when started with\n")
	sb.WriteString("        /// --dev-insecure-cookie; otherwise it answers 403 rather than put a bearer\n")
	sb.WriteString("        /// secret on a plaintext listener.\n")
	sb.WriteString("        public async Task ConnectAsync(string baseUrl, string host, int port, string username, string password,\n")
	sb.WriteString("            bool registerIfMissing = false, string? email = null, int handshakeTimeoutMs = 5000,\n")
	sb.WriteString("            CancellationToken cancellationToken = default)\n        {\n")
	sb.WriteString("            UdpKeyCredential cred = await MmokitAuth.FetchUdpKeyAsync(\n")
	sb.WriteString("                baseUrl, username, password, registerIfMissing, email,\n")
	sb.WriteString("                MmokitAuth.DefaultCookieName, cancellationToken).ConfigureAwait(false);\n")
	sb.WriteString("            Connect(host, port, cred.KeyId, cred.Key, handshakeTimeoutMs);\n")
	sb.WriteString("        }\n\n")

	sb.WriteString("        /// Open an authenticated UDP session with a key you already hold, and\n")
	sb.WriteString("        /// start the receive pump.\n")
	sb.WriteString("        ///\n")
	sb.WriteString("        /// udpKeyId and udpKey come from POST /auth/udp-key over HTTPS — see\n")
	sb.WriteString("        /// ConnectAsync, which does that for you. The transport authenticates every\n")
	sb.WriteString("        /// packet under that key, so there is no unauthenticated connect path.\n")
	sb.WriteString("        public void Connect(string host, int port, ulong udpKeyId, byte[] udpKey, int handshakeTimeoutMs = 5000)\n        {\n")
	sb.WriteString("            _transport = UdpTransport.Connect(host, port, udpKeyId, udpKey, handshakeTimeoutMs);\n")
	sb.WriteString("            _pumpCts = new CancellationTokenSource();\n")
	sb.WriteString("            var t = _transport;\n")
	sb.WriteString("            var ct = _pumpCts.Token;\n")
	sb.WriteString("            _ = Task.Run(() => Pump(t, ct));\n")
	sb.WriteString("        }\n\n")

	sb.WriteString("        public void Disconnect()\n        {\n")
	sb.WriteString("            _pumpCts?.Cancel();\n")
	if hasOps {
		sb.WriteString("            lock (_opLock) { foreach (var p in _pendingOps.Values) p.TrySetException(new Exception(\"client disconnected\")); _pendingOps.Clear(); }\n")
	}
	sb.WriteString("            _transport?.Close();\n")
	sb.WriteString("        }\n\n")

	sb.WriteString("        /// Clear delta baselines (call on reconnect).\n")
	sb.WriteString("        public void ClearBaselines() => Decoder.Clear();\n\n")

	// Pump + routing.
	sb.WriteString("        void Pump(UdpTransport t, CancellationToken ct)\n        {\n")
	sb.WriteString("            while (!ct.IsCancellationRequested)\n            {\n")
	sb.WriteString("                byte[]? frame = t.Recv();\n")
	sb.WriteString("                if (frame == null) return; // transport closed\n")
	sb.WriteString("                if (frame.Length == 0) continue;\n")
	sb.WriteString("                byte ch = frame[0];\n")
	sb.WriteString("                byte[] body = Sub(frame, 1, frame.Length - 1);\n")
	sb.WriteString("                if (ch == 0x00) HandleEvent(body);\n")
	if hasOps {
		sb.WriteString("                else if (ch == 0x01) HandleOperation(body);\n")
	}
	sb.WriteString("            }\n        }\n\n")

	// HandleEvent.
	sb.WriteString("        void HandleEvent(byte[] body)\n        {\n")
	if hasEvents {
		sb.WriteString("            int off = 0;\n")
		sb.WriteString("            while (off + 8 <= body.Length)\n            {\n")
		sb.WriteString("                uint typeID = ReadU32(body, off);\n")
		sb.WriteString("                int bodyLen = (int)ReadU32(body, off + 4);\n")
		sb.WriteString("                off += 8;\n")
		sb.WriteString("                if (off + bodyLen > body.Length) return; // truncated\n")
		if autoAck {
			sb.WriteString("                if (typeID == WorldDelta.TypeID) AckWorldDelta(Sub(body, off, bodyLen));\n")
		}
		sb.WriteString("                TypedEvents.Dispatch(typeID, Sub(body, off, bodyLen));\n")
		sb.WriteString("                off += bodyLen;\n")
		sb.WriteString("            }\n")
	}
	sb.WriteString("        }\n\n")

	if autoAck {
		sb.WriteString("        /// Acknowledge one replication frame back to the server.\n")
		sb.WriteString("        ///\n")
		sb.WriteString("        /// Datagram transports need this: the server latches explicit-ACK\n")
		sb.WriteString("        /// baseline advancement per connection from the transport's delivery\n")
		sb.WriteString("        /// class, and without an ACK it stalls the stream and then resends a\n")
		sb.WriteString("        /// full snapshot. Sending an unsolicited or stale ACK is harmless — the\n")
		sb.WriteString("        /// server promotes only the exact (StreamEpoch, Seq) currently in flight.\n")
		sb.WriteString("        ///\n")
		sb.WriteString("        /// Acking on RECEIPT, before the consumer's decoder has run, is sound\n")
		sb.WriteString("        /// only because a connection may have at most one causal attempt in\n")
		sb.WriteString("        /// flight, so a reordered or duplicated datagram can never acknowledge a\n")
		sb.WriteString("        /// frame the decoder rejected. If server-side frames are ever pipelined,\n")
		sb.WriteString("        /// this ACK must move behind the decoder's accept gate or the server\n")
		sb.WriteString("        /// will promote baselines the client never applied.\n")
		sb.WriteString("        void AckWorldDelta(byte[] raw)\n        {\n")
		sb.WriteString("            var m = WorldDelta.Decode(raw);\n")
		sb.WriteString("            // Frame seq is the big-endian uint32 at offset 4 of the delta body.\n")
		sb.WriteString("            if (m.body == null || m.body.Length < 8) return;\n")
		sb.WriteString("            uint seq = ((uint)m.body[4] << 24) | ((uint)m.body[5] << 16) | ((uint)m.body[6] << 8) | m.body[7];\n")
		sb.WriteString("            // UNRELIABLE deliberately: a retransmitted ACK is worthless (the\n")
		sb.WriteString("            // server's attempt has moved on or timed out) and would burn a slot\n")
		sb.WriteString("            // in the 256-entry reliable window at tick rate.\n")
		sb.WriteString("            SendReplicationAck(new ReplicationAck { streamEpoch = m.streamEpoch, seq = seq }, reliable: false);\n")
		sb.WriteString("        }\n\n")
	}

	// HandleOperation.
	if hasOps {
		sb.WriteString("        void HandleOperation(byte[] body)\n        {\n")
		sb.WriteString("            if (body.Length < 16) return;\n")
		sb.WriteString("            uint resTypeID = ReadU32(body, 0);\n")
		sb.WriteString("            ulong reqID = ReadU64(body, 4);\n")
		sb.WriteString("            int bodyLen = (int)ReadU32(body, 12);\n")
		sb.WriteString("            if (16 + bodyLen > body.Length) return;\n")
		sb.WriteString("            byte[] opBody = Sub(body, 16, bodyLen);\n")
		sb.WriteString("            TaskCompletionSource<byte[]>? p;\n")
		sb.WriteString("            lock (_opLock) { if (!_pendingOps.TryGetValue(reqID, out p)) return; _pendingOps.Remove(reqID); }\n")
		if hasOpError {
			sb.WriteString("            if (resTypeID == OperationError.TypeID) { var err = OperationError.Decode(opBody); p.TrySetException(new OperationException(err.code, err.message)); return; }\n")
		}
		sb.WriteString("            p.TrySetResult(opBody);\n")
		sb.WriteString("        }\n\n")

		// CallOp helper.
		sb.WriteString("        Task<byte[]> CallOp(uint reqTypeID, byte[] reqBody)\n        {\n")
		sb.WriteString("            ulong reqID = (ulong)Interlocked.Increment(ref _nextReqId);\n")
		sb.WriteString("            var tcs = new TaskCompletionSource<byte[]>();\n")
		sb.WriteString("            lock (_opLock) { _pendingOps[reqID] = tcs; }\n")
		sb.WriteString("            byte[] frame = new byte[1 + 4 + 8 + 4 + reqBody.Length];\n")
		sb.WriteString("            frame[0] = 0x01;\n")
		sb.WriteString("            WriteU32(frame, 1, reqTypeID);\n")
		sb.WriteString("            WriteU64(frame, 5, reqID);\n")
		sb.WriteString("            WriteU32(frame, 13, (uint)reqBody.Length);\n")
		sb.WriteString("            Array.Copy(reqBody, 0, frame, 17, reqBody.Length);\n")
		sb.WriteString("            _transport!.SendReliable(frame);\n")
		sb.WriteString("            return tcs.Task;\n")
		sb.WriteString("        }\n\n")

		// Per-op methods.
		emitted := map[string]struct{}{}
		for _, op := range schema.Operations {
			reqCls := csReflectClassName(op.RequestTypeName)
			resCls := csReflectClassName(op.ResponseTypeName)
			method := csOpMethodName(reqCls)
			if _, dup := emitted[method]; dup {
				continue
			}
			emitted[method] = struct{}{}
			fmt.Fprintf(&sb, "        /// Typed op %s → %s.\n", op.RequestTypeName, op.ResponseTypeName)
			fmt.Fprintf(&sb, "        public async Task<%s> %s(%s req)\n        {\n", resCls, method, reqCls)
			fmt.Fprintf(&sb, "            byte[] raw = await CallOp(%s.TypeID, req.Encode());\n", reqCls)
			fmt.Fprintf(&sb, "            return %s.Decode(raw);\n", resCls)
			sb.WriteString("        }\n\n")
		}
	}

	// Per-input send methods.
	if hasInputs {
		sb.WriteString("        void SendInputFrame(uint typeID, byte[] body, bool reliable)\n        {\n")
		sb.WriteString("            byte[] frame = new byte[1 + 4 + 4 + body.Length];\n")
		sb.WriteString("            frame[0] = 0x00;\n")
		sb.WriteString("            WriteU32(frame, 1, typeID);\n")
		sb.WriteString("            WriteU32(frame, 5, (uint)body.Length);\n")
		sb.WriteString("            Array.Copy(body, 0, frame, 9, body.Length);\n")
		sb.WriteString("            if (reliable) _transport!.SendReliable(frame); else _transport!.SendUnreliable(frame);\n")
		sb.WriteString("        }\n\n")
		for _, ct := range schema.ClientInputTypes {
			cls := csReflectClassName(ct.Name)
			fmt.Fprintf(&sb, "        /// Send a %s client-input (reliable by default; opt out for replaceable high-rate samples).\n", cls)
			fmt.Fprintf(&sb, "        public void Send%s(%s msg, bool reliable = true) => SendInputFrame(%s.TypeID, msg.Encode(), reliable);\n\n", cls, cls, cls)
		}
	}

	// Per-server-event On<Name> subscriptions.
	if hasEvents {
		for _, st := range schema.ServerEventTypes {
			cls := csReflectClassName(st.Name)
			fmt.Fprintf(&sb, "        /// Subscribe to the %s server event. Returns an unsubscribe.\n", st.Name)
			fmt.Fprintf(&sb, "        public Action On%s(Action<%s> handler) => TypedEvents.On(%s.TypeID, b => handler(%s.Decode(b)));\n\n", cls, cls, cls, cls)
		}
	}

	// LE byte helpers (frame headers are little-endian).
	sb.WriteString("        static uint ReadU32(byte[] b, int o) => (uint)b[o] | ((uint)b[o + 1] << 8) | ((uint)b[o + 2] << 16) | ((uint)b[o + 3] << 24);\n")
	sb.WriteString("        static ulong ReadU64(byte[] b, int o) { ulong v = 0; for (int i = 0; i < 8; i++) v |= (ulong)b[o + i] << (8 * i); return v; }\n")
	sb.WriteString("        static void WriteU32(byte[] b, int o, uint v) { for (int i = 0; i < 4; i++) b[o + i] = (byte)(v >> (8 * i)); }\n")
	sb.WriteString("        static void WriteU64(byte[] b, int o, ulong v) { for (int i = 0; i < 8; i++) b[o + i] = (byte)(v >> (8 * i)); }\n")
	sb.WriteString("        static byte[] Sub(byte[] b, int start, int len) { var r = new byte[len]; Array.Copy(b, start, r, 0, len); return r; }\n")

	sb.WriteString("    }\n}\n")
	return sb.String()
}
