package main

import (
	"fmt"
	"sort"
	"strings"
)

// csharpBackend emits a C# client SDK. The hand-written runtime lives in
// csharp/Mmokit.Sdk.Core/*.cs and is copied verbatim into the SDK's _core/;
// the schema-driven types are generated here.
type csharpBackend struct {
	namespace string // root namespace for generated files (default "Mmokit.Sdk")
	coreDir   string // path to the hand-written _core .cs sources
}

func (b csharpBackend) Lang() string { return "csharp" }

// CoreFiles copies the hand-written runtime files into <out>/_core/.
func (b csharpBackend) CoreFiles() []CoreFile {
	dir := b.coreDir
	if dir == "" {
		dir = "csharp/Mmokit.Sdk.Core"
	}
	names := []string{
		"DeltaDecoderCore.cs",
		"InterpolationCore.cs",
		"ReflectCodec.cs",
		"UdpProto.cs",
		"UdpTransport.cs",
		"UdpTransport.Socket.cs",
	}
	out := make([]CoreFile, len(names))
	for i, n := range names {
		out[i] = CoreFile{Src: dir + "/" + n, Dst: n}
	}
	return out
}

func (b csharpBackend) OutputFiles(schema ProtocolSchema) map[string]func() string {
	files := map[string]func() string{}
	// EntityType + Entities are emitted only when the schema registers kinds.
	if len(schema.Entities) > 0 {
		files["EntityType.cs"] = func() string { return b.genEntityType(schema) }
		files["Entities.cs"] = func() string { return b.genEntities(schema) }
		files["DeltaDecoder.cs"] = func() string { return b.genDeltaDecoder(schema) }
	}
	// Reflect-codec message surface, gated per registry (mirrors tsBackend).
	if len(schema.BroadcastTypes) > 0 || len(schema.ServerEventTypes) > 0 {
		files["Events.cs"] = func() string { return b.genEvents(schema) }
	}
	if len(schema.ClientInputTypes) > 0 {
		files["Inputs.cs"] = func() string { return b.genInputs(schema) }
	}
	if len(schema.Operations) > 0 {
		files["Operations.cs"] = func() string { return b.genOperations(schema) }
	}
	return files
}

// genEntityType emits a byte-valued enum of entity kinds, sorted by Kind.
func (b csharpBackend) genEntityType(schema ProtocolSchema) string {
	entries := make([]EntitySchema, len(schema.Entities))
	copy(entries, schema.Entities)
	sort.Slice(entries, func(i, j int) bool { return entries[i].Kind < entries[j].Kind })

	var sb strings.Builder
	sb.WriteString("// GENERATED by sdkgen — do not edit.\n\n")
	fmt.Fprintf(&sb, "namespace %s\n{\n", b.namespace)
	sb.WriteString("    /// Entity-kind wire IDs. Values match the kindID arg to\n")
	sb.WriteString("    /// mmokit.RegisterKind[T] on the server; names match its display-name arg.\n")
	sb.WriteString("    public enum EntityType : byte\n    {\n")
	for _, e := range entries {
		fmt.Fprintf(&sb, "        %s = %d,\n", csharpIdent(e.Name, e.Kind), e.Kind)
	}
	sb.WriteString("    }\n}\n")
	return sb.String()
}

// genEntities emits EntityBase + one sealed class per kind (+ var-tail item
// classes) + a DeltaWorldUpdate carrier.
func (b csharpBackend) genEntities(schema ProtocolSchema) string {
	var sb strings.Builder
	sb.WriteString("// GENERATED by sdkgen — do not edit.\n\n")
	sb.WriteString("using System.Collections.Generic;\n\n")
	fmt.Fprintf(&sb, "namespace %s\n{\n", b.namespace)

	// Common base: every decoded entity carries these three.
	sb.WriteString("    /// Fields every decoded entity carries. ProducedAtMs is the producer\n")
	sb.WriteString("    /// cluster-clock stamp (Unix ms) used as the interpolation time-base.\n")
	sb.WriteString("    public abstract class EntityBase\n    {\n")
	sb.WriteString("        public uint NetID;\n")
	sb.WriteString("        public byte EntityKind;\n")
	sb.WriteString("        public ulong ProducedAtMs;\n")
	sb.WriteString("    }\n\n")

	for _, ent := range schema.Entities {
		name := csharpEntityName(ent)
		fmt.Fprintf(&sb, "    /// Entity kind %d.\n", ent.Kind)
		fmt.Fprintf(&sb, "    public sealed class %s : EntityBase\n    {\n", name)
		// Non-initial then initial fixed fields (matches the TS order).
		for _, binding := range ent.Bindings {
			for _, f := range binding.Fields {
				if f.Initial {
					continue
				}
				fmt.Fprintf(&sb, "        public %s %s;\n", encodingToCSharpType(f.Encoding), f.Name)
			}
		}
		for _, binding := range ent.Bindings {
			for _, f := range binding.Fields {
				if !f.Initial {
					continue
				}
				fmt.Fprintf(&sb, "        public %s %s;\n", encodingToCSharpType(f.Encoding), f.Name)
			}
		}
		if ent.VarTail != nil {
			item := csharpTailItemName(ent)
			fmt.Fprintf(&sb, "        public List<%s> %s = new();\n", item, ent.VarTail.Name)
		}
		sb.WriteString("    }\n\n")

		if ent.VarTail != nil {
			item := csharpTailItemName(ent)
			fmt.Fprintf(&sb, "    /// Item record for %s.%s.\n", name, ent.VarTail.Name)
			fmt.Fprintf(&sb, "    public sealed class %s\n    {\n", item)
			for _, f := range ent.VarTail.ItemFields {
				fmt.Fprintf(&sb, "        public %s %s;\n", encodingToCSharpType(f.Encoding), f.Name)
			}
			sb.WriteString("    }\n\n")
		}
	}

	// World-update carrier (entered/updated are typed to the common base).
	sb.WriteString("    /// One decoded SE_DELTA_WORLD_UPDATE frame.\n")
	sb.WriteString("    public sealed class DeltaWorldUpdate\n    {\n")
	sb.WriteString("        public uint Tick;\n")
	sb.WriteString("        public uint Seq;\n")
	sb.WriteString("        public bool FreshSnapshot;\n")
	sb.WriteString("        public List<EntityBase> Entered = new();\n")
	sb.WriteString("        public List<EntityBase> Updated = new();\n")
	sb.WriteString("        public List<uint> Removed = new();\n")
	sb.WriteString("        public List<uint> Exited = new();\n")
	sb.WriteString("    }\n}\n")
	return sb.String()
}

// csharpEntityName mirrors generate.go::entityName: "Ship" -> "ShipEntity";
// unnamed -> "Entity{Kind}".
func csharpEntityName(ent EntitySchema) string {
	if ent.Name != "" {
		return ent.Name + "Entity"
	}
	return fmt.Sprintf("Entity%d", ent.Kind)
}

// csharpTailItemName mirrors generate.go::tailItemTypeName: strip "Entity",
// append TitleCase(varTail name) + "Item".
func csharpTailItemName(ent EntitySchema) string {
	if ent.VarTail == nil {
		return ""
	}
	base := strings.TrimSuffix(csharpEntityName(ent), "Entity")
	return base + titleCase(ent.VarTail.Name) + "Item"
}

// csharpIdent returns a valid C# enum-member identifier for an entity name,
// falling back to Entity{Kind} if the name is empty.
func csharpIdent(name string, kind uint8) string {
	if name == "" {
		return fmt.Sprintf("Entity%d", kind)
	}
	return name
}

// encodingToCSharpType maps a wire/field encoding to the DECODED C# type the
// entity data class holds. Quantized numerics decode to float; integer
// encodings keep their width; bool/string map directly. Mirrors the type the
// Plan 7 DeltaDecoder will produce into these fields.
func encodingToCSharpType(enc string) string {
	switch enc {
	case "string":
		return "string"
	case "bool":
		return "bool"
	case "u8":
		return "byte"
	case "u16":
		return "ushort"
	case "u32":
		return "uint"
	case "u64":
		return "ulong"
	case "i8":
		return "sbyte"
	case "i16":
		return "short"
	case "i32":
		return "int"
	case "i64":
		return "long"
	case "f32", "qvel", "qangle", "qnorm":
		return "float"
	default:
		// Unknown encodings decode to a float scalar, mirroring the TS
		// `number` fallback. New encodings should be added explicitly.
		return "float"
	}
}
