package main

import (
	"fmt"
	"strings"
)

// genDeltaDecoder emits DeltaDecoder.cs: per-entity snapshot decoders + a
// <Game>DeltaDecoder class driving full/delta frame application over the
// DeltaDecoderCore primitives. Port of generate.go::genDeltaDecoder.
func (b csharpBackend) genDeltaDecoder(schema ProtocolSchema) string {
	var sb strings.Builder
	sb.WriteString("// GENERATED by sdkgen — do not edit.\n\n")
	sb.WriteString("using System;\nusing System.Collections.Generic;\nusing System.Text;\nusing Mmokit.Sdk.Core;\n\n")
	fmt.Fprintf(&sb, "namespace %s\n{\n", b.namespace)

	gameName := titleCase(schema.Game)

	// Baseline meta: the cached snapshot's kind + last decoded entity (so
	// delta frames can restore initial-only fields like names).
	sb.WriteString("    sealed class BaselineMeta { public byte Type; public EntityBase? LastEntity; }\n\n")

	fmt.Fprintf(&sb, "    public sealed class %sDeltaDecoder\n    {\n", gameName)

	// Per-entity snapshot decoders — C# requires these inside a class (unlike
	// the TS module-level functions), so they live as static methods here.
	for _, ent := range schema.Entities {
		writeCsSnapshotDecoder(&sb, ent, csharpEntityName(ent), csharpTailItemName(ent))
	}

	sb.WriteString("        readonly BaselineStore<BaselineMeta> _baselines = new();\n\n")
	sb.WriteString("        public void Clear() => _baselines.Clear();\n\n")

	sb.WriteString("        public DeltaWorldUpdate Decode(byte[] data)\n        {\n")
	sb.WriteString("            var (header, pos0) = DeltaDecoderCore.DecodeFrameHeader(data, 0);\n")
	sb.WriteString("            int pos = pos0;\n")
	sb.WriteString("            bool freshSnapshot = (header.Flags & DeltaDecoderCore.FrameFlagFreshSnapshot) != 0;\n")
	sb.WriteString("            if (freshSnapshot) _baselines.Clear();\n\n")
	sb.WriteString("            var entered = new List<EntityBase>();\n")
	sb.WriteString("            var updated = new List<EntityBase>();\n\n")

	// Full entries.
	sb.WriteString("            for (int i = 0; i < header.FullCount; i++)\n            {\n")
	sb.WriteString("                var (entry, next) = DeltaDecoderCore.DecodeFullEntry(data, pos);\n")
	sb.WriteString("                pos = next;\n")
	sb.WriteString("                EntityBase? prev = _baselines.TryGet(entry.NetID, out _, out var pm) ? pm?.LastEntity : null;\n")
	sb.WriteString("                var entity = DecodeEntity(entry.EntityType, entry.Snapshot, entry.InitialData, entry.NetID, entry.ProducedAtMs, prev);\n")
	sb.WriteString("                _baselines.Set(entry.NetID, entry.Snapshot, new BaselineMeta { Type = entry.EntityType, LastEntity = entity });\n")
	sb.WriteString("                if (entity != null) entered.Add(entity);\n")
	sb.WriteString("            }\n\n")

	// Delta entries.
	sb.WriteString("            for (int i = 0; i < header.DeltaCount; i++)\n            {\n")
	sb.WriteString("                var (entry, next) = DeltaDecoderCore.DecodeDeltaEntry(data, pos);\n")
	sb.WriteString("                pos = next;\n")
	sb.WriteString("                if (!_baselines.TryGet(entry.NetID, out var snap, out var meta)) continue;\n")
	sb.WriteString("                int[] fieldSizes = FieldSizesFor(entry.EntityType);\n")
	sb.WriteString("                bool hasVarTail = HasVarTailFor(entry.EntityType);\n")
	sb.WriteString("                byte[] newSnap = DeltaDecoderCore.ApplyDelta(fieldSizes, hasVarTail, snap, entry.DeltaData);\n")
	sb.WriteString("                var entity = DecodeEntity(entry.EntityType, newSnap, null, entry.NetID, entry.ProducedAtMs, meta?.LastEntity);\n")
	sb.WriteString("                _baselines.Set(entry.NetID, newSnap, new BaselineMeta { Type = meta?.Type ?? entry.EntityType, LastEntity = entity });\n")
	sb.WriteString("                if (entity != null) updated.Add(entity);\n")
	sb.WriteString("            }\n\n")

	// Removed + exited.
	sb.WriteString("            var (removed, pos2) = DeltaDecoderCore.DecodeRemovedIDs(data, pos, header.RemovedCount);\n")
	sb.WriteString("            var (exited, _) = DeltaDecoderCore.DecodeRemovedIDs(data, pos2, header.ExitedCount);\n")
	sb.WriteString("            foreach (var id in removed) _baselines.Delete(id);\n")
	sb.WriteString("            foreach (var id in exited) _baselines.Delete(id);\n\n")

	sb.WriteString("            return new DeltaWorldUpdate {\n")
	sb.WriteString("                Tick = header.Tick, Seq = header.Seq, FreshSnapshot = freshSnapshot,\n")
	sb.WriteString("                Entered = entered, Updated = updated,\n")
	sb.WriteString("                Removed = new List<uint>(removed), Exited = new List<uint>(exited),\n")
	sb.WriteString("            };\n")
	sb.WriteString("        }\n\n")

	// DecodeEntity dispatcher.
	sb.WriteString("        static EntityBase? DecodeEntity(byte type_, byte[] snap, byte[]? initial, uint netID, ulong producedAtMs, EntityBase? existing)\n        {\n")
	sb.WriteString("            switch (type_)\n            {\n")
	for _, ent := range schema.Entities {
		name := csharpEntityName(ent)
		fmt.Fprintf(&sb, "                case %d: { var e = Decode%sSnapshot(snap, initial, existing as %s); e.NetID = netID; e.ProducedAtMs = producedAtMs; return e; }\n", ent.Kind, name, name)
	}
	sb.WriteString("                default: return null;\n")
	sb.WriteString("            }\n        }\n\n")

	// FieldSizesFor / HasVarTailFor.
	sb.WriteString("        static int[] FieldSizesFor(byte type_)\n        {\n            switch (type_)\n            {\n")
	for _, ent := range schema.Entities {
		fixedSizes, _ := splitVarTailLayout(ent.Layout)
		fmt.Fprintf(&sb, "                case %d: return new int[] { %s };\n", ent.Kind, joinInts(fixedSizes))
	}
	sb.WriteString("                default: return System.Array.Empty<int>();\n            }\n        }\n\n")

	sb.WriteString("        static bool HasVarTailFor(byte type_)\n        {\n            switch (type_)\n            {\n")
	for _, ent := range schema.Entities {
		_, hasVarTail := splitVarTailLayout(ent.Layout)
		fmt.Fprintf(&sb, "                case %d: return %v;\n", ent.Kind, hasVarTail)
	}
	sb.WriteString("                default: return false;\n            }\n        }\n")

	sb.WriteString("    }\n}\n")
	return sb.String()
}

// splitVarTailLayout strips a trailing -1 var-tail marker, returning the fixed
// field sizes + whether a var tail was present.
func splitVarTailLayout(layout []int) (fixedSizes []int, hasVarTail bool) {
	fixedSizes = layout
	if len(fixedSizes) > 0 && fixedSizes[len(fixedSizes)-1] == -1 {
		hasVarTail = true
		fixedSizes = fixedSizes[:len(fixedSizes)-1]
	}
	return fixedSizes, hasVarTail
}

// writeCsSnapshotDecoder emits Decode<Name>Snapshot.
func writeCsSnapshotDecoder(sb *strings.Builder, ent EntitySchema, name, itemName string) {
	fmt.Fprintf(sb, "    static %s Decode%sSnapshot(byte[] snap, byte[]? initial, %s? existing)\n    {\n", name, name, name)
	sb.WriteString("        int o = 0;\n")
	fmt.Fprintf(sb, "        var e = new %s { EntityKind = %d };\n", name, ent.Kind)

	// Fixed (non-initial) fields.
	for _, binding := range ent.Bindings {
		for _, f := range binding.Fields {
			if f.Initial {
				continue
			}
			writeCsFixedFieldDecode(sb, "e."+f.Name, f, "        ")
		}
	}

	// Var tail.
	if ent.VarTail != nil {
		vt := ent.VarTail
		if len(vt.ItemFields) == 0 {
			// No item fields means no field decoder advances `o`, so the
			// generated while-loop would spin forever. Match the TS guard.
			panic(fmt.Sprintf("sdkgen csharp: entity kind %d var-tail %q has no ItemFields; decoder would be an infinite loop", ent.Kind, vt.Name))
		}
		fmt.Fprintf(sb, "        { ushort _tlen = DeltaDecoderCore.ReadUint16(snap, o); o += 2; int _tend = o + _tlen;\n")
		fmt.Fprintf(sb, "          while (o < _tend) {\n")
		fmt.Fprintf(sb, "            var _it = new %s();\n", itemName)
		for _, f := range vt.ItemFields {
			writeCsFixedFieldDecode(sb, "_it."+f.Name, f, "            ")
		}
		fmt.Fprintf(sb, "            e.%s.Add(_it);\n", vt.Name)
		sb.WriteString("          } }\n")
	}

	// Initial fields.
	hasInitial := false
	for _, binding := range ent.Bindings {
		for _, f := range binding.Fields {
			if f.Initial {
				hasInitial = true
			}
		}
	}
	if hasInitial {
		sb.WriteString("        int initialOff = 0;\n")
		for _, binding := range ent.Bindings {
			for _, f := range binding.Fields {
				if !f.Initial {
					continue
				}
				writeCsInitialFieldDecode(sb, "e."+f.Name, "existing?."+f.Name, f)
			}
		}
		sb.WriteString("        _ = initialOff;\n")
	}

	sb.WriteString("        return e;\n    }\n\n")
}

// writeCsFixedFieldDecode emits one fixed-layout field decode into `target`.
func writeCsFixedFieldDecode(sb *strings.Builder, target string, f BindingSchemaField, indent string) {
	switch f.Encoding {
	case "f32":
		fmt.Fprintf(sb, "%s%s = DeltaDecoderCore.ReadFloat32(snap, o); o += 4;\n", indent, target)
	case "qvel":
		fmt.Fprintf(sb, "%s%s = (float)DeltaDecoderCore.UnVel(DeltaDecoderCore.ReadInt16(snap, o), %g); o += 2;\n", indent, target, f.Scale)
	case "qangle":
		fmt.Fprintf(sb, "%s%s = (float)DeltaDecoderCore.UnAngle(DeltaDecoderCore.ReadUint16(snap, o)); o += 2;\n", indent, target)
	case "qnorm":
		fmt.Fprintf(sb, "%s%s = (float)DeltaDecoderCore.UnNorm(snap[o]); o += 1;\n", indent, target)
	case "u8":
		fmt.Fprintf(sb, "%s%s = snap[o]; o += 1;\n", indent, target)
	case "u16":
		fmt.Fprintf(sb, "%s%s = DeltaDecoderCore.ReadUint16(snap, o); o += 2;\n", indent, target)
	case "u32":
		fmt.Fprintf(sb, "%s%s = DeltaDecoderCore.ReadUint32(snap, o); o += 4;\n", indent, target)
	case "i16":
		fmt.Fprintf(sb, "%s%s = DeltaDecoderCore.ReadInt16(snap, o); o += 2;\n", indent, target)
	case "bool":
		fmt.Fprintf(sb, "%s%s = snap[o] != 0; o += 1;\n", indent, target)
	default:
		panic(fmt.Sprintf("sdkgen csharp: unsupported fixed field encoding %q for %q", f.Encoding, f.Name))
	}
}

// writeCsInitialFieldDecode emits an if/else decode of one initial-only field
// from `initial`+`initialOff`, falling back to `fallback` (existing?.field).
func writeCsInitialFieldDecode(sb *strings.Builder, target, fallback string, f BindingSchemaField) {
	switch f.Encoding {
	case "string":
		fmt.Fprintf(sb, "        if (initial != null && initialOff < initial.Length) { int _l = initial[initialOff]; %s = Encoding.UTF8.GetString(initial, initialOff + 1, _l); initialOff += 1 + _l; } else { %s = %s ?? \"\"; }\n", target, target, fallback)
	case "u8":
		fmt.Fprintf(sb, "        if (initial != null && initialOff < initial.Length) { %s = initial[initialOff]; initialOff += 1; } else { %s = %s ?? (byte)0; }\n", target, target, fallback)
	case "i8":
		fmt.Fprintf(sb, "        if (initial != null && initialOff < initial.Length) { %s = (sbyte)initial[initialOff]; initialOff += 1; } else { %s = %s ?? (sbyte)0; }\n", target, target, fallback)
	case "u16":
		fmt.Fprintf(sb, "        if (initial != null && initialOff + 2 <= initial.Length) { %s = DeltaDecoderCore.ReadUint16(initial, initialOff); initialOff += 2; } else { %s = %s ?? (ushort)0; }\n", target, target, fallback)
	case "i16":
		fmt.Fprintf(sb, "        if (initial != null && initialOff + 2 <= initial.Length) { %s = DeltaDecoderCore.ReadInt16(initial, initialOff); initialOff += 2; } else { %s = %s ?? (short)0; }\n", target, target, fallback)
	case "u32":
		fmt.Fprintf(sb, "        if (initial != null && initialOff + 4 <= initial.Length) { %s = DeltaDecoderCore.ReadUint32(initial, initialOff); initialOff += 4; } else { %s = %s ?? 0u; }\n", target, target, fallback)
	case "f32":
		fmt.Fprintf(sb, "        if (initial != null && initialOff + 4 <= initial.Length) { %s = DeltaDecoderCore.ReadFloat32(initial, initialOff); initialOff += 4; } else { %s = %s ?? 0f; }\n", target, target, fallback)
	case "bool":
		fmt.Fprintf(sb, "        if (initial != null && initialOff < initial.Length) { %s = initial[initialOff] != 0; initialOff += 1; } else { %s = %s ?? false; }\n", target, target, fallback)
	default:
		fmt.Fprintf(sb, "        %s = %s ?? default;\n", target, fallback)
	}
}
