package main

import (
	"fmt"
	"sort"
	"strings"
)

// genEntityType emits entityType.ts containing one TS const block keyed
// by the entity-kind names + numeric IDs registered via
// mmokit.RegisterKind[T](p, kindID, name, ...). The schema dump's
// Entities array carries both fields, so this emitter consumes the same
// data the broadcasts/inputs/operations emitters use for entity classes.
//
// Output schema:
//
//	export const EntityType = {
//	    Ship: 0,
//	    Asteroid: 1,
//	    Station: 2,
//	    LootCrate: 3,
//	    NPC: 4,
//	} as const;
//	export type EntityTypeValue = typeof EntityType[keyof typeof EntityType];
//
// `as const` chosen over `enum` for tree-shakeability + zero runtime
// overhead. Consumers do forward-lookup only (no reverse-mapping needs).
//
// Returns "" when the schema has zero registered entity kinds — caller
// (main.go's files map) uses that to skip writing the file.
func (g *Generator) genEntityType() string {
	if len(g.schema.Entities) == 0 {
		return ""
	}

	// Sort by Kind value to keep the output stable regardless of the
	// schema dump's iteration order.
	entries := make([]EntitySchema, len(g.schema.Entities))
	copy(entries, g.schema.Entities)
	sort.Slice(entries, func(i, j int) bool {
		return entries[i].Kind < entries[j].Kind
	})

	var b strings.Builder
	b.WriteString("// GENERATED by sdkgen — do not edit.\n\n")
	b.WriteString("// Entity-kind wire bytes. The values match the kindID arg passed to\n")
	b.WriteString("// mmokit.RegisterKind[T] on the Go side; the names match the second\n")
	b.WriteString("// arg (display name) of the same call.\n\n")
	b.WriteString("export const EntityType = {\n")
	for _, e := range entries {
		fmt.Fprintf(&b, "    %s: %d,\n", e.Name, e.Kind)
	}
	b.WriteString("} as const;\n\n")
	b.WriteString("export type EntityTypeValue = typeof EntityType[keyof typeof EntityType];\n")

	return b.String()
}
