package main

import (
	"fmt"
	"sort"
	"strings"
)

// Generator produces TypeScript SDK file contents from a protocol schema.
// It is the content engine behind tsBackend; all genXxx methods read only
// schema.
type Generator struct {
	schema ProtocolSchema
}

// ---------------------------------------------------------------------------
// transport.ts
// ---------------------------------------------------------------------------

func (g *Generator) genTransport() string {
	return `// GENERATED by sdkgen — do not edit.

const CH_EVENT = 0x00;
const CH_OPERATION = 0x01;

export type MessageHandler = (data: Uint8Array) => void;

export class Transport {
  private ws: WebSocket | null = null;
  private eventHandlers: MessageHandler[] = [];
  private operationHandlers: MessageHandler[] = [];

  constructor(private url: string) {}

  connect(): void {
    this.ws = new WebSocket(this.url);
    this.ws.binaryType = "arraybuffer";
    this.ws.onmessage = (ev) => {
      const data = new Uint8Array(ev.data as ArrayBuffer);
      if (data.length < 1) return;
      const channel = data[0];
      const payload = data.subarray(1);
      if (channel === CH_EVENT) {
        for (const h of this.eventHandlers) h(payload);
      } else if (channel === CH_OPERATION) {
        for (const h of this.operationHandlers) h(payload);
      }
    };
  }

  get socket(): WebSocket | null { return this.ws; }
  get connected(): boolean { return this.ws?.readyState === WebSocket.OPEN; }

  close(): void { this.ws?.close(); this.ws = null; }

  sendEvent(data: Uint8Array): void {
    if (!this.ws || this.ws.readyState !== WebSocket.OPEN) return;
    const frame = new Uint8Array(1 + data.length);
    frame[0] = CH_EVENT;
    frame.set(data, 1);
    this.ws.send(frame);
  }

  sendOperation(data: Uint8Array): void {
    if (!this.ws || this.ws.readyState !== WebSocket.OPEN) return;
    const frame = new Uint8Array(1 + data.length);
    frame[0] = CH_OPERATION;
    frame.set(data, 1);
    this.ws.send(frame);
  }

  /**
   * Send a fully-built frame as-is (no channel-byte prefix added). The
   * caller is responsible for the entire wire layout including the channel
   * byte. Used by the typed-op Promise correlator in <Game>Client, which
   * builds the full [0x01][typeID][requestID][bodyLen][body] frame in one
   * allocation rather than two.
   */
  sendRaw(frame: Uint8Array): void {
    if (!this.ws || this.ws.readyState !== WebSocket.OPEN) return;
    this.ws.send(frame);
  }

  /**
   * Send a typed client-input frame (mmokit.HandleClient registry).
   * Wire layout: [byte 0x00][u32 typeID][u32 bodyLen][body bytes].
   * Body is produced by the matching TS class's encode() instance method;
   * the server resolves typeID back to the registered Go type and decodes
   * the body via the same reflection codec used for broadcast events.
   *
   * Inputs and server events both ride channel 0x00 — they're
   * distinguished server-side by typeID via the typed dispatcher.
   */
  sendClientInput(typeID: number, body: Uint8Array): void {
    if (!this.ws || this.ws.readyState !== WebSocket.OPEN) return;
    const frame = new Uint8Array(1 + 4 + 4 + body.length);
    const dv = new DataView(frame.buffer);
    frame[0] = CH_EVENT;
    dv.setUint32(1, typeID, true);
    dv.setUint32(5, body.length, true);
    frame.set(body, 9);
    this.ws.send(frame);
  }

  onEvent(handler: MessageHandler): void { this.eventHandlers.push(handler); }
  onOperation(handler: MessageHandler): void { this.operationHandlers.push(handler); }
}
`
}

// ---------------------------------------------------------------------------
// entities.ts
// ---------------------------------------------------------------------------

func (g *Generator) genEntities() string {
	var b strings.Builder
	b.WriteString("// GENERATED by sdkgen — do not edit.\n\n")

	var entityNames []string

	for _, ent := range g.schema.Entities {
		name := g.entityName(ent)
		entityNames = append(entityNames, name)

		fmt.Fprintf(&b, "/** Entity kind %d. */\n", ent.Kind)
		fmt.Fprintf(&b, "export interface %s {\n", name)
		b.WriteString("  netID: number;\n")
		b.WriteString("  /** Authority generation for this netID (uint32 serial). */\n")
		b.WriteString("  authorityEpoch: number;\n")
		fmt.Fprintf(&b, "  entityType: %d;\n", ent.Kind)
		b.WriteString("  /**\n")
		b.WriteString("   * Cluster-clock stamp (Unix ms) from the authoritative producer at\n")
		b.WriteString("   * the moment this state was emitted. Preserves the producer's\n")
		b.WriteString("   * timeline through any relay hops. Used as the per-entity time-base\n")
		b.WriteString("   * for snapshot interpolation.\n")
		b.WriteString("   */\n")
		b.WriteString("  producedAtMs: number;\n")

		for _, binding := range ent.Bindings {
			for _, field := range binding.Fields {
				if field.Initial {
					continue
				}
				tsType := encodingToTSType(field.Encoding)
				fmt.Fprintf(&b, "  %s: %s;\n", field.Name, tsType)
			}
		}
		// Initial fields.
		for _, binding := range ent.Bindings {
			for _, field := range binding.Fields {
				if !field.Initial {
					continue
				}
				tsType := encodingToTSType(field.Encoding)
				fmt.Fprintf(&b, "  %s: %s;\n", field.Name, tsType)
			}
		}

		// Var-tail field (if any).
		if ent.VarTail != nil {
			itemType := g.tailItemTypeName(ent)
			fmt.Fprintf(&b, "  %s: %s[];\n", ent.VarTail.Name, itemType)
		}

		b.WriteString("}\n\n")

		// Emit the var-tail item type interface after the entity interface.
		if ent.VarTail != nil {
			itemType := g.tailItemTypeName(ent)
			fmt.Fprintf(&b, "/** Item record for %s.%s var-tail. */\n", name, ent.VarTail.Name)
			fmt.Fprintf(&b, "export interface %s {\n", itemType)
			for _, f := range ent.VarTail.ItemFields {
				tsType := encodingToTSType(f.Encoding)
				fmt.Fprintf(&b, "  %s: %s;\n", f.Name, tsType)
			}
			b.WriteString("}\n\n")
		}
	}

	// Union type.
	if len(entityNames) > 0 {
		b.WriteString("export type AnyEntity = ")
		b.WriteString(strings.Join(entityNames, " | "))
		b.WriteString(";\n\n")
	}

	b.WriteString("export interface DeltaWorldUpdate {\n")
	b.WriteString("  tick: number;\n")
	b.WriteString("  seq: number;\n")
	b.WriteString("  /**\n")
	b.WriteString("   * Set when the server's ReplicationSystem sent this frame as the\n")
	b.WriteString("   * first frame to this connection — i.e. on initial login or on every\n")
	b.WriteString("   * cross-cell handoff. The SDK decoder clears its per-entity baselines\n")
	b.WriteString("   * before applying the frame; clients should treat the frame's Entered\n")
	b.WriteString("   * list as the authoritative current entity set and drop any stale\n")
	b.WriteString("   * entities they retained from before. Topology-transparent: clients\n")
	b.WriteString("   * never learn about cells, authority transfers, or server boundaries.\n")
	b.WriteString("   */\n")
	b.WriteString("  freshSnapshot: boolean;\n")
	b.WriteString("  /** True when the decoder adopted a new explicit stream generation. */\n")
	b.WriteString("  streamChanged: boolean;\n")
	b.WriteString("  /** Input sequence causally reflected by this frame; null on legacy/unsequenced streams. */\n")
	b.WriteString("  processedInputSeq: number | null;\n")
	b.WriteString("  entered: AnyEntity[];\n")
	b.WriteString("  updated: AnyEntity[];\n")
	b.WriteString("  removed: number[];\n")
	b.WriteString("  exited: number[];\n")
	b.WriteString("}\n")

	return b.String()
}

func (g *Generator) entityName(ent EntitySchema) string {
	if ent.Name != "" {
		return ent.Name + "Entity"
	}
	return fmt.Sprintf("Entity%d", ent.Kind)
}

// tailItemTypeName returns the generated TypeScript interface name for a
// var-tail's per-item record. Example: Ship → ShipStatusEffectsItem.
//
// Strips the trailing "Entity" suffix from entityName() so tail-item names
// read as ShipStatusEffectsItem rather than ShipEntityStatusEffectsItem.
func (g *Generator) tailItemTypeName(ent EntitySchema) string {
	if ent.VarTail == nil {
		return ""
	}
	name := strings.TrimSuffix(g.entityName(ent), "Entity")
	return name + titleCase(ent.VarTail.Name) + "Item"
}

func encodingToTSType(enc string) string {
	switch enc {
	case "string":
		return "string"
	case "bool":
		return "boolean"
	default:
		return "number"
	}
}

// ---------------------------------------------------------------------------
// delta-decoder.ts
// ---------------------------------------------------------------------------

func (g *Generator) genDeltaDecoder() string {
	var b strings.Builder
	b.WriteString("// GENERATED by sdkgen — do not edit.\n\n")
	b.WriteString("import {\n")
	b.WriteString("  readFloat32, readInt16, readUint16, readUint32,\n")
	b.WriteString("  unAngle, unNorm, unVel,\n")
	b.WriteString("  decodeFrameHeader, decodeFullEntry, decodeDeltaEntry, decodeRemovedIDs, decodeInputAck,\n")
	b.WriteString("  FRAME_FLAG_FRESH_SNAPSHOT,\n")
	b.WriteString("  applyDelta, BaselineStore,\n")
	b.WriteString("  decodeLengthPrefixedStringU8,\n")
	b.WriteString("} from \"./_core/delta-decoder-core.js\";\n")

	// Import entity types AND per-entity var-tail item types. The decode
	// functions below allocate slices typed as `<Entity><Tail>Item[]`, so
	// every entity with a var-tail contributes its item interface to the
	// import list alongside its entity interface.
	var entityNames []string
	for _, ent := range g.schema.Entities {
		entityNames = append(entityNames, g.entityName(ent))
		if item := g.tailItemTypeName(ent); item != "" {
			entityNames = append(entityNames, item)
		}
	}
	fmt.Fprintf(&b, "import type { %s, AnyEntity, DeltaWorldUpdate } from \"./entities.js\";\n\n", strings.Join(entityNames, ", "))

	// Generate per-entity constants and decode functions.
	for _, ent := range g.schema.Entities {
		name := g.entityName(ent)
		upperName := strings.ToUpper(name)

		// Field sizes array — strip the trailing -1 var-tail marker. The
		// client-side applyDelta expects only the fixed field sizes and takes
		// hasVarTail as a separate boolean. Leaving the -1 in the array
		// miscounts totalLogicalFields and fixedSize, corrupting delta
		// application.
		fixedLayout := ent.Layout
		hasVarTail := false
		if len(fixedLayout) > 0 && fixedLayout[len(fixedLayout)-1] == -1 {
			hasVarTail = true
			fixedLayout = fixedLayout[:len(fixedLayout)-1]
		}
		fmt.Fprintf(&b, "const %s_FIELD_SIZES = [%s];\n", upperName, joinInts(fixedLayout))
		fmt.Fprintf(&b, "const %s_HAS_VAR_TAIL = %v;\n\n", upperName, hasVarTail)

		// Decode snapshot function.
		fmt.Fprintf(&b, "function decode%sSnapshot(snap: Uint8Array, initial: Uint8Array | null, existing?: %s): %s {\n", name, name, name)
		b.WriteString("  let o = 0;\n")

		// Snapshot fields (non-initial).
		for _, binding := range ent.Bindings {
			for _, field := range binding.Fields {
				if field.Initial {
					continue
				}
				writeFieldDecoder(&b, field)
			}
		}

		// Var-tail parsing.
		if ent.VarTail != nil {
			writeVarTailDecoder(&b, ent, g.tailItemTypeName(ent))
		}

		// Initial fields. Multiple initial fields are packed in declaration
		// order into the entity's InitialData byte slice; we walk through
		// with a running offset variable so each decoder reads from its
		// proper position. Without this all initial fields after the first
		// would read from byte 0 and clobber each other.
		hasInitialFields := false
		for _, binding := range ent.Bindings {
			for _, field := range binding.Fields {
				if field.Initial {
					hasInitialFields = true
					break
				}
			}
			if hasInitialFields {
				break
			}
		}
		if hasInitialFields {
			b.WriteString("  let initialOff = 0;\n")
		}
		for _, binding := range ent.Bindings {
			for _, field := range binding.Fields {
				if !field.Initial {
					continue
				}
				writeInitialFieldDecoder(&b, field, ent.InitialData)
			}
		}
		if hasInitialFields {
			// Silence the unused-variable warning when the last field is a
			// scalar (the final advance line is the only "use" of initialOff
			// and gets stripped by tsc DCE if no later field references it).
			b.WriteString("  void initialOff;\n")
		}

		// Return object. Wire metadata is overwritten by the caller; initializing
		// it keeps the interface satisfied even if a future path forgets to set it.
		fmt.Fprintf(&b, "  return { netID: 0, authorityEpoch: 0, producedAtMs: 0, entityType: %d", ent.Kind)
		for _, binding := range ent.Bindings {
			for _, field := range binding.Fields {
				fmt.Fprintf(&b, ", %s", field.Name)
			}
		}
		if ent.VarTail != nil {
			fmt.Fprintf(&b, ", %s", ent.VarTail.Name)
		}
		b.WriteString(" };\n")
		b.WriteString("}\n\n")
	}

	// Authority epochs are uint32 serials. Comparing them as ordinary numbers
	// fails across wraparound (0 is newer than 0xffffffff), so use RFC 1982-style
	// half-range arithmetic. An exact half-range jump is deliberately not newer.
	b.WriteString("function isNewerAuthorityEpoch(candidate: number, current: number): boolean {\n")
	b.WriteString("  const distance = (candidate - current) >>> 0;\n")
	b.WriteString("  return distance !== 0 && distance < 0x80000000;\n")
	b.WriteString("}\n\n")
	b.WriteString("function isNewerFrameSequence(candidate: number, current: number): boolean {\n")
	b.WriteString("  const distance = (candidate - current) >>> 0;\n")
	b.WriteString("  return distance !== 0 && distance < 0x80000000;\n")
	b.WriteString("}\n\n")

	// Decoder class.
	gameName := titleCase(g.schema.Game)
	fmt.Fprintf(&b, "export class %sDeltaDecoder {\n", gameName)
	// Baseline meta caches the last fully-decoded entity so delta frames can
	// restore initial-only fields (e.g. string names that are only transmitted
	// in the initial data block of a full snapshot). Without this, delta
	// decoding would reset those fields to empty strings every tick.
	b.WriteString("  private baselines = new BaselineStore<{ epoch: number; type: number; lastEntity?: AnyEntity }>();\n\n")
	// FreshSnapshot resets delta baselines, but it does not normally reset the
	// highest authority generation observed for a netID. Frames from the same
	// stream can overlap at handoff; retaining this fence prevents a delayed old
	// fresh frame from resurrecting a superseded lifecycle. A *new enclosing
	// stream generation* is different: it supersedes all history from the old
	// stream (including a destination stream that was later rolled back), so
	// acceptFrame clears this map when it advances the stream generation.
	b.WriteString("  private authorityEpochs = new Map<number, number>();\n\n")
	// The viewer's authority epoch scopes the frame sequence. Gate the entire
	// frame before FreshSnapshot can clear baselines or removals can mutate the
	// visible set: delayed frames from the previous host are otherwise able to
	// roll back a decoder that has already accepted the destination stream.
	b.WriteString("  private streamEpoch: number | null = null;\n")
	b.WriteString("  private lastFrameSequence: number | null = null;\n\n")

	b.WriteString("  clear(): void {\n")
	b.WriteString("    this.baselines.clear();\n")
	b.WriteString("    this.authorityEpochs.clear();\n")
	b.WriteString("    this.streamEpoch = null;\n")
	b.WriteString("    this.lastFrameSequence = null;\n")
	b.WriteString("  }\n\n")

	b.WriteString("  private acceptFrame(streamEpoch: number | undefined, sequence: number): { accepted: boolean; streamChanged: boolean } {\n")
	b.WriteString("    if (streamEpoch === undefined) return { accepted: true, streamChanged: false };\n")
	b.WriteString("    const epoch = streamEpoch >>> 0;\n")
	b.WriteString("    const seq = sequence >>> 0;\n")
	b.WriteString("    if (this.streamEpoch === null) {\n")
	b.WriteString("      this.streamEpoch = epoch;\n")
	b.WriteString("      this.lastFrameSequence = seq;\n")
	b.WriteString("      return { accepted: true, streamChanged: true };\n")
	b.WriteString("    }\n")
	b.WriteString("    if (epoch !== this.streamEpoch) {\n")
	b.WriteString("      if (!isNewerAuthorityEpoch(epoch, this.streamEpoch)) return { accepted: false, streamChanged: false };\n")
	b.WriteString("      this.streamEpoch = epoch;\n")
	b.WriteString("      this.lastFrameSequence = seq;\n")
	b.WriteString("      this.baselines.clear();\n")
	b.WriteString("      this.authorityEpochs.clear();\n")
	b.WriteString("      return { accepted: true, streamChanged: true };\n")
	b.WriteString("    }\n")
	b.WriteString("    if (this.lastFrameSequence !== null && !isNewerFrameSequence(seq, this.lastFrameSequence)) return { accepted: false, streamChanged: false };\n")
	b.WriteString("    this.lastFrameSequence = seq;\n")
	b.WriteString("    return { accepted: true, streamChanged: false };\n")
	b.WriteString("  }\n\n")

	b.WriteString("  decode(data: Uint8Array, streamEpoch?: number): DeltaWorldUpdate | null {\n")
	b.WriteString("    const { header, offset: pos0 } = decodeFrameHeader(data, 0);\n")
	b.WriteString("    const frameOrder = this.acceptFrame(streamEpoch, header.seq);\n")
	b.WriteString("    if (!frameOrder.accepted) return null;\n")
	b.WriteString("    let pos = pos0;\n\n")

	// If the server flagged this frame as fresh (first frame for this
	// conn on the sending ReplicationSystem — login or post-handoff),
	// drop every baseline before applying. This is the only way a
	// handoff-initiated full snapshot can land correctly: the incoming
	// Full entries carry the authoritative per-entity state and must
	// replace, not merge with, whatever baselines the previous cell's
	// decoder had accumulated.
	b.WriteString("    const freshSnapshot = (header.flags & FRAME_FLAG_FRESH_SNAPSHOT) !== 0;\n")
	b.WriteString("    if (freshSnapshot) {\n")
	b.WriteString("      this.baselines.clear();\n")
	b.WriteString("    }\n\n")
	b.WriteString("    const freshAuthorityIDs = freshSnapshot && this.streamEpoch !== null ? new Set<number>() : null;\n\n")

	b.WriteString("    const entered: AnyEntity[] = [];\n")
	b.WriteString("    const updated: AnyEntity[] = [];\n\n")

	// Full entries.
	//
	// Full frames come in two flavors: the first-visibility snapshot (which
	// carries InitialData for one-shot fields like pilot name), and periodic
	// full-state keyframes (which carry no initial data). Both go through this
	// loop. To keep initial-only fields alive across keyframes, look up the
	// previous baseline and pass its cached lastEntity as `existing` — the
	// per-entity decoders fall back to `existing?.field` when the initial
	// blob is missing. First-visibility decodes have no baseline yet and so
	// pass `undefined`, which is fine because initial data IS present.
	b.WriteString("    for (let i = 0; i < header.fullCount; i++) {\n")
	b.WriteString("      const { entry, offset: next } = decodeFullEntry(data, pos);\n")
	b.WriteString("      pos = next;\n")
	b.WriteString("      freshAuthorityIDs?.add(entry.netID);\n")
	b.WriteString("      const highestEpoch = this.authorityEpochs.get(entry.netID);\n")
	b.WriteString("      if (highestEpoch !== undefined && entry.epoch !== highestEpoch && !isNewerAuthorityEpoch(entry.epoch, highestEpoch)) continue;\n")
	b.WriteString("      if (highestEpoch === undefined || isNewerAuthorityEpoch(entry.epoch, highestEpoch)) this.authorityEpochs.set(entry.netID, entry.epoch);\n")
	b.WriteString("      const prevBl = this.baselines.get(entry.netID);\n")
	b.WriteString("      const prevMeta = prevBl?.meta;\n")
	b.WriteString("      const previousEntity = prevMeta?.epoch === entry.epoch && prevMeta.type === entry.entityType ? prevMeta.lastEntity : undefined;\n")
	b.WriteString("      const entity = this.decodeEntity(entry.entityType, entry.snapshot, entry.initialData, entry.netID, entry.epoch, entry.producedAtMs, previousEntity);\n")
	b.WriteString("      this.baselines.set(entry.netID, entry.snapshot, { epoch: entry.epoch, type: entry.entityType, lastEntity: entity ?? undefined });\n")
	b.WriteString("      if (entity) entered.push(entity);\n")
	b.WriteString("    }\n\n")

	// Delta entries.
	b.WriteString("    for (let i = 0; i < header.deltaCount; i++) {\n")
	b.WriteString("      const { entry, offset: next } = decodeDeltaEntry(data, pos);\n")
	b.WriteString("      pos = next;\n")
	b.WriteString("      const bl = this.baselines.get(entry.netID);\n")
	b.WriteString("      if (!bl?.meta || bl.meta.epoch !== entry.epoch || bl.meta.type !== entry.entityType) continue;\n")
	b.WriteString("      const fieldSizes = this.fieldSizesFor(entry.entityType);\n")
	b.WriteString("      const hasVarTail = this.hasVarTailFor(entry.entityType);\n")
	b.WriteString("      const newSnap = applyDelta(fieldSizes, hasVarTail, bl.snapshot, entry.deltaData);\n")
	b.WriteString("      const entity = this.decodeEntity(entry.entityType, newSnap, null, entry.netID, entry.epoch, entry.producedAtMs, bl.meta.lastEntity);\n")
	b.WriteString("      this.baselines.set(entry.netID, newSnap, { epoch: entry.epoch, type: entry.entityType, lastEntity: entity ?? undefined });\n")
	b.WriteString("      if (entity) updated.push(entity);\n")
	b.WriteString("    }\n\n")

	// Removed and exited.
	b.WriteString("    const { ids: removed, offset: pos2 } = decodeRemovedIDs(data, pos, header.removedCount);\n")
	b.WriteString("    const { ids: exited, offset: pos3 } = decodeRemovedIDs(data, pos2, header.exitedCount);\n")
	b.WriteString("    const { sequence: processedInputSeq } = decodeInputAck(data, pos3, header.flags);\n\n")

	// Clean up baselines.
	b.WriteString("    for (const id of removed) this.baselines.delete(id);\n")
	b.WriteString("    for (const id of exited) this.baselines.delete(id);\n\n")
	// Once the enclosing stream generation is known, frame ordering protects
	// against delayed resurrection. Retaining tombstones for entities that are
	// no longer visible would otherwise grow this map for the life of a client.
	b.WriteString("    if (this.streamEpoch !== null) {\n")
	b.WriteString("      for (const id of removed) this.authorityEpochs.delete(id);\n")
	b.WriteString("      for (const id of exited) this.authorityEpochs.delete(id);\n")
	b.WriteString("    }\n\n")
	b.WriteString("    if (freshAuthorityIDs) {\n")
	b.WriteString("      for (const id of this.authorityEpochs.keys()) {\n")
	b.WriteString("        if (!freshAuthorityIDs.has(id)) this.authorityEpochs.delete(id);\n")
	b.WriteString("      }\n")
	b.WriteString("    }\n\n")

	b.WriteString("    return {\n")
	b.WriteString("      tick: header.tick, seq: header.seq, freshSnapshot, streamChanged: frameOrder.streamChanged, processedInputSeq,\n")
	b.WriteString("      entered, updated, removed, exited,\n")
	b.WriteString("    };\n")
	b.WriteString("  }\n\n")

	// decodeEntity dispatcher.
	//
	// `existing` is the previously-decoded entity for this netID (if any),
	// threaded through from baseline meta so per-entity decoders can restore
	// initial-only fields (e.g. strings carried only in full-snapshot initial
	// data). Each case narrows the type before passing it through.
	b.WriteString("  private decodeEntity(type_: number, snap: Uint8Array, initial: Uint8Array | null, netID: number, authorityEpoch: number, producedAtMs: number, existing?: AnyEntity): AnyEntity | null {\n")
	b.WriteString("    switch (type_) {\n")
	for _, ent := range g.schema.Entities {
		name := g.entityName(ent)
		fmt.Fprintf(&b,
			"      case %d: { const prev = existing && existing.entityType === %d ? existing : undefined; const e = decode%sSnapshot(snap, initial, prev); e.netID = netID; e.authorityEpoch = authorityEpoch; e.producedAtMs = producedAtMs; return e; }\n",
			ent.Kind, ent.Kind, name)
	}
	b.WriteString("      default: return null;\n")
	b.WriteString("    }\n")
	b.WriteString("  }\n\n")

	// fieldSizesFor dispatcher.
	b.WriteString("  private fieldSizesFor(type_: number): number[] {\n")
	b.WriteString("    switch (type_) {\n")
	for _, ent := range g.schema.Entities {
		upperName := strings.ToUpper(g.entityName(ent))
		fmt.Fprintf(&b, "      case %d: return %s_FIELD_SIZES;\n", ent.Kind, upperName)
	}
	b.WriteString("      default: return [];\n")
	b.WriteString("    }\n")
	b.WriteString("  }\n\n")

	// hasVarTailFor dispatcher.
	b.WriteString("  private hasVarTailFor(type_: number): boolean {\n")
	b.WriteString("    switch (type_) {\n")
	for _, ent := range g.schema.Entities {
		upperName := strings.ToUpper(g.entityName(ent))
		fmt.Fprintf(&b, "      case %d: return %s_HAS_VAR_TAIL;\n", ent.Kind, upperName)
	}
	b.WriteString("      default: return false;\n")
	b.WriteString("    }\n")
	b.WriteString("  }\n")

	b.WriteString("}\n")

	return b.String()
}

// writeVarTailDecoder emits TypeScript that parses the snapshot's var-tail
// into a typed item array on the decoded entity. Called once per decode
// function after all scalar fields have been consumed.
//
// Panics at codegen time if ItemFields is empty — the generated while loop
// would be an infinite loop because no field decoder would advance `o`.
func writeVarTailDecoder(b *strings.Builder, ent EntitySchema, itemType string) {
	vt := ent.VarTail
	if len(vt.ItemFields) == 0 {
		panic(fmt.Sprintf("sdkgen: entity kind %d var-tail %q has no ItemFields; decoder would be an infinite loop", ent.Kind, vt.Name))
	}
	fmt.Fprintf(b, "  const %sByteLen = readUint16(snap, o); o += 2;\n", vt.Name)
	fmt.Fprintf(b, "  const %sEnd = o + %sByteLen;\n", vt.Name, vt.Name)
	fmt.Fprintf(b, "  const %s: %s[] = [];\n", vt.Name, itemType)
	fmt.Fprintf(b, "  while (o < %sEnd) {\n", vt.Name)
	for _, f := range vt.ItemFields {
		writeFieldDecoderIndented(b, f, "    ")
	}
	fmt.Fprintf(b, "    %s.push({ %s });\n", vt.Name, joinItemFieldNames(vt.ItemFields))
	b.WriteString("  }\n")
}

// writeFieldDecoderIndented is writeFieldDecoder with configurable indent, so
// it can be nested inside the while loop for var-tail items.
//
// Panics on unsupported encodings so a new var-tail field type can't silently
// emit missing decoder lines. String is not supported in var-tail items because
// the client-side while-loop needs a fixed stride per iteration; length-prefixed
// strings belong in the fixed-layout portion of the snapshot.
func writeFieldDecoderIndented(b *strings.Builder, field BindingSchemaField, indent string) {
	switch field.Encoding {
	case "f32":
		fmt.Fprintf(b, "%sconst %s = readFloat32(snap, o); o += 4;\n", indent, field.Name)
	case "qvel":
		fmt.Fprintf(b, "%sconst %s = unVel(readInt16(snap, o), %g); o += 2;\n", indent, field.Name, field.Scale)
	case "qangle":
		fmt.Fprintf(b, "%sconst %s = unAngle(readUint16(snap, o)); o += 2;\n", indent, field.Name)
	case "qnorm":
		fmt.Fprintf(b, "%sconst %s = unNorm(snap[o]); o += 1;\n", indent, field.Name)
	case "u8":
		fmt.Fprintf(b, "%sconst %s = snap[o]; o += 1;\n", indent, field.Name)
	case "u16":
		fmt.Fprintf(b, "%sconst %s = readUint16(snap, o); o += 2;\n", indent, field.Name)
	case "u32":
		fmt.Fprintf(b, "%sconst %s = readUint32(snap, o); o += 4;\n", indent, field.Name)
	case "i16":
		fmt.Fprintf(b, "%sconst %s = readInt16(snap, o); o += 2;\n", indent, field.Name)
	case "bool":
		fmt.Fprintf(b, "%sconst %s = !!snap[o]; o += 1;\n", indent, field.Name)
	default:
		panic(fmt.Sprintf("sdkgen: unsupported var-tail field encoding %q for field %q", field.Encoding, field.Name))
	}
}

func joinItemFieldNames(fields []BindingSchemaField) string {
	names := make([]string, len(fields))
	for i, f := range fields {
		names[i] = f.Name
	}
	return strings.Join(names, ", ")
}

// writeFieldDecoder emits a TypeScript line that consumes one scalar field
// from the fixed-layout portion of an entity snapshot. Strings are handled
// separately by writeInitialFieldDecoder (they live in the initial payload),
// so string encodings must not appear here.
func writeFieldDecoder(b *strings.Builder, field BindingSchemaField) {
	switch field.Encoding {
	case "f32":
		fmt.Fprintf(b, "  const %s = readFloat32(snap, o); o += 4;\n", field.Name)
	case "qvel":
		fmt.Fprintf(b, "  const %s = unVel(readInt16(snap, o), %g); o += 2;\n", field.Name, field.Scale)
	case "qangle":
		fmt.Fprintf(b, "  const %s = unAngle(readUint16(snap, o)); o += 2;\n", field.Name)
	case "qnorm":
		fmt.Fprintf(b, "  const %s = unNorm(snap[o]); o += 1;\n", field.Name)
	case "u8":
		fmt.Fprintf(b, "  const %s = snap[o]; o += 1;\n", field.Name)
	case "u16":
		fmt.Fprintf(b, "  const %s = readUint16(snap, o); o += 2;\n", field.Name)
	case "u32":
		fmt.Fprintf(b, "  const %s = readUint32(snap, o); o += 4;\n", field.Name)
	case "i16":
		fmt.Fprintf(b, "  const %s = readInt16(snap, o); o += 2;\n", field.Name)
	case "bool":
		fmt.Fprintf(b, "  const %s = !!snap[o]; o += 1;\n", field.Name)
	default:
		panic(fmt.Sprintf("sdkgen: unsupported snapshot field encoding %q for field %q", field.Encoding, field.Name))
	}
}

// writeInitialFieldDecoder emits one TS decode statement for an
// initial-only field. It assumes a `let initialOff = 0;` variable was
// emitted earlier in the same function and updates that offset after
// each read so subsequent fields find the right bytes.
//
// Supported encodings:
//
//	string — 1-byte length prefix + UTF-8 bytes
//	u8     — 1 byte
//	i8     — 1 byte signed
//	u16    — 2 bytes big-endian unsigned
//	i16    — 2 bytes big-endian signed
//	u32    — 4 bytes big-endian unsigned
//	f32    — 4 bytes IEEE-754 big-endian
//	bool   — 1 byte (0/1)
//
// Unknown encodings fall back to the previous existing-or-zero default
// so a new wire type doesn't silently corrupt other fields' offsets.
func writeInitialFieldDecoder(b *strings.Builder, field BindingSchemaField, _ string) {
	n := field.Name
	switch field.Encoding {
	case "string":
		fmt.Fprintf(b, "  const %s = initial && initialOff < initial.length ? decodeLengthPrefixedStringU8(initial.subarray(initialOff)) : (existing?.%s ?? \"\");\n", n, n)
		fmt.Fprintf(b, "  if (initial && initialOff < initial.length) initialOff += 1 + initial[initialOff];\n")
	case "u8":
		fmt.Fprintf(b, "  const %s = initial && initialOff < initial.length ? initial[initialOff] : (existing?.%s ?? 0);\n", n, n)
		b.WriteString("  if (initial && initialOff < initial.length) initialOff += 1;\n")
	case "i8":
		fmt.Fprintf(b, "  const %s = initial && initialOff < initial.length ? (initial[initialOff] << 24 >> 24) : (existing?.%s ?? 0);\n", n, n)
		b.WriteString("  if (initial && initialOff < initial.length) initialOff += 1;\n")
	case "u16":
		fmt.Fprintf(b, "  const %s = initial && initialOff + 2 <= initial.length ? readUint16(initial, initialOff) : (existing?.%s ?? 0);\n", n, n)
		b.WriteString("  if (initial && initialOff + 2 <= initial.length) initialOff += 2;\n")
	case "i16":
		fmt.Fprintf(b, "  const %s = initial && initialOff + 2 <= initial.length ? readInt16(initial, initialOff) : (existing?.%s ?? 0);\n", n, n)
		b.WriteString("  if (initial && initialOff + 2 <= initial.length) initialOff += 2;\n")
	case "u32":
		fmt.Fprintf(b, "  const %s = initial && initialOff + 4 <= initial.length ? readUint32(initial, initialOff) : (existing?.%s ?? 0);\n", n, n)
		b.WriteString("  if (initial && initialOff + 4 <= initial.length) initialOff += 4;\n")
	case "f32":
		fmt.Fprintf(b, "  const %s = initial && initialOff + 4 <= initial.length ? readFloat32(initial, initialOff) : (existing?.%s ?? 0);\n", n, n)
		b.WriteString("  if (initial && initialOff + 4 <= initial.length) initialOff += 4;\n")
	case "bool":
		fmt.Fprintf(b, "  const %s = initial && initialOff < initial.length ? (initial[initialOff] !== 0) : (existing?.%s ?? false);\n", n, n)
		b.WriteString("  if (initial && initialOff < initial.length) initialOff += 1;\n")
	default:
		fmt.Fprintf(b, "  const %s = existing?.%s ?? 0;\n", n, n)
	}
}

func joinInts(ints []int) string {
	parts := make([]string, len(ints))
	for i, v := range ints {
		parts[i] = fmt.Sprintf("%d", v)
	}
	return strings.Join(parts, ", ")
}

// ---------------------------------------------------------------------------
// client.ts
// ---------------------------------------------------------------------------

func (g *Generator) genClient() string {
	var b strings.Builder
	gameName := titleCase(g.schema.Game)

	b.WriteString("// GENERATED by sdkgen — do not edit.\n\n")

	b.WriteString("import { Transport } from \"./transport.js\";\n")
	fmt.Fprintf(&b, "import { %sDeltaDecoder } from \"./delta-decoder.js\";\n", gameName)
	hasTypedEvents := len(g.schema.BroadcastTypes) > 0 || len(g.schema.ServerEventTypes) > 0
	hasTypedOps := len(g.schema.Operations) > 0
	if hasTypedEvents {
		// TypedDispatcher routes both HandleAll[T] broadcasts and
		// RegisterEvent[T] typed server events. Per-typed-server-event
		// classes are imported eagerly so the on<EventName>(handler)
		// wrappers below can pass them to typedEvents.on.
		var imports []string
		imports = append(imports, "TypedDispatcher")
		for _, name := range serverEventClassNames(g.schema.ServerEventTypes) {
			imports = append(imports, name)
		}
		// OperationError is auto-registered as a server event by Phase 1's
		// registerFrameworkOps and so already lives in the broadcasts.ts
		// import set when hasTypedEvents is true. The typed-op response
		// handler intercepts its typeID to reject the matching pending
		// promise; no extra import needed beyond the eager list above.
		fmt.Fprintf(&b, "import { %s } from \"./broadcasts.js\";\n", strings.Join(imports, ", "))
	}
	if hasTypedOps {
		// Per-op Request + Response classes — imported eagerly so the
		// generated client.<opName>() wrapper methods can hand the Response
		// class to callOp<Req, Res> as the decode hook. Multiple ops can
		// share a Response class (e.g. MarketOrderResultResponse covers
		// create/cancel/instant-trade) so dedupe before emitting.
		seen := map[string]struct{}{}
		var imports []string
		for _, op := range g.schema.Operations {
			for _, name := range []string{typedOpRequestClassName(op), typedOpResponseClassName(op)} {
				if _, dup := seen[name]; dup {
					continue
				}
				seen[name] = struct{}{}
				imports = append(imports, name)
			}
		}
		// Deterministic order for codegen-stability.
		sort.Strings(imports)
		fmt.Fprintf(&b, "import { %s } from \"./operations.js\";\n", strings.Join(imports, ", "))
	}

	b.WriteString("\n")

	// Options interface.
	fmt.Fprintf(&b, "export interface %sClientOptions {\n", gameName)
	b.WriteString("  url: string;\n")
	b.WriteString("  onOpen?: () => void;\n")
	b.WriteString("  onClose?: (ev: CloseEvent) => void;\n")
	b.WriteString("  onError?: (ev: Event) => void;\n")
	b.WriteString("}\n\n")

	// Client class.
	fmt.Fprintf(&b, "export class %sClient {\n", gameName)
	b.WriteString("  private transport: Transport;\n")
	fmt.Fprintf(&b, "  private decoder = new %sDeltaDecoder();\n", gameName)
	if hasTypedEvents {
		b.WriteString("  /** Typed broadcast dispatcher — register handlers for AoI-filtered\n")
		b.WriteString("   *  events emitted by the server's HandleAll[T] machinery. */\n")
		b.WriteString("  readonly typedEvents = new TypedDispatcher();\n")
	}
	if hasTypedOps {
		// Typed-op Promise correlator — keyed on a 64-bit request_id so the
		// counter never wraps in practice. Each pending entry carries the
		// Response class to feed the matching decode call when the response
		// arrives. OperationError responses are intercepted before the decode
		// (different typeID) and reject the promise with the carried code.
		b.WriteString("  private pendingTypedOps = new Map<bigint, { resolve: (msg: any) => void; reject: (err: Error) => void; resCls: { typeID: number; decode(buf: Uint8Array): any } }>();\n")
		b.WriteString("  private nextTypedOpRequestID: bigint = 1n;\n")
	}
	b.WriteString("\n")

	fmt.Fprintf(&b, "  constructor(private options: %sClientOptions) {\n", gameName)
	b.WriteString("    this.transport = new Transport(options.url);\n")
	b.WriteString("  }\n\n")

	// connect / disconnect / connected
	b.WriteString("  connect(): void {\n")
	b.WriteString("    this.transport.connect();\n")
	b.WriteString("    const ws = this.transport.socket!;\n")
	b.WriteString("    if (this.options.onOpen) ws.onopen = this.options.onOpen;\n")
	b.WriteString("    if (this.options.onClose) ws.onclose = this.options.onClose;\n")
	b.WriteString("    if (this.options.onError) ws.onerror = this.options.onError;\n")
	b.WriteString("    this.transport.onEvent((payload) => this.handleEvent(payload));\n")
	if hasTypedOps {
		b.WriteString("    this.transport.onOperation((payload) => this.handleOperation(payload));\n")
	}
	b.WriteString("  }\n\n")

	if hasTypedOps {
		b.WriteString("  disconnect(): void {\n")
		b.WriteString("    // Reject any pending operations.\n")
		b.WriteString("    for (const pending of this.pendingTypedOps.values()) {\n")
		b.WriteString("      pending.reject(new Error(\"client disconnected\"));\n")
		b.WriteString("    }\n")
		b.WriteString("    this.pendingTypedOps.clear();\n")
		b.WriteString("    this.transport.close();\n")
		b.WriteString("  }\n")
	} else {
		b.WriteString("  disconnect(): void { this.transport.close(); }\n")
	}
	b.WriteString("  get connected(): boolean { return this.transport.connected; }\n\n")

	b.WriteString("  /** Raw transport handle for advanced use (operations channel,\n")
	b.WriteString("   *  custom protocol extensions). Most app code should use the typed\n")
	b.WriteString("   *  send* / on* methods on this class instead. */\n")
	b.WriteString("  get rawTransport(): Transport { return this.transport; }\n\n")

	// Event dispatch.
	//
	// Channel 0x00 carries the typed reflection-codec wire format only:
	// repeated [typeID:u32 LE][body_len:u32 LE][body] until end of message.
	// Each entry dispatches to typedEvents (mmokit.RegisterEvent[T] on the
	// server, decoded by the matching TS class on the client).
	b.WriteString("  private handleEvent(payload: Uint8Array): void {\n")
	b.WriteString("    if (payload.length === 0) return;\n")
	if hasTypedEvents {
		b.WriteString("    let off = 0;\n")
		b.WriteString("    while (off + 8 <= payload.length) {\n")
		b.WriteString("      const view = new DataView(payload.buffer, payload.byteOffset + off, 8);\n")
		b.WriteString("      const typeID = view.getUint32(0, true);\n")
		b.WriteString("      const bodyLen = view.getUint32(4, true);\n")
		b.WriteString("      off += 8;\n")
		b.WriteString("      if (off + bodyLen > payload.length) {\n")
		b.WriteString("        console.warn(`typed-event frame: truncated body for typeID=0x${typeID.toString(16)}`);\n")
		b.WriteString("        return;\n")
		b.WriteString("      }\n")
		b.WriteString("      const body = payload.subarray(off, off + bodyLen);\n")
		b.WriteString("      off += bodyLen;\n")
		b.WriteString("      this.typedEvents.dispatch(typeID, body);\n")
		b.WriteString("    }\n")
	}
	b.WriteString("  }\n\n")

	// --- Typed client-input send ---
	//
	// Wire path: TS class instance → encode() body bytes → transport
	// sendClientInput frames as [0x00][u32 typeID][u32 bodyLen][body].
	// Server-side ReflectUnmarshalOnStage decodes the body back into
	// the registered Go type and dispatches via mmokit.HandleClient.
	//
	// The TS-side type bound matches every class generated in inputs.ts:
	// each has `static readonly typeID: number` and an `encode(): Uint8Array`
	// instance method. This signature works whether or not inputs.ts was
	// emitted (the server's HandleClient registry may be empty).
	b.WriteString("  /** Send a typed client-input message (mmokit.HandleClient).\n")
	b.WriteString("   *\n")
	b.WriteString("   *  msg must be an instance of a class generated into inputs.ts —\n")
	b.WriteString("   *  exposing static typeID and instance encode(): Uint8Array. The\n")
	b.WriteString("   *  resulting wire frame is dispatched server-side to the matching\n")
	b.WriteString("   *  HandleClient[T] handler. */\n")
	b.WriteString("  send(msg: { encode(): Uint8Array }): void {\n")
	b.WriteString("    const ctor = msg.constructor as unknown as { typeID: number };\n")
	b.WriteString("    this.transport.sendClientInput(ctor.typeID, msg.encode());\n")
	b.WriteString("  }\n\n")

	// --- Typed server-event handlers (mmokit.RegisterEvent[T]) ---
	//
	// Each typed registration produces a `client.on<EventName>(handler)`
	// method that subscribes against the TypedDispatcher under the hood.
	// The dispatcher dispatches by typeID — set on the wire by the server's
	// afterSend path and matched against the class's static typeID.
	//
	// Naming convention: Go `pkg.PlayerSpawned` → TS class `PlayerSpawned`
	// (last dot segment) → method `onPlayerSpawned`.
	for _, st := range g.schema.ServerEventTypes {
		writeServerEventHandler(&b, st)
	}

	// --- Typed operations (RegisterOp[Req, Res] on channel 0x01) ---
	//
	// Wire format: [typeID:u32 LE][request_id:u64 LE][body_len:u32 LE][body]
	// (channel byte stripped by the transport). Routed via pendingTypedOps
	// (Map<bigint, ...>) keyed on the 64-bit request_id assigned by callOp().
	// OperationError typeID intercepts a generic failure and rejects the
	// promise with code+message.
	//
	// Each typed registration produces a `client.<opName>(req): Promise<Res>`
	// wrapper that allocates a 64-bit request_id, encodes the typed-op frame,
	// and awaits the matching response. callOp is the shared helper.
	if hasTypedOps {
		b.WriteString("  private handleOperation(payload: Uint8Array): void {\n")
		b.WriteString("    if (payload.length === 0) return;\n")
		writeTypedOpDispatch(&b)
		b.WriteString("    return;\n")
		b.WriteString("  }\n\n")
	}
	if hasTypedOps {
		// Private callOp helper — one per client. Builds the
		// [0x01][typeID][requestID][bodyLen][body] frame in a single
		// allocation, registers the pending slot, and returns a Promise that
		// resolves to the decoded Response (or rejects on OperationError).
		b.WriteString("  /** Private helper: encode + send a typed-op request, return a\n")
		b.WriteString("   *  Promise that resolves with the decoded Response. */\n")
		b.WriteString("  private callOp<Req extends { encode(): Uint8Array }, Res>(\n")
		b.WriteString("    req: Req,\n")
		b.WriteString("    resCls: { typeID: number; decode(buf: Uint8Array): Res }\n")
		b.WriteString("  ): Promise<Res> {\n")
		b.WriteString("    const reqID = this.nextTypedOpRequestID++;\n")
		b.WriteString("    const reqTypeID = (req.constructor as unknown as { typeID: number }).typeID;\n")
		b.WriteString("    const body = req.encode();\n")
		b.WriteString("    const frame = new Uint8Array(1 + 4 + 8 + 4 + body.length);\n")
		b.WriteString("    const dv = new DataView(frame.buffer);\n")
		b.WriteString("    frame[0] = 0x01;\n")
		b.WriteString("    dv.setUint32(1, reqTypeID, true);\n")
		b.WriteString("    dv.setBigUint64(5, reqID, true);\n")
		b.WriteString("    dv.setUint32(13, body.length, true);\n")
		b.WriteString("    frame.set(body, 17);\n")
		b.WriteString("    return new Promise<Res>((resolve, reject) => {\n")
		b.WriteString("      this.pendingTypedOps.set(reqID, { resolve, reject, resCls });\n")
		b.WriteString("      this.transport.sendRaw(frame);\n")
		b.WriteString("    });\n")
		b.WriteString("  }\n\n")

		// Per-op wrapper methods.
		for _, op := range g.schema.Operations {
			reqCls := typedOpRequestClassName(op)
			resCls := typedOpResponseClassName(op)
			method := typedOpMethodName(reqCls)
			fmt.Fprintf(&b, "  /** Typed op %s → %s (kind=%s). */\n", op.RequestTypeName, op.ResponseTypeName, op.Kind)
			fmt.Fprintf(&b, "  %s(req: %s): Promise<%s> {\n", method, reqCls, resCls)
			fmt.Fprintf(&b, "    return this.callOp<%s, %s>(req, %s);\n", reqCls, resCls, resCls)
			b.WriteString("  }\n\n")
		}
	}

	// Baseline clear.
	b.WriteString("  /** Clear delta baselines (call on cell change / reconnect). */\n")
	b.WriteString("  clearBaselines(): void { this.decoder.clear(); }\n")

	b.WriteString("}\n")

	return b.String()
}

// ---------------------------------------------------------------------------
// index.ts
// ---------------------------------------------------------------------------

func (g *Generator) genIndex() string {
	gameName := titleCase(g.schema.Game)
	var b strings.Builder
	b.WriteString("// GENERATED by sdkgen — do not edit.\n\n")
	fmt.Fprintf(&b, "export { %sClient } from \"./client.js\";\n", gameName)
	fmt.Fprintf(&b, "export type { %sClientOptions } from \"./client.js\";\n", gameName)
	b.WriteString("export type { AnyEntity, DeltaWorldUpdate } from \"./entities.js\";\n")
	b.WriteString("export * from \"./entities.js\";\n")
	fmt.Fprintf(&b, "export { %sDeltaDecoder } from \"./delta-decoder.js\";\n", gameName)
	b.WriteString("export { Transport } from \"./transport.js\";\n")
	if len(g.schema.BroadcastTypes) > 0 || len(g.schema.ServerEventTypes) > 0 {
		// Re-export every generated broadcast / typed-server-event class
		// plus the dispatcher so app code imports them via the SDK's public
		// surface, not directly from the internal broadcasts.ts file.
		var names []string
		names = append(names, "TypedDispatcher")
		for _, bt := range g.schema.BroadcastTypes {
			names = append(names, broadcastClassName(bt.Name))
		}
		for _, st := range g.schema.ServerEventTypes {
			names = append(names, broadcastClassName(st.Name))
		}
		sort.Strings(names)
		fmt.Fprintf(&b, "export { %s } from \"./broadcasts.js\";\n", strings.Join(names, ", "))
	}
	if len(g.schema.ClientInputTypes) > 0 {
		// Re-export every generated client-input class so app code imports
		// them via the SDK's public surface (e.g. `import { SetMoveTarget }
		// from "@sdk"`) rather than reaching into the internal inputs.ts
		// file directly.
		var names []string
		for _, ct := range g.schema.ClientInputTypes {
			names = append(names, broadcastClassName(ct.Name))
		}
		sort.Strings(names)
		fmt.Fprintf(&b, "export { %s } from \"./inputs.js\";\n", strings.Join(names, ", "))
	}
	if len(g.schema.Operations) > 0 {
		// Re-export every generated typed-op Request + Response class so app
		// code can construct requests via the SDK's public surface. Multiple
		// ops can share a Response class (MarketOrderResultResponse) so
		// dedupe.
		seen := map[string]struct{}{}
		var names []string
		for _, op := range g.schema.Operations {
			for _, name := range []string{typedOpRequestClassName(op), typedOpResponseClassName(op)} {
				if _, dup := seen[name]; dup {
					continue
				}
				seen[name] = struct{}{}
				names = append(names, name)
			}
		}
		sort.Strings(names)
		fmt.Fprintf(&b, "export { %s } from \"./operations.js\";\n", strings.Join(names, ", "))
	}
	if len(g.schema.Entities) > 0 {
		// Re-export the EntityType const + type alias so app code
		// imports them via the SDK's public surface.
		b.WriteString("export { EntityType } from \"./entityType.js\";\n")
		b.WriteString("export type { EntityTypeValue } from \"./entityType.js\";\n")
	}

	return b.String()
}
