package main

import (
	"fmt"
	"sort"
	"strings"
)

// Generator produces TypeScript SDK files from a protocol schema.
type Generator struct {
	schema ProtocolSchema
	msgs   MessageDB
	outDir string
}

// resolveMsg looks up a proto message by full name.
func (g *Generator) resolveMsg(fullName string) *ProtoMessage {
	return g.msgs[fullName]
}

// protoImportPath returns the relative import path from the SDK output dir to
// gen/es proto files. For now we use a path alias that games configure in tsconfig.
func protoImportPath(msg *ProtoMessage) string {
	return fmt.Sprintf("@gen/%s", msg.ImportPath)
}

// ---------------------------------------------------------------------------
// transport.ts
// ---------------------------------------------------------------------------

func (g *Generator) genTransport() string {
	return `// GENERATED by sdkgen — do not edit.

const CH_EVENT = 0x00;
const CH_OPERATION = 0x01;
const CH_CLIENT_INPUT = 0x02;

export type MessageHandler = (data: Uint8Array) => void;

export class Transport {
  private ws: WebSocket | null = null;
  private eventHandlers: MessageHandler[] = [];
  private operationHandlers: MessageHandler[] = [];

  constructor(private url: string) {}

  connect(): void {
    this.ws = new WebSocket(this.url);
    this.ws.binaryType = "arraybuffer";
    this.ws.onmessage = (ev) => {
      const data = new Uint8Array(ev.data as ArrayBuffer);
      if (data.length < 1) return;
      const channel = data[0];
      const payload = data.subarray(1);
      if (channel === CH_EVENT) {
        for (const h of this.eventHandlers) h(payload);
      } else if (channel === CH_OPERATION) {
        for (const h of this.operationHandlers) h(payload);
      }
    };
  }

  get socket(): WebSocket | null { return this.ws; }
  get connected(): boolean { return this.ws?.readyState === WebSocket.OPEN; }

  close(): void { this.ws?.close(); this.ws = null; }

  sendEvent(data: Uint8Array): void {
    if (!this.ws || this.ws.readyState !== WebSocket.OPEN) return;
    const frame = new Uint8Array(1 + data.length);
    frame[0] = CH_EVENT;
    frame.set(data, 1);
    this.ws.send(frame);
  }

  sendOperation(data: Uint8Array): void {
    if (!this.ws || this.ws.readyState !== WebSocket.OPEN) return;
    const frame = new Uint8Array(1 + data.length);
    frame[0] = CH_OPERATION;
    frame.set(data, 1);
    this.ws.send(frame);
  }

  /**
   * Send a typed client-input frame (mmokit.HandleClient registry).
   * Wire layout: [byte 0x02][u32 typeID][u32 bodyLen][body bytes].
   * Body is produced by the matching TS class's encode() instance method;
   * the server resolves typeID back to the registered Go type and decodes
   * the body via the same reflection codec used for broadcast events.
   */
  sendClientInput(typeID: number, body: Uint8Array): void {
    if (!this.ws || this.ws.readyState !== WebSocket.OPEN) return;
    const frame = new Uint8Array(1 + 4 + 4 + body.length);
    const dv = new DataView(frame.buffer);
    frame[0] = CH_CLIENT_INPUT;
    dv.setUint32(1, typeID, true);
    dv.setUint32(5, body.length, true);
    frame.set(body, 9);
    this.ws.send(frame);
  }

  onEvent(handler: MessageHandler): void { this.eventHandlers.push(handler); }
  onOperation(handler: MessageHandler): void { this.operationHandlers.push(handler); }
}
`
}

// ---------------------------------------------------------------------------
// entities.ts
// ---------------------------------------------------------------------------

func (g *Generator) genEntities() string {
	var b strings.Builder
	b.WriteString("// GENERATED by sdkgen — do not edit.\n\n")

	var entityNames []string

	for _, ent := range g.schema.Entities {
		name := g.entityName(ent)
		entityNames = append(entityNames, name)

		fmt.Fprintf(&b, "/** Entity kind %d. */\n", ent.Kind)
		fmt.Fprintf(&b, "export interface %s {\n", name)
		b.WriteString("  netID: number;\n")
		fmt.Fprintf(&b, "  entityType: %d;\n", ent.Kind)
		b.WriteString("  /**\n")
		b.WriteString("   * Cluster-clock stamp (Unix ms) from the authoritative producer at\n")
		b.WriteString("   * the moment this state was emitted. Preserves the producer's\n")
		b.WriteString("   * timeline through any relay hops. Used as the per-entity time-base\n")
		b.WriteString("   * for snapshot interpolation.\n")
		b.WriteString("   */\n")
		b.WriteString("  producedAtMs: number;\n")

		for _, binding := range ent.Bindings {
			for _, field := range binding.Fields {
				if field.Initial {
					continue
				}
				tsType := encodingToTSType(field.Encoding)
				fmt.Fprintf(&b, "  %s: %s;\n", field.Name, tsType)
			}
		}
		// Initial fields.
		for _, binding := range ent.Bindings {
			for _, field := range binding.Fields {
				if !field.Initial {
					continue
				}
				tsType := encodingToTSType(field.Encoding)
				fmt.Fprintf(&b, "  %s: %s;\n", field.Name, tsType)
			}
		}

		// Var-tail field (if any).
		if ent.VarTail != nil {
			itemType := g.tailItemTypeName(ent)
			fmt.Fprintf(&b, "  %s: %s[];\n", ent.VarTail.Name, itemType)
		}

		b.WriteString("}\n\n")

		// Emit the var-tail item type interface after the entity interface.
		if ent.VarTail != nil {
			itemType := g.tailItemTypeName(ent)
			fmt.Fprintf(&b, "/** Item record for %s.%s var-tail. */\n", name, ent.VarTail.Name)
			fmt.Fprintf(&b, "export interface %s {\n", itemType)
			for _, f := range ent.VarTail.ItemFields {
				tsType := encodingToTSType(f.Encoding)
				fmt.Fprintf(&b, "  %s: %s;\n", f.Name, tsType)
			}
			b.WriteString("}\n\n")
		}
	}

	// Union type.
	if len(entityNames) > 0 {
		b.WriteString("export type AnyEntity = ")
		b.WriteString(strings.Join(entityNames, " | "))
		b.WriteString(";\n\n")
	}

	b.WriteString("export interface DeltaWorldUpdate {\n")
	b.WriteString("  tick: number;\n")
	b.WriteString("  seq: number;\n")
	b.WriteString("  /**\n")
	b.WriteString("   * Set when the server's ReplicationSystem sent this frame as the\n")
	b.WriteString("   * first frame to this connection — i.e. on initial login or on every\n")
	b.WriteString("   * cross-cell handoff. The SDK decoder clears its per-entity baselines\n")
	b.WriteString("   * before applying the frame; clients should treat the frame's Entered\n")
	b.WriteString("   * list as the authoritative current entity set and drop any stale\n")
	b.WriteString("   * entities they retained from before. Topology-transparent: clients\n")
	b.WriteString("   * never learn about cells, authority transfers, or server boundaries.\n")
	b.WriteString("   */\n")
	b.WriteString("  freshSnapshot: boolean;\n")
	b.WriteString("  entered: AnyEntity[];\n")
	b.WriteString("  updated: AnyEntity[];\n")
	b.WriteString("  removed: number[];\n")
	b.WriteString("  exited: number[];\n")
	b.WriteString("}\n")

	return b.String()
}

func (g *Generator) entityName(ent EntitySchema) string {
	if ent.Name != "" {
		return ent.Name + "Entity"
	}
	return fmt.Sprintf("Entity%d", ent.Kind)
}

// tailItemTypeName returns the generated TypeScript interface name for a
// var-tail's per-item record. Example: Ship → ShipStatusEffectsItem.
//
// Strips the trailing "Entity" suffix from entityName() so tail-item names
// read as ShipStatusEffectsItem rather than ShipEntityStatusEffectsItem.
func (g *Generator) tailItemTypeName(ent EntitySchema) string {
	if ent.VarTail == nil {
		return ""
	}
	name := strings.TrimSuffix(g.entityName(ent), "Entity")
	return name + titleCase(ent.VarTail.Name) + "Item"
}

func encodingToTSType(enc string) string {
	switch enc {
	case "string":
		return "string"
	case "bool":
		return "boolean"
	default:
		return "number"
	}
}

// ---------------------------------------------------------------------------
// delta-decoder.ts
// ---------------------------------------------------------------------------

func (g *Generator) genDeltaDecoder() string {
	var b strings.Builder
	b.WriteString("// GENERATED by sdkgen — do not edit.\n\n")
	b.WriteString("import {\n")
	b.WriteString("  readFloat32, readInt16, readUint16, readUint32,\n")
	b.WriteString("  unAngle, unNorm, unVel,\n")
	b.WriteString("  decodeFrameHeader, decodeFullEntry, decodeDeltaEntry, decodeRemovedIDs,\n")
	b.WriteString("  FRAME_FLAG_FRESH_SNAPSHOT,\n")
	b.WriteString("  applyDelta, BaselineStore,\n")
	b.WriteString("  decodeLengthPrefixedStringU8,\n")
	b.WriteString("} from \"./_core/delta-decoder-core.js\";\n")

	// Import entity types AND per-entity var-tail item types. The decode
	// functions below allocate slices typed as `<Entity><Tail>Item[]`, so
	// every entity with a var-tail contributes its item interface to the
	// import list alongside its entity interface.
	var entityNames []string
	for _, ent := range g.schema.Entities {
		entityNames = append(entityNames, g.entityName(ent))
		if item := g.tailItemTypeName(ent); item != "" {
			entityNames = append(entityNames, item)
		}
	}
	fmt.Fprintf(&b, "import type { %s, AnyEntity, DeltaWorldUpdate } from \"./entities.js\";\n\n", strings.Join(entityNames, ", "))

	// Generate per-entity constants and decode functions.
	for _, ent := range g.schema.Entities {
		name := g.entityName(ent)
		upperName := strings.ToUpper(name)

		// Field sizes array — strip the trailing -1 var-tail marker. The
		// client-side applyDelta expects only the fixed field sizes and takes
		// hasVarTail as a separate boolean. Leaving the -1 in the array
		// miscounts totalLogicalFields and fixedSize, corrupting delta
		// application.
		fixedLayout := ent.Layout
		hasVarTail := false
		if len(fixedLayout) > 0 && fixedLayout[len(fixedLayout)-1] == -1 {
			hasVarTail = true
			fixedLayout = fixedLayout[:len(fixedLayout)-1]
		}
		fmt.Fprintf(&b, "const %s_FIELD_SIZES = [%s];\n", upperName, joinInts(fixedLayout))
		fmt.Fprintf(&b, "const %s_HAS_VAR_TAIL = %v;\n\n", upperName, hasVarTail)

		// Decode snapshot function.
		fmt.Fprintf(&b, "function decode%sSnapshot(snap: Uint8Array, initial: Uint8Array | null, existing?: %s): %s {\n", name, name, name)
		b.WriteString("  let o = 0;\n")

		// Snapshot fields (non-initial).
		for _, binding := range ent.Bindings {
			for _, field := range binding.Fields {
				if field.Initial {
					continue
				}
				writeFieldDecoder(&b, field)
			}
		}

		// Var-tail parsing.
		if ent.VarTail != nil {
			writeVarTailDecoder(&b, ent, g.tailItemTypeName(ent))
		}

		// Initial fields.
		for _, binding := range ent.Bindings {
			for _, field := range binding.Fields {
				if !field.Initial {
					continue
				}
				writeInitialFieldDecoder(&b, field, ent.InitialData)
			}
		}

		// Return object. `producedAtMs` is overwritten by the caller from
		// the wire entry's stamp; initializing to 0 keeps the interface
		// satisfied even if a future path forgets to set it.
		fmt.Fprintf(&b, "  return { netID: 0, producedAtMs: 0, entityType: %d", ent.Kind)
		for _, binding := range ent.Bindings {
			for _, field := range binding.Fields {
				fmt.Fprintf(&b, ", %s", field.Name)
			}
		}
		if ent.VarTail != nil {
			fmt.Fprintf(&b, ", %s", ent.VarTail.Name)
		}
		b.WriteString(" };\n")
		b.WriteString("}\n\n")
	}

	// Decoder class.
	gameName := titleCase(g.schema.Game)
	fmt.Fprintf(&b, "export class %sDeltaDecoder {\n", gameName)
	// Baseline meta caches the last fully-decoded entity so delta frames can
	// restore initial-only fields (e.g. string names that are only transmitted
	// in the initial data block of a full snapshot). Without this, delta
	// decoding would reset those fields to empty strings every tick.
	b.WriteString("  private baselines = new BaselineStore<{ type: number; lastEntity?: AnyEntity }>();\n\n")

	b.WriteString("  clear(): void { this.baselines.clear(); }\n\n")

	b.WriteString("  decode(data: Uint8Array): DeltaWorldUpdate {\n")
	b.WriteString("    const { header, offset: pos0 } = decodeFrameHeader(data, 0);\n")
	b.WriteString("    let pos = pos0;\n\n")

	// If the server flagged this frame as fresh (first frame for this
	// conn on the sending ReplicationSystem — login or post-handoff),
	// drop every baseline before applying. This is the only way a
	// handoff-initiated full snapshot can land correctly: the incoming
	// Full entries carry the authoritative per-entity state and must
	// replace, not merge with, whatever baselines the previous cell's
	// decoder had accumulated.
	b.WriteString("    const freshSnapshot = (header.flags & FRAME_FLAG_FRESH_SNAPSHOT) !== 0;\n")
	b.WriteString("    if (freshSnapshot) {\n")
	b.WriteString("      this.baselines.clear();\n")
	b.WriteString("    }\n\n")

	b.WriteString("    const entered: AnyEntity[] = [];\n")
	b.WriteString("    const updated: AnyEntity[] = [];\n\n")

	// Full entries.
	//
	// Full frames come in two flavors: the first-visibility snapshot (which
	// carries InitialData for one-shot fields like pilot name), and periodic
	// full-state keyframes (which carry no initial data). Both go through this
	// loop. To keep initial-only fields alive across keyframes, look up the
	// previous baseline and pass its cached lastEntity as `existing` — the
	// per-entity decoders fall back to `existing?.field` when the initial
	// blob is missing. First-visibility decodes have no baseline yet and so
	// pass `undefined`, which is fine because initial data IS present.
	b.WriteString("    for (let i = 0; i < header.fullCount; i++) {\n")
	b.WriteString("      const { entry, offset: next } = decodeFullEntry(data, pos);\n")
	b.WriteString("      pos = next;\n")
	b.WriteString("      const prevBl = this.baselines.get(entry.netID);\n")
	b.WriteString("      const entity = this.decodeEntity(entry.entityType, entry.snapshot, entry.initialData, entry.netID, entry.producedAtMs, prevBl?.meta?.lastEntity);\n")
	b.WriteString("      this.baselines.set(entry.netID, entry.snapshot, { type: entry.entityType, lastEntity: entity ?? undefined });\n")
	b.WriteString("      if (entity) entered.push(entity);\n")
	b.WriteString("    }\n\n")

	// Delta entries.
	b.WriteString("    for (let i = 0; i < header.deltaCount; i++) {\n")
	b.WriteString("      const { entry, offset: next } = decodeDeltaEntry(data, pos);\n")
	b.WriteString("      pos = next;\n")
	b.WriteString("      const bl = this.baselines.get(entry.netID);\n")
	b.WriteString("      if (!bl) continue;\n")
	b.WriteString("      const fieldSizes = this.fieldSizesFor(entry.entityType);\n")
	b.WriteString("      const hasVarTail = this.hasVarTailFor(entry.entityType);\n")
	b.WriteString("      const newSnap = applyDelta(fieldSizes, hasVarTail, bl.snapshot, entry.deltaData);\n")
	b.WriteString("      const entity = this.decodeEntity(entry.entityType, newSnap, null, entry.netID, entry.producedAtMs, bl.meta?.lastEntity);\n")
	b.WriteString("      this.baselines.set(entry.netID, newSnap, { type: bl.meta?.type ?? entry.entityType, lastEntity: entity ?? undefined });\n")
	b.WriteString("      if (entity) updated.push(entity);\n")
	b.WriteString("    }\n\n")

	// Removed and exited.
	b.WriteString("    const { ids: removed, offset: pos2 } = decodeRemovedIDs(data, pos, header.removedCount);\n")
	b.WriteString("    const { ids: exited } = decodeRemovedIDs(data, pos2, header.exitedCount);\n\n")

	// Clean up baselines.
	b.WriteString("    for (const id of removed) this.baselines.delete(id);\n")
	b.WriteString("    for (const id of exited) this.baselines.delete(id);\n\n")

	b.WriteString("    return {\n")
	b.WriteString("      tick: header.tick, seq: header.seq, freshSnapshot,\n")
	b.WriteString("      entered, updated, removed, exited,\n")
	b.WriteString("    };\n")
	b.WriteString("  }\n\n")

	// decodeEntity dispatcher.
	//
	// `existing` is the previously-decoded entity for this netID (if any),
	// threaded through from baseline meta so per-entity decoders can restore
	// initial-only fields (e.g. strings carried only in full-snapshot initial
	// data). Each case narrows the type before passing it through.
	b.WriteString("  private decodeEntity(type_: number, snap: Uint8Array, initial: Uint8Array | null, netID: number, producedAtMs: number, existing?: AnyEntity): AnyEntity | null {\n")
	b.WriteString("    switch (type_) {\n")
	for _, ent := range g.schema.Entities {
		name := g.entityName(ent)
		fmt.Fprintf(&b,
			"      case %d: { const prev = existing && existing.entityType === %d ? existing : undefined; const e = decode%sSnapshot(snap, initial, prev); e.netID = netID; e.producedAtMs = producedAtMs; return e; }\n",
			ent.Kind, ent.Kind, name)
	}
	b.WriteString("      default: return null;\n")
	b.WriteString("    }\n")
	b.WriteString("  }\n\n")

	// fieldSizesFor dispatcher.
	b.WriteString("  private fieldSizesFor(type_: number): number[] {\n")
	b.WriteString("    switch (type_) {\n")
	for _, ent := range g.schema.Entities {
		upperName := strings.ToUpper(g.entityName(ent))
		fmt.Fprintf(&b, "      case %d: return %s_FIELD_SIZES;\n", ent.Kind, upperName)
	}
	b.WriteString("      default: return [];\n")
	b.WriteString("    }\n")
	b.WriteString("  }\n\n")

	// hasVarTailFor dispatcher.
	b.WriteString("  private hasVarTailFor(type_: number): boolean {\n")
	b.WriteString("    switch (type_) {\n")
	for _, ent := range g.schema.Entities {
		upperName := strings.ToUpper(g.entityName(ent))
		fmt.Fprintf(&b, "      case %d: return %s_HAS_VAR_TAIL;\n", ent.Kind, upperName)
	}
	b.WriteString("      default: return false;\n")
	b.WriteString("    }\n")
	b.WriteString("  }\n")

	b.WriteString("}\n")

	return b.String()
}

// writeVarTailDecoder emits TypeScript that parses the snapshot's var-tail
// into a typed item array on the decoded entity. Called once per decode
// function after all scalar fields have been consumed.
//
// Panics at codegen time if ItemFields is empty — the generated while loop
// would be an infinite loop because no field decoder would advance `o`.
func writeVarTailDecoder(b *strings.Builder, ent EntitySchema, itemType string) {
	vt := ent.VarTail
	if len(vt.ItemFields) == 0 {
		panic(fmt.Sprintf("sdkgen: entity kind %d var-tail %q has no ItemFields; decoder would be an infinite loop", ent.Kind, vt.Name))
	}
	fmt.Fprintf(b, "  const %sByteLen = readUint16(snap, o); o += 2;\n", vt.Name)
	fmt.Fprintf(b, "  const %sEnd = o + %sByteLen;\n", vt.Name, vt.Name)
	fmt.Fprintf(b, "  const %s: %s[] = [];\n", vt.Name, itemType)
	fmt.Fprintf(b, "  while (o < %sEnd) {\n", vt.Name)
	for _, f := range vt.ItemFields {
		writeFieldDecoderIndented(b, f, "    ")
	}
	fmt.Fprintf(b, "    %s.push({ %s });\n", vt.Name, joinItemFieldNames(vt.ItemFields))
	b.WriteString("  }\n")
}

// writeFieldDecoderIndented is writeFieldDecoder with configurable indent, so
// it can be nested inside the while loop for var-tail items.
//
// Panics on unsupported encodings so a new var-tail field type can't silently
// emit missing decoder lines. String is not supported in var-tail items because
// the client-side while-loop needs a fixed stride per iteration; length-prefixed
// strings belong in the fixed-layout portion of the snapshot.
func writeFieldDecoderIndented(b *strings.Builder, field BindingSchemaField, indent string) {
	switch field.Encoding {
	case "f32":
		fmt.Fprintf(b, "%sconst %s = readFloat32(snap, o); o += 4;\n", indent, field.Name)
	case "qvel":
		fmt.Fprintf(b, "%sconst %s = unVel(readInt16(snap, o), %g); o += 2;\n", indent, field.Name, field.Scale)
	case "qangle":
		fmt.Fprintf(b, "%sconst %s = unAngle(readUint16(snap, o)); o += 2;\n", indent, field.Name)
	case "qnorm":
		fmt.Fprintf(b, "%sconst %s = unNorm(snap[o]); o += 1;\n", indent, field.Name)
	case "u8":
		fmt.Fprintf(b, "%sconst %s = snap[o]; o += 1;\n", indent, field.Name)
	case "u16":
		fmt.Fprintf(b, "%sconst %s = readUint16(snap, o); o += 2;\n", indent, field.Name)
	case "u32":
		fmt.Fprintf(b, "%sconst %s = readUint32(snap, o); o += 4;\n", indent, field.Name)
	case "i16":
		fmt.Fprintf(b, "%sconst %s = readInt16(snap, o); o += 2;\n", indent, field.Name)
	case "bool":
		fmt.Fprintf(b, "%sconst %s = !!snap[o]; o += 1;\n", indent, field.Name)
	default:
		panic(fmt.Sprintf("sdkgen: unsupported var-tail field encoding %q for field %q", field.Encoding, field.Name))
	}
}

func joinItemFieldNames(fields []BindingSchemaField) string {
	names := make([]string, len(fields))
	for i, f := range fields {
		names[i] = f.Name
	}
	return strings.Join(names, ", ")
}

// writeFieldDecoder emits a TypeScript line that consumes one scalar field
// from the fixed-layout portion of an entity snapshot. Strings are handled
// separately by writeInitialFieldDecoder (they live in the initial payload),
// so string encodings must not appear here.
func writeFieldDecoder(b *strings.Builder, field BindingSchemaField) {
	switch field.Encoding {
	case "f32":
		fmt.Fprintf(b, "  const %s = readFloat32(snap, o); o += 4;\n", field.Name)
	case "qvel":
		fmt.Fprintf(b, "  const %s = unVel(readInt16(snap, o), %g); o += 2;\n", field.Name, field.Scale)
	case "qangle":
		fmt.Fprintf(b, "  const %s = unAngle(readUint16(snap, o)); o += 2;\n", field.Name)
	case "qnorm":
		fmt.Fprintf(b, "  const %s = unNorm(snap[o]); o += 1;\n", field.Name)
	case "u8":
		fmt.Fprintf(b, "  const %s = snap[o]; o += 1;\n", field.Name)
	case "u16":
		fmt.Fprintf(b, "  const %s = readUint16(snap, o); o += 2;\n", field.Name)
	case "u32":
		fmt.Fprintf(b, "  const %s = readUint32(snap, o); o += 4;\n", field.Name)
	case "i16":
		fmt.Fprintf(b, "  const %s = readInt16(snap, o); o += 2;\n", field.Name)
	case "bool":
		fmt.Fprintf(b, "  const %s = !!snap[o]; o += 1;\n", field.Name)
	default:
		panic(fmt.Sprintf("sdkgen: unsupported snapshot field encoding %q for field %q", field.Encoding, field.Name))
	}
}

func writeInitialFieldDecoder(b *strings.Builder, field BindingSchemaField, _ string) {
	switch field.Encoding {
	case "string":
		fmt.Fprintf(b, "  const %s = initial ? decodeLengthPrefixedStringU8(initial) : (existing?.%s ?? \"\");\n", field.Name, field.Name)
	case "u8":
		fmt.Fprintf(b, "  const %s = initial ? initial[0] : (existing?.%s ?? 0);\n", field.Name, field.Name)
	default:
		fmt.Fprintf(b, "  const %s = existing?.%s ?? 0;\n", field.Name, field.Name)
	}
}

func joinInts(ints []int) string {
	parts := make([]string, len(ints))
	for i, v := range ints {
		parts[i] = fmt.Sprintf("%d", v)
	}
	return strings.Join(parts, ", ")
}

// ---------------------------------------------------------------------------
// client.ts
// ---------------------------------------------------------------------------

func (g *Generator) genClient() string {
	var b strings.Builder
	gameName := titleCase(g.schema.Game)

	b.WriteString("// GENERATED by sdkgen — do not edit.\n\n")
	b.WriteString("import { create, toBinary, fromBinary } from \"@bufbuild/protobuf\";\n")

	// Collect unique proto imports (sorted paths + symbols for deterministic output).
	imports := g.collectProtoImports()
	paths := make([]string, 0, len(imports))
	for path := range imports {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	for _, path := range paths {
		symbols := imports[path]
		sort.Strings(symbols)
		fmt.Fprintf(&b, "import { %s } from \"%s\";\n", strings.Join(symbols, ", "), path)
	}

	// Import type-only for server event + operation response messages.
	typeImports := g.collectTypeImports()
	typePaths := make([]string, 0, len(typeImports))
	for path := range typeImports {
		typePaths = append(typePaths, path)
	}
	sort.Strings(typePaths)
	for _, path := range typePaths {
		symbols := typeImports[path]
		sort.Strings(symbols)
		fmt.Fprintf(&b, "import type { %s } from \"%s\";\n", strings.Join(symbols, ", "), path)
	}

	b.WriteString("import { Transport } from \"./transport.js\";\n")
	fmt.Fprintf(&b, "import { %sDeltaDecoder } from \"./delta-decoder.js\";\n", gameName)
	b.WriteString("import type { DeltaWorldUpdate } from \"./entities.js\";\n")
	hasTypedEvents := len(g.schema.BroadcastTypes) > 0 || len(g.schema.ServerEventTypes) > 0
	if hasTypedEvents {
		// TypedDispatcher routes both HandleAll[T] broadcasts and
		// RegisterEvent[T] typed server events. Per-typed-server-event
		// classes are imported eagerly so the on<EventName>(handler)
		// wrappers below can pass them to typedEvents.on.
		var imports []string
		imports = append(imports, "TypedDispatcher")
		for _, name := range serverEventClassNames(g.schema.ServerEventTypes) {
			imports = append(imports, name)
		}
		fmt.Fprintf(&b, "import { %s } from \"./broadcasts.js\";\n", strings.Join(imports, ", "))
	}

	// Import envelope schemas from engine proto.
	if len(g.schema.Operations) > 0 {
		b.WriteString("import { ClientEventSchema, ServerEventSchema, type ServerEvent, OperationRequestSchema, OperationResponseSchema, type OperationResponse } from \"@gen/enginepb/engine_pb.js\";\n")
	} else {
		b.WriteString("import { ClientEventSchema, ServerEventSchema, type ServerEvent } from \"@gen/enginepb/engine_pb.js\";\n")
	}

	b.WriteString("\n")

	// Options interface.
	fmt.Fprintf(&b, "export interface %sClientOptions {\n", gameName)
	b.WriteString("  url: string;\n")
	b.WriteString("  onOpen?: () => void;\n")
	b.WriteString("  onClose?: (ev: CloseEvent) => void;\n")
	b.WriteString("  onError?: (ev: Event) => void;\n")
	b.WriteString("}\n\n")

	// Client class.
	fmt.Fprintf(&b, "export class %sClient {\n", gameName)
	b.WriteString("  private transport: Transport;\n")
	fmt.Fprintf(&b, "  private decoder = new %sDeltaDecoder();\n", gameName)
	b.WriteString("  private eventHandlers = new Map<number, ((data: Uint8Array) => void)[]>();\n")
	b.WriteString("  private rawEventHandlers: ((code: number, data: Uint8Array) => void)[] = [];\n")
	if hasTypedEvents {
		b.WriteString("  /** Typed broadcast dispatcher — register handlers for AoI-filtered\n")
		b.WriteString("   *  events emitted by the server's HandleAll[T] machinery. */\n")
		b.WriteString("  readonly typedEvents = new TypedDispatcher();\n")
	}
	if len(g.schema.Operations) > 0 {
		b.WriteString("  private pendingOps = new Map<number, { resolve: (data: Uint8Array) => void; reject: (err: Error) => void }>();\n")
		b.WriteString("  private pushHandlers = new Map<number, ((data: Uint8Array) => void)[]>();\n")
		b.WriteString("  private nextRequestID = 1;\n")
	}
	b.WriteString("\n")

	fmt.Fprintf(&b, "  constructor(private options: %sClientOptions) {\n", gameName)
	b.WriteString("    this.transport = new Transport(options.url);\n")
	b.WriteString("  }\n\n")

	// connect / disconnect / connected
	b.WriteString("  connect(): void {\n")
	b.WriteString("    this.transport.connect();\n")
	b.WriteString("    const ws = this.transport.socket!;\n")
	b.WriteString("    if (this.options.onOpen) ws.onopen = this.options.onOpen;\n")
	b.WriteString("    if (this.options.onClose) ws.onclose = this.options.onClose;\n")
	b.WriteString("    if (this.options.onError) ws.onerror = this.options.onError;\n")
	b.WriteString("    this.transport.onEvent((payload) => this.handleEvent(payload));\n")
	if len(g.schema.Operations) > 0 {
		b.WriteString("    this.transport.onOperation((payload) => this.handleOperation(payload));\n")
	}
	b.WriteString("  }\n\n")

	if len(g.schema.Operations) > 0 {
		b.WriteString("  disconnect(): void {\n")
		b.WriteString("    // Reject any pending operations.\n")
		b.WriteString("    for (const pending of this.pendingOps.values()) {\n")
		b.WriteString("      pending.reject(new Error(\"client disconnected\"));\n")
		b.WriteString("    }\n")
		b.WriteString("    this.pendingOps.clear();\n")
		b.WriteString("    this.transport.close();\n")
		b.WriteString("  }\n")
	} else {
		b.WriteString("  disconnect(): void { this.transport.close(); }\n")
	}
	b.WriteString("  get connected(): boolean { return this.transport.connected; }\n\n")

	b.WriteString("  /** Raw transport handle for advanced use (operations channel,\n")
	b.WriteString("   *  custom protocol extensions). Most app code should use the typed\n")
	b.WriteString("   *  send* / on* methods on this class instead. */\n")
	b.WriteString("  get rawTransport(): Transport { return this.transport; }\n\n")

	// Event dispatch.
	//
	// Channel 0x00 carries two coexisting wire formats during the
	// events-channel-redesign migration:
	//
	//   1. Legacy ServerEvent envelope: protobuf wire format. The first
	//      byte is the field-1 varint tag for the `code` field (0x08).
	//      Decoded as before via ServerEventSchema.
	//
	//   2. New typed-event frame: repeated [typeID:u32 LE][body_len:u32 LE][body]
	//      until end of message. Each entry dispatches to typedEvents.
	//
	// Disambiguation: the first byte of the payload. ServerEvent always
	// starts with 0x08 (the field-1 varint tag for `code`); a typed-event
	// frame's first byte is the low byte of an FNV-1a typeID hash, which
	// has a 1/256 chance of being 0x08. Collisions panic at registration
	// time on the server (mmokit.RegisterEvent[T]) — if the legacy decode
	// throws here, we log a defensive warning hinting at the collision.
	//
	// Phase 2.4 retires WorldUpdateMsg.events; Phase 7 retires the legacy
	// ServerEvent envelope entirely. Until then, both paths coexist.
	b.WriteString("  private handleEvent(payload: Uint8Array): void {\n")
	b.WriteString("    if (payload.length === 0) return;\n")
	if hasTypedEvents {
		b.WriteString("    if (payload[0] !== 0x08) {\n")
		b.WriteString("      // Typed-event frame: repeated [typeID:u32 LE][body_len:u32 LE][body].\n")
		b.WriteString("      let off = 0;\n")
		b.WriteString("      while (off + 8 <= payload.length) {\n")
		b.WriteString("        const view = new DataView(payload.buffer, payload.byteOffset + off, 8);\n")
		b.WriteString("        const typeID = view.getUint32(0, true);\n")
		b.WriteString("        const bodyLen = view.getUint32(4, true);\n")
		b.WriteString("        off += 8;\n")
		b.WriteString("        if (off + bodyLen > payload.length) {\n")
		b.WriteString("          console.warn(`typed-event frame: truncated body for typeID=0x${typeID.toString(16)}`);\n")
		b.WriteString("          return;\n")
		b.WriteString("        }\n")
		b.WriteString("        const body = payload.subarray(off, off + bodyLen);\n")
		b.WriteString("        off += bodyLen;\n")
		b.WriteString("        this.typedEvents.dispatch(typeID, body);\n")
		b.WriteString("      }\n")
		b.WriteString("      return;\n")
		b.WriteString("    }\n")
	}
	b.WriteString("    let evt: ServerEvent;\n")
	b.WriteString("    try {\n")
	b.WriteString("      evt = fromBinary(ServerEventSchema, payload) as ServerEvent;\n")
	b.WriteString("    } catch (err) {\n")
	b.WriteString("      console.warn(`legacy ServerEvent decode failed (first byte 0x${payload[0].toString(16)}); this might be a typed-event frame whose typeID's low byte is 0x08 — rename the offending Go type. err=${err}`);\n")
	b.WriteString("      return;\n")
	b.WriteString("    }\n")
	b.WriteString("    const handlers = this.eventHandlers.get(evt.code);\n")
	b.WriteString("    if (handlers) {\n")
	b.WriteString("      for (const h of handlers) h(evt.data);\n")
	b.WriteString("    }\n")
	b.WriteString("    for (const h of this.rawEventHandlers) h(evt.code, evt.data);\n")
	b.WriteString("  }\n\n")

	b.WriteString("  private on(code: number, handler: (data: Uint8Array) => void): () => void {\n")
	b.WriteString("    let arr = this.eventHandlers.get(code);\n")
	b.WriteString("    if (!arr) { arr = []; this.eventHandlers.set(code, arr); }\n")
	b.WriteString("    arr.push(handler);\n")
	b.WriteString("    return () => { const idx = arr!.indexOf(handler); if (idx >= 0) arr!.splice(idx, 1); };\n")
	b.WriteString("  }\n\n")

	// Send helper.
	b.WriteString("  private sendEvent(code: number, data: Uint8Array): void {\n")
	b.WriteString("    const evt = create(ClientEventSchema, { code, data });\n")
	b.WriteString("    this.transport.sendEvent(toBinary(ClientEventSchema, evt));\n")
	b.WriteString("  }\n\n")

	// --- Typed client-input send ---
	//
	// Wire path: TS class instance → encode() body bytes → transport
	// sendClientInput frames as [0x02][u32 typeID][u32 bodyLen][body].
	// Server-side ReflectUnmarshalOnStage decodes the body back into
	// the registered Go type and dispatches via mmokit.HandleClient.
	//
	// The TS-side type bound matches every class generated in inputs.ts:
	// each has `static readonly typeID: number` and an `encode(): Uint8Array`
	// instance method. This signature works whether or not inputs.ts was
	// emitted (the server's HandleClient registry may be empty).
	b.WriteString("  /** Send a typed client-input message (mmokit.HandleClient).\n")
	b.WriteString("   *\n")
	b.WriteString("   *  msg must be an instance of a class generated into inputs.ts —\n")
	b.WriteString("   *  exposing static typeID and instance encode(): Uint8Array. The\n")
	b.WriteString("   *  resulting wire frame is dispatched server-side to the matching\n")
	b.WriteString("   *  HandleClient[T] handler. */\n")
	b.WriteString("  send(msg: { encode(): Uint8Array }): void {\n")
	b.WriteString("    const ctor = msg.constructor as unknown as { typeID: number };\n")
	b.WriteString("    this.transport.sendClientInput(ctor.typeID, msg.encode());\n")
	b.WriteString("  }\n\n")

	// --- Client → Server send methods ---
	for _, ce := range g.schema.ClientEvents {
		msg := g.resolveMsg(ce.ProtoName)
		if msg == nil {
			continue
		}
		methodName := "send" + titleCase(protoToMethodName(msg.TypeName, g.schema.Game))
		fmt.Fprintf(&b, "  /** Send %s (code %d). */\n", msg.TypeName, ce.Code)
		fmt.Fprintf(&b, "  %s(params: { %s }): void {\n", methodName, fieldParamList(msg.Fields))
		fmt.Fprintf(&b, "    const data = toBinary(%s, create(%s, params));\n", msg.SchemaName, msg.SchemaName)
		fmt.Fprintf(&b, "    this.sendEvent(%d, data);\n", ce.Code)
		b.WriteString("  }\n\n")
	}

	// Pre-compute the set of typed-event method names. During Phase 3 of the
	// events-channel-redesign migration, a single logical event (e.g.
	// PlayerDied) may be registered both via the legacy proto-envelope path
	// (gamepb.PlayerDiedMsg → onPlayerDied) AND via the typed path
	// (game.PlayerDied → onPlayerDied). Without dedupe we'd emit two TS
	// methods with the same name → TS error. Skip the legacy emit when a
	// typed equivalent exists; the typed path is the new canonical surface.
	typedMethodNames := map[string]struct{}{}
	for _, st := range g.schema.ServerEventTypes {
		typedMethodNames[serverEventMethodName(broadcastClassName(st.Name))] = struct{}{}
	}

	// --- Server → Client receive methods ---
	for _, se := range g.schema.ServerEvents {
		if se.ProtoName == "" {
			// Binary event (e.g. deltaWorldUpdate).
			methodName := "on" + titleCase(se.Name)
			fmt.Fprintf(&b, "  /** Subscribe to %s (code %d, binary). */\n", se.Name, se.Code)
			fmt.Fprintf(&b, "  %s(handler: (update: DeltaWorldUpdate) => void): () => void {\n", methodName)
			fmt.Fprintf(&b, "    return this.on(%d, (data) => handler(this.decoder.decode(data)));\n", se.Code)
			b.WriteString("  }\n\n")
		} else {
			msg := g.resolveMsg(se.ProtoName)
			if msg == nil {
				continue
			}
			methodName := "on" + titleCase(se.Name)
			if _, dup := typedMethodNames[methodName]; dup {
				// A typed RegisterEvent[T] for the same logical event already
				// emits this method — the typed path is the canonical surface.
				// Skip the legacy proto-envelope emit to avoid a TS duplicate
				// method declaration.
				continue
			}
			fmt.Fprintf(&b, "  /** Subscribe to %s (code %d). */\n", se.Name, se.Code)
			fmt.Fprintf(&b, "  %s(handler: (msg: %s) => void): () => void {\n", methodName, msg.TypeName)
			fmt.Fprintf(&b, "    return this.on(%d, (data) => handler(fromBinary(%s, data)));\n", se.Code, msg.SchemaName)
			b.WriteString("  }\n\n")
		}
	}

	// --- Typed server-event handlers (mmokit.RegisterEvent[T]) ---
	//
	// Each typed registration produces a `client.on<EventName>(handler)`
	// method that subscribes against the TypedDispatcher under the hood.
	// The dispatcher dispatches by typeID — set on the wire by the server's
	// afterSend path and matched against the class's static typeID.
	//
	// Naming convention: Go `pkg.PlayerSpawned` → TS class `PlayerSpawned`
	// (last dot segment) → method `onPlayerSpawned`.
	for _, st := range g.schema.ServerEventTypes {
		writeServerEventHandler(&b, st)
	}

	// --- Operations (request/response on channel 0x01) ---
	if len(g.schema.Operations) > 0 {
		// handleOperation dispatches responses to pending op requests (by requestId)
		// or to push handlers (when requestId == 0 — unsolicited server push).
		b.WriteString("  private handleOperation(payload: Uint8Array): void {\n")
		b.WriteString("    const resp = fromBinary(OperationResponseSchema, payload) as OperationResponse;\n")
		b.WriteString("    if (resp.requestId !== 0) {\n")
		b.WriteString("      const pending = this.pendingOps.get(resp.requestId);\n")
		b.WriteString("      if (pending) {\n")
		b.WriteString("        this.pendingOps.delete(resp.requestId);\n")
		b.WriteString("        if (resp.returnCode !== 0) {\n")
		b.WriteString("          pending.reject(new Error(resp.errorMsg || `op error code ${resp.returnCode}`));\n")
		b.WriteString("        } else {\n")
		b.WriteString("          pending.resolve(resp.data);\n")
		b.WriteString("        }\n")
		b.WriteString("      }\n")
		b.WriteString("      return;\n")
		b.WriteString("    }\n")
		b.WriteString("    const handlers = this.pushHandlers.get(resp.code);\n")
		b.WriteString("    if (handlers) for (const h of handlers) h(resp.data);\n")
		b.WriteString("  }\n\n")

		b.WriteString("  private onPush(code: number, handler: (data: Uint8Array) => void): () => void {\n")
		b.WriteString("    let arr = this.pushHandlers.get(code);\n")
		b.WriteString("    if (!arr) { arr = []; this.pushHandlers.set(code, arr); }\n")
		b.WriteString("    arr.push(handler);\n")
		b.WriteString("    return () => { const idx = arr!.indexOf(handler); if (idx >= 0) arr!.splice(idx, 1); };\n")
		b.WriteString("  }\n\n")

		// Generic op-channel send for opcodes whose proto types aren't in the
		// schema (e.g. service-kind ops like auth, which sdkgen doesn't yet
		// pick up). Callers marshal request/response themselves and hand raw
		// bytes through. Mirrors the typed-send machinery — assigns a fresh
		// requestId, registers a pendingOps slot, and resolves with the raw
		// response bytes (or rejects on returnCode != 0).
		b.WriteString("  /** Send a raw op (code, data) and await raw response bytes. For ops not in the typed schema. */\n")
		b.WriteString("  sendOp(code: number, data: Uint8Array): Promise<Uint8Array> {\n")
		b.WriteString("    const requestId = this.nextRequestID++;\n")
		b.WriteString("    const req = create(OperationRequestSchema, { code, requestId, data });\n")
		b.WriteString("    this.transport.sendOperation(toBinary(OperationRequestSchema, req));\n")
		b.WriteString("    return new Promise((resolve, reject) => {\n")
		b.WriteString("      this.pendingOps.set(requestId, { resolve, reject });\n")
		b.WriteString("    });\n")
		b.WriteString("  }\n\n")

		// Typed send method per operation.
		for _, op := range g.schema.Operations {
			reqMsg := g.resolveMsg(op.RequestProto)
			respMsg := g.resolveMsg(op.ResponseProto)
			if reqMsg == nil || respMsg == nil {
				continue
			}
			methodName := "send" + titleCase(op.Name)
			fmt.Fprintf(&b, "  /** Send %s request (op code %d), await typed %s. */\n", op.Name, op.Code, respMsg.TypeName)
			fmt.Fprintf(&b, "  %s(params: { %s }): Promise<%s> {\n", methodName, fieldParamList(reqMsg.Fields), respMsg.TypeName)
			fmt.Fprintf(&b, "    const data = toBinary(%s, create(%s, params));\n", reqMsg.SchemaName, reqMsg.SchemaName)
			b.WriteString("    const requestId = this.nextRequestID++;\n")
			fmt.Fprintf(&b, "    const req = create(OperationRequestSchema, { code: %d, requestId, data });\n", op.Code)
			b.WriteString("    this.transport.sendOperation(toBinary(OperationRequestSchema, req));\n")
			b.WriteString("    return new Promise((resolve, reject) => {\n")
			b.WriteString("      this.pendingOps.set(requestId, {\n")
			fmt.Fprintf(&b, "        resolve: (d) => resolve(fromBinary(%s, d) as %s),\n", respMsg.SchemaName, respMsg.TypeName)
			b.WriteString("        reject,\n")
			b.WriteString("      });\n")
			b.WriteString("    });\n")
			b.WriteString("  }\n\n")

			// Push subscriber: fires when server sends an unsolicited response for this op code.
			pushMethodName := "on" + titleCase(op.Name) + "Push"
			fmt.Fprintf(&b, "  /** Subscribe to unsolicited %s pushes (op code %d, requestId=0). */\n", op.Name, op.Code)
			fmt.Fprintf(&b, "  %s(handler: (msg: %s) => void): () => void {\n", pushMethodName, respMsg.TypeName)
			fmt.Fprintf(&b, "    return this.onPush(%d, (data) => handler(fromBinary(%s, data) as %s));\n", op.Code, respMsg.SchemaName, respMsg.TypeName)
			b.WriteString("  }\n\n")
		}
	}

	// Raw event handler.
	b.WriteString("  /** Catch-all for unhandled server events. */\n")
	b.WriteString("  onRawEvent(handler: (code: number, data: Uint8Array) => void): () => void {\n")
	b.WriteString("    this.rawEventHandlers.push(handler);\n")
	b.WriteString("    return () => {\n")
	b.WriteString("      const idx = this.rawEventHandlers.indexOf(handler);\n")
	b.WriteString("      if (idx >= 0) this.rawEventHandlers.splice(idx, 1);\n")
	b.WriteString("    };\n")
	b.WriteString("  }\n\n")

	// Baseline clear.
	b.WriteString("  /** Clear delta baselines (call on cell change / reconnect). */\n")
	b.WriteString("  clearBaselines(): void { this.decoder.clear(); }\n")

	b.WriteString("}\n")

	return b.String()
}

// typedShadowedServerEvents returns the set of legacy proto-based server-event
// codes whose method emit is suppressed because a typed RegisterEvent[T]
// equivalent owns the canonical method name. Used by import collectors so we
// don't emit dead `import { FooMsg, FooMsgSchema } from "@gen/..."` lines.
func (g *Generator) typedShadowedServerEvents() map[uint32]struct{} {
	typedNames := map[string]struct{}{}
	for _, st := range g.schema.ServerEventTypes {
		typedNames[serverEventMethodName(broadcastClassName(st.Name))] = struct{}{}
	}
	out := map[uint32]struct{}{}
	for _, se := range g.schema.ServerEvents {
		if se.ProtoName == "" {
			continue
		}
		if _, dup := typedNames["on"+titleCase(se.Name)]; dup {
			out[se.Code] = struct{}{}
		}
	}
	return out
}

// collectProtoImports collects Schema imports (for encoding/decoding) grouped by import path.
func (g *Generator) collectProtoImports() map[string][]string {
	imports := make(map[string][]string)
	seen := make(map[string]bool)
	addSchema := func(fullName string) {
		msg := g.resolveMsg(fullName)
		if msg == nil || seen[msg.SchemaName] {
			return
		}
		seen[msg.SchemaName] = true
		path := protoImportPath(msg)
		imports[path] = append(imports[path], msg.SchemaName)
	}
	for _, ce := range g.schema.ClientEvents {
		addSchema(ce.ProtoName)
	}
	shadowed := g.typedShadowedServerEvents()
	for _, se := range g.schema.ServerEvents {
		if se.ProtoName == "" {
			continue
		}
		if _, dup := shadowed[se.Code]; dup {
			continue
		}
		addSchema(se.ProtoName)
	}
	for _, op := range g.schema.Operations {
		addSchema(op.RequestProto)
		addSchema(op.ResponseProto)
	}
	return imports
}

// collectTypeImports collects type-only imports for server event + operation response types.
func (g *Generator) collectTypeImports() map[string][]string {
	imports := make(map[string][]string)
	seen := make(map[string]bool)
	addType := func(fullName string) {
		msg := g.resolveMsg(fullName)
		if msg == nil || seen[msg.TypeName] {
			return
		}
		seen[msg.TypeName] = true
		path := protoImportPath(msg)
		imports[path] = append(imports[path], msg.TypeName)
	}
	shadowed := g.typedShadowedServerEvents()
	for _, se := range g.schema.ServerEvents {
		if se.ProtoName == "" {
			continue
		}
		if _, dup := shadowed[se.Code]; dup {
			continue
		}
		addType(se.ProtoName)
	}
	for _, op := range g.schema.Operations {
		addType(op.ResponseProto)
	}
	return imports
}

// protoToMethodName strips game-prefix from proto message names for cleaner methods.
// "BasicMoveTargetMsg" with game="basic" → "MoveTarget"
func protoToMethodName(typeName string, game string) string {
	name := typeName
	prefix := titleCase(game)
	name = strings.TrimPrefix(name, prefix)
	name = strings.TrimSuffix(name, "Msg")
	if name == "" {
		return typeName
	}
	return name
}

func fieldParamList(fields []ProtoField) string {
	parts := make([]string, len(fields))
	for i, f := range fields {
		parts[i] = fmt.Sprintf("%s: %s", f.Name, f.Type)
	}
	return strings.Join(parts, "; ")
}

// ---------------------------------------------------------------------------
// index.ts
// ---------------------------------------------------------------------------

func (g *Generator) genIndex() string {
	gameName := titleCase(g.schema.Game)
	var b strings.Builder
	b.WriteString("// GENERATED by sdkgen — do not edit.\n\n")
	fmt.Fprintf(&b, "export { %sClient } from \"./client.js\";\n", gameName)
	fmt.Fprintf(&b, "export type { %sClientOptions } from \"./client.js\";\n", gameName)
	b.WriteString("export type { AnyEntity, DeltaWorldUpdate } from \"./entities.js\";\n")
	b.WriteString("export * from \"./entities.js\";\n")
	fmt.Fprintf(&b, "export { %sDeltaDecoder } from \"./delta-decoder.js\";\n", gameName)
	b.WriteString("export { Transport } from \"./transport.js\";\n")
	if len(g.schema.BroadcastTypes) > 0 || len(g.schema.ServerEventTypes) > 0 {
		// Re-export every generated broadcast / typed-server-event class
		// plus the dispatcher so app code imports them via the SDK's public
		// surface, not directly from the internal broadcasts.ts file.
		var names []string
		names = append(names, "TypedDispatcher")
		for _, bt := range g.schema.BroadcastTypes {
			names = append(names, broadcastClassName(bt.Name))
		}
		for _, st := range g.schema.ServerEventTypes {
			names = append(names, broadcastClassName(st.Name))
		}
		sort.Strings(names)
		fmt.Fprintf(&b, "export { %s } from \"./broadcasts.js\";\n", strings.Join(names, ", "))
	}
	if len(g.schema.ClientInputTypes) > 0 {
		// Re-export every generated client-input class so app code imports
		// them via the SDK's public surface (e.g. `import { SetMoveTarget }
		// from "@sdk"`) rather than reaching into the internal inputs.ts
		// file directly.
		var names []string
		for _, ct := range g.schema.ClientInputTypes {
			names = append(names, broadcastClassName(ct.Name))
		}
		sort.Strings(names)
		fmt.Fprintf(&b, "export { %s } from \"./inputs.js\";\n", strings.Join(names, ", "))
	}

	// Re-export proto types that appear in the SDK's public method
	// signatures — consumers should not have to reach into @gen/... for
	// types the SDK already uses on its own surface.
	typeImports := g.collectTypeImports()
	paths := make([]string, 0, len(typeImports))
	for p := range typeImports {
		paths = append(paths, p)
	}
	sort.Strings(paths)
	for _, path := range paths {
		names := append([]string(nil), typeImports[path]...)
		sort.Strings(names)
		fmt.Fprintf(&b, "export type { %s } from %q;\n", strings.Join(names, ", "), path)
	}

	return b.String()
}
