package main

import (
	"fmt"
	"strings"
)

// genInputs emits the TypeScript file containing one class per
// HandleClient-eligible Go type. Each class exposes:
//
//   - static readonly typeID (uint32, matches mmokit.TypeIDOf on the server)
//   - per-field public properties initialized to a zero value
//   - encode(): Uint8Array — produces bytes that the server-side
//     ReflectUnmarshalOnStage call site decodes back into the Go struct
//
// The wire layout mirrors the reflect_marshal codec defined in
// pkg/universe/reflect_marshal.go: fields encoded in source declaration
// order, no padding, little-endian. mmokit.Entity encodes as a 4-byte
// NetID via the registered reflect codec.
//
// The full client→server frame layout is:
//
//	[byte 0x00][u32 typeID][u32 bodyLen][body bytes]
//
// The TS class only encodes the body; SpaceClient.send wraps it with
// the channel byte + header. Plan 1 Phase 5 unified the typed-input
// channel with the event channel; both inbound paths share 0x00 and
// disambiguate by typeID at the server-side dispatcher.
//
// Output schema (per type):
//
//	export class SetMoveTarget {
//	  static readonly typeID = 0x12345678;
//	  sequence: number = 0;
//	  active: boolean = false;
//	  ...
//	  encode(): Uint8Array { ... }
//	}
func (g *Generator) genInputs() string {
	var b strings.Builder
	b.WriteString("// GENERATED by sdkgen — do not edit.\n\n")
	b.WriteString("// Typed client-input messages. Wire format mirrors the reflect-codec\n")
	b.WriteString("// layout in pkg/universe/reflect_marshal.go: fields encoded in source\n")
	b.WriteString("// order, little-endian, no padding. mmokit.Entity → 4-byte NetID.\n")
	b.WriteString("//\n")
	b.WriteString("// SpaceClient.send(msg) wraps the encoded body in the [0x00][u32 typeID]\n")
	b.WriteString("// [u32 bodyLen][body] frame consumed by the server's HandleClient dispatch.\n\n")

	for _, ct := range g.schema.ClientInputTypes {
		writeClientInputClass(&b, ct)
	}

	return b.String()
}

// writeClientInputClass emits one TS class for a HandleClient-eligible Go type.
// The class name is the Go type's bare struct name (e.g. "game.SetMoveTarget"
// → "SetMoveTarget"). All fields are public + zero-initialized so callers can
// construct + mutate without ceremony; the encode() instance method allocates
// a fresh buffer sized to fit all fields and serializes them in declaration
// order.
//
// Reuses broadcastClassName + broadcastFieldTSType from broadcasts.go: the
// schema shapes are identical and the per-field TS types match exactly.
func writeClientInputClass(b *strings.Builder, ct ClientInputTypeSchema) {
	className := broadcastClassName(ct.Name)

	fmt.Fprintf(b, "/** Client-input message %s (typeID 0x%08x). */\n", ct.Name, ct.TypeID)
	fmt.Fprintf(b, "export class %s {\n", className)
	fmt.Fprintf(b, "  static readonly typeID = 0x%x;\n", ct.TypeID)
	for _, f := range ct.Fields {
		fmt.Fprintf(b, "  %s: %s = %s;\n", f.Name, broadcastFieldTSType(f), broadcastFieldTSInit(f))
	}
	b.WriteString("\n")

	// Constructor accepts a Partial<T> for ergonomic field-init at the
	// call site: `client.send(new SetMoveTarget({ x: 100, y: 200, active: true }))`.
	fmt.Fprintf(b, "  constructor(init?: Partial<%s>) {\n", className)
	b.WriteString("    if (init) Object.assign(this, init);\n")
	b.WriteString("  }\n\n")

	// encode(): Uint8Array.
	//
	// Pre-allocate the exact buffer size by walking the field list. Variable-
	// size strings have to be UTF-8 encoded first to know their byte length.
	// Other field sizes come straight from the schema's Size column.
	b.WriteString("  encode(): Uint8Array {\n")
	writeReflectCodecEncode(b, ct)
	b.WriteString("  }\n")
	b.WriteString("}\n\n")
}

// writeReflectCodecEncode emits the body of an encode(): Uint8Array method
// — buffer sizing pass first (any string fields are UTF-8 encoded into
// local consts so their .length is known up-front), then the actual write
// pass into the allocated buffer.
//
// Fixed-size-only types take the simpler fast path (size known at codegen
// time, single allocation, no pre-encode).
//
// The wire layout is the reflect-codec from pkg/universe/reflect_marshal.go,
// shared by client-input frames AND typed-op Request bodies. The caller
// must wrap the emit with the surrounding `encode(): Uint8Array {` / `}`
// or equivalent. operations.go's writeBroadcastClass(withEncode=true) call
// path reuses this helper so both inputs.ts and operations.ts have one
// source of truth for the encode emission.
func writeReflectCodecEncode(b *strings.Builder, bt BroadcastTypeSchema) {
	hasVar := false
	fixedSize := 0
	for _, f := range bt.Fields {
		if isVariableSizeField(f) {
			hasVar = true
		} else {
			fixedSize += f.Size
		}
	}

	if !hasVar {
		// Fast path: every field is fixed-size, total known at codegen time.
		fmt.Fprintf(b, "    const buf = new Uint8Array(%d);\n", fixedSize)
		b.WriteString("    const dv = new DataView(buf.buffer);\n")
		b.WriteString("    let off = 0;\n")
		for _, f := range bt.Fields {
			writeReflectCodecFieldEncode(b, f)
		}
		b.WriteString("    return buf;\n")
		return
	}

	// Variable-size path: pre-encode each string into a local const so we
	// know its length up-front; sum total size from fixed-size fields +
	// (2 + bytes.length) per string + per-element size for slices.
	for _, f := range bt.Fields {
		if f.Encoding == "string" {
			fmt.Fprintf(b, "    const _%s = new TextEncoder().encode(this.%s);\n", f.Name, f.Name)
		}
	}
	// Slice items that are strings need element-level pre-encoding too.
	// Emit a helper local `_<name>_items` array containing pre-encoded
	// Uint8Arrays for each string element so the size pass and write
	// pass agree on lengths.
	for _, f := range bt.Fields {
		if f.Encoding == "slice" && f.Item != nil && f.Item.Encoding == "string" {
			fmt.Fprintf(b, "    const _%s_items: Uint8Array[] = this.%s.map(s => new TextEncoder().encode(s));\n", f.Name, f.Name)
		}
	}

	// Size expression: fixed bytes + per-string + per-slice contributions.
	parts := []string{fmt.Sprintf("%d", fixedSize)}
	for _, f := range bt.Fields {
		switch {
		case f.Encoding == "string":
			parts = append(parts, fmt.Sprintf("2 + _%s.length", f.Name))
		case f.Encoding == "slice":
			parts = append(parts, sliceSizeExpr(f))
		}
	}
	fmt.Fprintf(b, "    const buf = new Uint8Array(%s);\n", strings.Join(parts, " + "))
	b.WriteString("    const dv = new DataView(buf.buffer);\n")
	b.WriteString("    let off = 0;\n")
	for _, f := range bt.Fields {
		writeReflectCodecFieldEncode(b, f)
	}
	b.WriteString("    return buf;\n")
}

// isVariableSizeField returns true when the field's wire size depends on
// runtime data (string length, slice element count, or string-bearing
// slice elements).
func isVariableSizeField(f BroadcastFieldSchema) bool {
	switch f.Encoding {
	case "string", "slice", "bytes":
		return true
	}
	return false
}

// sliceSizeExpr returns a TypeScript expression evaluating to the total
// byte size of the slice (including the 2-byte length prefix). Used in
// the buffer-sizing pass before writeReflectCodecFieldEncode actually
// emits the slice loop.
func sliceSizeExpr(f BroadcastFieldSchema) string {
	if f.Item == nil {
		panic(fmt.Sprintf("sdkgen: slice field %q missing item schema", f.Name))
	}
	switch f.Item.Encoding {
	case "string":
		// 2 (slice len) + sum(2 + element bytes) per pre-encoded item.
		return fmt.Sprintf("2 + _%s_items.reduce((acc, b) => acc + 2 + b.length, 0)", f.Name)
	case "f32", "f64",
		"u8", "u16", "u32", "u64",
		"i8", "i16", "i32", "i64",
		"bool", "entity":
		// Fixed-stride scalars: 2 (slice len) + N * itemSize.
		return fmt.Sprintf("2 + this.%s.length * %d", f.Name, f.Item.Size)
	default:
		panic(fmt.Sprintf("sdkgen: unsupported slice item encoding %q for field %q", f.Item.Encoding, f.Name))
	}
}

// writeReflectCodecFieldEncode emits one encode line for a single field.
// Each line writes the field's bytes via DataView (or buf.set for strings)
// and advances `off`. Format mirrors reflect_marshal.marshalValue exactly.
func writeReflectCodecFieldEncode(b *strings.Builder, f BroadcastFieldSchema) {
	switch f.Encoding {
	case "f32":
		fmt.Fprintf(b, "    dv.setFloat32(off, this.%s, true); off += 4;\n", f.Name)
	case "f64":
		fmt.Fprintf(b, "    dv.setFloat64(off, this.%s, true); off += 8;\n", f.Name)
	case "u8":
		fmt.Fprintf(b, "    dv.setUint8(off, this.%s); off += 1;\n", f.Name)
	case "u16":
		fmt.Fprintf(b, "    dv.setUint16(off, this.%s, true); off += 2;\n", f.Name)
	case "u32", "entity":
		// `entity` rides on the registered reflect codec for mmokit.Entity,
		// which encodes only the 4-byte NetID. Callers pass the NetID as
		// a number on the TS-class field — same shape as broadcast decode.
		fmt.Fprintf(b, "    dv.setUint32(off, this.%s, true); off += 4;\n", f.Name)
	case "u64":
		// JS `number` only safely covers up to 2^53; for the typical
		// mmokit u64 use cases (request sequences, NetIDs) that's enough.
		// BigInt-typed at the boundary; .setBigUint64 wants a BigInt arg.
		fmt.Fprintf(b, "    dv.setBigUint64(off, BigInt(this.%s), true); off += 8;\n", f.Name)
	case "i8":
		fmt.Fprintf(b, "    dv.setInt8(off, this.%s); off += 1;\n", f.Name)
	case "i16":
		fmt.Fprintf(b, "    dv.setInt16(off, this.%s, true); off += 2;\n", f.Name)
	case "i32":
		fmt.Fprintf(b, "    dv.setInt32(off, this.%s, true); off += 4;\n", f.Name)
	case "i64":
		fmt.Fprintf(b, "    dv.setBigInt64(off, BigInt(this.%s), true); off += 8;\n", f.Name)
	case "bool":
		fmt.Fprintf(b, "    dv.setUint8(off, this.%s ? 1 : 0); off += 1;\n", f.Name)
	case "string":
		// Matches reflect_marshal: 2-byte LE length prefix, then UTF-8 bytes.
		// _<name> was pre-encoded by writeReflectCodecEncode so we know its
		// length before the size pass; here we just write the prefix + body
		// bytes.
		fmt.Fprintf(b, "    dv.setUint16(off, _%s.length, true); off += 2;\n", f.Name)
		fmt.Fprintf(b, "    buf.set(_%s, off); off += _%s.length;\n", f.Name, f.Name)
	case "slice":
		// Matches reflect_marshal: 2-byte LE length prefix, then N elements.
		// String elements were pre-encoded into _<name>_items by
		// writeReflectCodecEncode so we know each item's length up-front.
		writeReflectCodecSliceEncode(b, f)
	default:
		panic(fmt.Sprintf("sdkgen: unsupported reflect-codec field encoding %q for field %q", f.Encoding, f.Name))
	}
}

// writeReflectCodecSliceEncode emits the loop that writes a slice's
// length prefix + elements. Mirrors reflect_marshal's slice path:
// [u16 len][elem0]...[elemN-1].
func writeReflectCodecSliceEncode(b *strings.Builder, f BroadcastFieldSchema) {
	if f.Item == nil {
		panic(fmt.Sprintf("sdkgen: slice field %q missing item schema", f.Name))
	}
	fmt.Fprintf(b, "    dv.setUint16(off, this.%s.length, true); off += 2;\n", f.Name)
	switch f.Item.Encoding {
	case "string":
		fmt.Fprintf(b, "    for (const _b of _%s_items) {\n", f.Name)
		b.WriteString("      dv.setUint16(off, _b.length, true); off += 2;\n")
		b.WriteString("      buf.set(_b, off); off += _b.length;\n")
		b.WriteString("    }\n")
	case "f32":
		fmt.Fprintf(b, "    for (const _v of this.%s) { dv.setFloat32(off, _v, true); off += 4; }\n", f.Name)
	case "f64":
		fmt.Fprintf(b, "    for (const _v of this.%s) { dv.setFloat64(off, _v, true); off += 8; }\n", f.Name)
	case "u8":
		fmt.Fprintf(b, "    for (const _v of this.%s) { dv.setUint8(off, _v); off += 1; }\n", f.Name)
	case "u16":
		fmt.Fprintf(b, "    for (const _v of this.%s) { dv.setUint16(off, _v, true); off += 2; }\n", f.Name)
	case "u32", "entity":
		fmt.Fprintf(b, "    for (const _v of this.%s) { dv.setUint32(off, _v, true); off += 4; }\n", f.Name)
	case "u64":
		fmt.Fprintf(b, "    for (const _v of this.%s) { dv.setBigUint64(off, BigInt(_v), true); off += 8; }\n", f.Name)
	case "i8":
		fmt.Fprintf(b, "    for (const _v of this.%s) { dv.setInt8(off, _v); off += 1; }\n", f.Name)
	case "i16":
		fmt.Fprintf(b, "    for (const _v of this.%s) { dv.setInt16(off, _v, true); off += 2; }\n", f.Name)
	case "i32":
		fmt.Fprintf(b, "    for (const _v of this.%s) { dv.setInt32(off, _v, true); off += 4; }\n", f.Name)
	case "i64":
		fmt.Fprintf(b, "    for (const _v of this.%s) { dv.setBigInt64(off, BigInt(_v), true); off += 8; }\n", f.Name)
	case "bool":
		fmt.Fprintf(b, "    for (const _v of this.%s) { dv.setUint8(off, _v ? 1 : 0); off += 1; }\n", f.Name)
	default:
		panic(fmt.Sprintf("sdkgen: unsupported slice item encoding %q for field %q", f.Item.Encoding, f.Name))
	}
}
