package main

import (
	"strings"
)

// genOperations emits operations.ts containing one Request class + one
// Response class per registered typed-op. Returns "" when no typed-ops are
// registered.
//
// Wire layout for the body bytes (the Req/Res types) uses the reflect-codec
// from pkg/universe/reflect_marshal.go, identical to broadcasts.ts and
// inputs.ts. The frame layout (channel byte, typeID, request_id, body_len)
// is built on the client by the callOp<Req, Res> helper in client.ts
// (emitted by genClient when typed_operations is non-empty).
//
// Output schema (per op):
//
//	export class MarketBrowseRequest {
//	  static readonly typeID = ...;
//	  ... fields ...
//	  static decode(buf: Uint8Array): MarketBrowseRequest { ... }
//	  encode(): Uint8Array { ... }
//	}
//
//	export class MarketOrderBookResponse {
//	  static readonly typeID = ...;
//	  ... fields ...
//	  static decode(buf: Uint8Array): MarketOrderBookResponse { ... }
//	}
func (g *Generator) genOperations() string {
	if len(g.schema.TypedOperations) == 0 {
		return ""
	}

	var b strings.Builder
	b.WriteString("// GENERATED by sdkgen — do not edit.\n\n")
	b.WriteString("// Typed operation Request + Response classes. Wire format:\n")
	b.WriteString("//   [0x01][typeID:u32 LE][request_id:u64 LE][body_len:u32 LE][body]\n")
	b.WriteString("// Bodies use the reflect-codec layout from pkg/universe/reflect_marshal.go\n")
	b.WriteString("// (matches broadcasts.ts and inputs.ts).\n\n")

	// Multiple ops can share a Response class (e.g. MarketOrderResultResponse
	// covers create/cancel/instant-trade) so dedupe by class name. Request
	// types are 1:1 with ops by construction (each registers a unique pair)
	// but we dedupe both sides defensively.
	emitted := map[string]struct{}{}
	emit := func(bt BroadcastTypeSchema, withEncode bool) {
		name := broadcastClassName(bt.Name)
		if _, dup := emitted[name]; dup {
			return
		}
		emitted[name] = struct{}{}
		writeBroadcastClass(&b, bt, withEncode)
	}
	for _, op := range g.schema.TypedOperations {
		// Request: encode (client → server) + decode (for symmetry).
		emit(BroadcastTypeSchema{
			Name:   op.RequestTypeName,
			TypeID: op.RequestTypeID,
			Fields: op.RequestFields,
		}, true)

		// Response: decode-only (server → client).
		emit(BroadcastTypeSchema{
			Name:   op.ResponseTypeName,
			TypeID: op.ResponseTypeID,
			Fields: op.ResponseFields,
		}, false)
	}

	return b.String()
}

// typedOpRequestClassName returns the TS class name for a typed-op Request.
// "marketplace.MarketBrowseRequest" → "MarketBrowseRequest".
func typedOpRequestClassName(op TypedOperationSchema) string {
	return broadcastClassName(op.RequestTypeName)
}

// typedOpResponseClassName returns the TS class name for a typed-op Response.
// "marketplace.MarketOrderBookResponse" → "MarketOrderBookResponse".
func typedOpResponseClassName(op TypedOperationSchema) string {
	return broadcastClassName(op.ResponseTypeName)
}

// writeTypedOpDispatch emits the body of the typed-op response handler that
// runs inside <Game>Client.handleOperation. Reads the
// [typeID:u32 LE][request_id:u64 LE][body_len:u32 LE][body] header, looks
// up the matching pending Promise by request_id, and either rejects (when
// the response typeID is OperationError) or resolves with resCls.decode(body).
//
// Indented for nesting inside an `if (payload[0] !== 0x08) { ... }` block
// (legacy-coexist path) or directly inside handleOperation (pure-typed-op
// path). The caller is responsible for the surrounding control flow.
func writeTypedOpDispatch(b *strings.Builder) {
	b.WriteString("      // Typed-op response: [typeID:u32 LE][request_id:u64 LE][bodyLen:u32 LE][body].\n")
	b.WriteString("      if (payload.length < 16) {\n")
	b.WriteString("        console.warn(`typed-op frame: truncated header (len=${payload.length})`);\n")
	b.WriteString("        return;\n")
	b.WriteString("      }\n")
	b.WriteString("      const opDV = new DataView(payload.buffer, payload.byteOffset, payload.byteLength);\n")
	b.WriteString("      const resTypeID = opDV.getUint32(0, true);\n")
	b.WriteString("      const reqID = opDV.getBigUint64(4, true);\n")
	b.WriteString("      const bodyLen = opDV.getUint32(12, true);\n")
	b.WriteString("      if (16 + bodyLen > payload.length) {\n")
	b.WriteString("        console.warn(`typed-op frame: truncated body for typeID=0x${resTypeID.toString(16)}`);\n")
	b.WriteString("        return;\n")
	b.WriteString("      }\n")
	b.WriteString("      const body = payload.subarray(16, 16 + bodyLen);\n")
	b.WriteString("      const pending = this.pendingTypedOps.get(reqID);\n")
	b.WriteString("      if (!pending) {\n")
	b.WriteString("        console.warn(`typed-op response for unknown request_id ${reqID}`);\n")
	b.WriteString("        return;\n")
	b.WriteString("      }\n")
	b.WriteString("      this.pendingTypedOps.delete(reqID);\n")
	// OperationError typeID intercept — reject the matching promise with the
	// carried code+message. OperationError is auto-registered as a server
	// event by Phase 1 so its TS class lives in broadcasts.ts.
	b.WriteString("      if (resTypeID === OperationError.typeID) {\n")
	b.WriteString("        const err = OperationError.decode(body);\n")
	b.WriteString("        pending.reject(new Error(`OperationError code=${err.code}: ${err.message}`));\n")
	b.WriteString("        return;\n")
	b.WriteString("      }\n")
	b.WriteString("      pending.resolve(pending.resCls.decode(body));\n")
}

// typedOpMethodName converts a Request class name to a wrapper method name.
// Strips a trailing "Request" suffix and lowercases the first character so
// `MarketBrowseRequest` → `marketBrowse`. Falls back to lowercasing the first
// character when the suffix is absent.
func typedOpMethodName(reqClassName string) string {
	name := strings.TrimSuffix(reqClassName, "Request")
	if name == "" {
		name = reqClassName
	}
	if len(name) == 0 {
		return name
	}
	return strings.ToLower(name[:1]) + name[1:]
}
