// GENERATED by sdkgen — do not edit.

import { Transport } from "./transport.js";
import { SpaceDeltaDecoder } from "./delta-decoder.js";
import { TypedDispatcher, BankContents, BeamClip, CurrencyUpdate, Docked, DockingState, EquipResult, MapData, PlayerDied, PlayerOwnState, PlayerSpawned, TransferResult, MarketTradeNotification, CellChange, DebugInfo, OperationError, PlayerEntityAssigned, Pong, ServerConfig, WorldDelta } from "./broadcasts.js";
import { AuthChangePasswordRequest, AuthChangePasswordResponse, AuthLoginRequest, AuthLoginResponse, AuthLogoutRequest, AuthLogoutResponse, AuthRegisterRequest, AuthRegisterResponse, AuthValidateTokenRequest, AuthValidateTokenResponse, BankRequest, BankResponse, MarketBrowseRequest, MarketCancelOrderRequest, MarketCreateOrderRequest, MarketInstantTradeRequest, MarketMyOrdersRequest, MarketMyOrdersResponse, MarketOrderBookResponse, MarketOrderResultResponse, RepairRequest, RepairResponse } from "./operations.js";

/** Structural fingerprint of the protocol this SDK was generated from.
 *  Sent at connection setup; the server refuses a mismatch. */
export const SCHEMA_FINGERPRINT = "31bfd4eb";

/** Appends the schema fingerprint to a connect URL, preserving any
 *  query the caller already put there. */
function withSchemaFingerprint(url: string): string {
  const u = new URL(url);
  u.searchParams.set("schema", SCHEMA_FINGERPRINT);
  return u.toString();
}

export interface SpaceClientOptions {
  url: string;
  onOpen?: () => void;
  onClose?: (ev: CloseEvent) => void;
  onError?: (ev: Event) => void;
  /** Fires when the server reports a protocol fingerprint other than the
   *  one this SDK was generated from. The connection-setup gate refuses a
   *  stale CLIENT before the upgrade, so reaching here means the SERVER is
   *  older than this SDK and ignored the fingerprint we sent. */
  onSchemaMismatch?: (serverFingerprint: string, clientFingerprint: string) => void;
}

export class SpaceClient {
  private transport: Transport;
  private decoder = new SpaceDeltaDecoder();
  /** Typed broadcast dispatcher — register handlers for AoI-filtered
   *  events emitted by the server's HandleAll[T] machinery. */
  readonly typedEvents = new TypedDispatcher();
  private pendingTypedOps = new Map<bigint, { resolve: (msg: any) => void; reject: (err: Error) => void; resCls: { typeID: number; decode(buf: Uint8Array): any } }>();
  private nextTypedOpRequestID: bigint = 1n;

  constructor(private options: SpaceClientOptions) {
    this.transport = new Transport(withSchemaFingerprint(options.url));
  }

  connect(): void {
    this.transport.connect();
    const ws = this.transport.socket!;
    if (this.options.onOpen) ws.onopen = this.options.onOpen;
    if (this.options.onClose) ws.onclose = this.options.onClose;
    if (this.options.onError) ws.onerror = this.options.onError;
    this.typedEvents.on(ServerConfig, (cfg) => {
      const server = (cfg.schemaHash >>> 0).toString(16).padStart(8, "0");
      if (cfg.schemaHash !== 0 && server !== SCHEMA_FINGERPRINT) {
        this.options.onSchemaMismatch?.(server, SCHEMA_FINGERPRINT);
      }
    });
    this.transport.onEvent((payload) => this.handleEvent(payload));
    this.transport.onOperation((payload) => this.handleOperation(payload));
  }

  disconnect(): void {
    // Reject any pending operations.
    for (const pending of this.pendingTypedOps.values()) {
      pending.reject(new Error("client disconnected"));
    }
    this.pendingTypedOps.clear();
    this.transport.close();
  }
  get connected(): boolean { return this.transport.connected; }

  /** Raw transport handle for advanced use (operations channel,
   *  custom protocol extensions). Most app code should use the typed
   *  send* / on* methods on this class instead. */
  get rawTransport(): Transport { return this.transport; }

  private handleEvent(payload: Uint8Array): void {
    if (payload.length === 0) return;
    let off = 0;
    while (off + 8 <= payload.length) {
      const view = new DataView(payload.buffer, payload.byteOffset + off, 8);
      const typeID = view.getUint32(0, true);
      const bodyLen = view.getUint32(4, true);
      off += 8;
      if (off + bodyLen > payload.length) {
        console.warn(`typed-event frame: truncated body for typeID=0x${typeID.toString(16)}`);
        return;
      }
      const body = payload.subarray(off, off + bodyLen);
      off += bodyLen;
      this.typedEvents.dispatch(typeID, body);
    }
  }

  /** Send a typed client-input message (mmokit.HandleClient).
   *
   *  msg must be an instance of a class generated into inputs.ts —
   *  exposing static typeID and instance encode(): Uint8Array. The
   *  resulting wire frame is dispatched server-side to the matching
   *  HandleClient[T] handler. */
  send(msg: { encode(): Uint8Array }): void {
    const ctor = msg.constructor as unknown as { typeID: number };
    this.transport.sendClientInput(ctor.typeID, msg.encode());
  }

  /** Subscribe to typed server event game.BankContents (typeID 0xce9d072f). */
  onBankContents(handler: (msg: BankContents) => void): () => void {
    return this.typedEvents.on(BankContents, handler);
  }

  /** Subscribe to typed server event game.BeamClip (typeID 0x35def132). */
  onBeamClip(handler: (msg: BeamClip) => void): () => void {
    return this.typedEvents.on(BeamClip, handler);
  }

  /** Subscribe to typed server event game.CurrencyUpdate (typeID 0x722e1d79). */
  onCurrencyUpdate(handler: (msg: CurrencyUpdate) => void): () => void {
    return this.typedEvents.on(CurrencyUpdate, handler);
  }

  /** Subscribe to typed server event game.Docked (typeID 0x8bf5541d). */
  onDocked(handler: (msg: Docked) => void): () => void {
    return this.typedEvents.on(Docked, handler);
  }

  /** Subscribe to typed server event game.DockingState (typeID 0x5c80df11). */
  onDockingState(handler: (msg: DockingState) => void): () => void {
    return this.typedEvents.on(DockingState, handler);
  }

  /** Subscribe to typed server event game.EquipResult (typeID 0x50af4abc). */
  onEquipResult(handler: (msg: EquipResult) => void): () => void {
    return this.typedEvents.on(EquipResult, handler);
  }

  /** Subscribe to typed server event game.MapData (typeID 0xc16d89a3). */
  onMapData(handler: (msg: MapData) => void): () => void {
    return this.typedEvents.on(MapData, handler);
  }

  /** Subscribe to typed server event game.PlayerDied (typeID 0xef56f740). */
  onPlayerDied(handler: (msg: PlayerDied) => void): () => void {
    return this.typedEvents.on(PlayerDied, handler);
  }

  /** Subscribe to typed server event game.PlayerOwnState (typeID 0xa01e17d7). */
  onPlayerOwnState(handler: (msg: PlayerOwnState) => void): () => void {
    return this.typedEvents.on(PlayerOwnState, handler);
  }

  /** Subscribe to typed server event game.PlayerSpawned (typeID 0xafa7d058). */
  onPlayerSpawned(handler: (msg: PlayerSpawned) => void): () => void {
    return this.typedEvents.on(PlayerSpawned, handler);
  }

  /** Subscribe to typed server event game.TransferResult (typeID 0xed313859). */
  onTransferResult(handler: (msg: TransferResult) => void): () => void {
    return this.typedEvents.on(TransferResult, handler);
  }

  /** Subscribe to typed server event marketplace.MarketTradeNotification (typeID 0x42a6c8cf). */
  onMarketTradeNotification(handler: (msg: MarketTradeNotification) => void): () => void {
    return this.typedEvents.on(MarketTradeNotification, handler);
  }

  /** Subscribe to typed server event mmokit.CellChange (typeID 0x474e8b92). */
  onCellChange(handler: (msg: CellChange) => void): () => void {
    return this.typedEvents.on(CellChange, handler);
  }

  /** Subscribe to typed server event mmokit.DebugInfo (typeID 0x83f2dca1). */
  onDebugInfo(handler: (msg: DebugInfo) => void): () => void {
    return this.typedEvents.on(DebugInfo, handler);
  }

  /** Subscribe to typed server event mmokit.OperationError (typeID 0x3d88aecb). */
  onOperationError(handler: (msg: OperationError) => void): () => void {
    return this.typedEvents.on(OperationError, handler);
  }

  /** Subscribe to typed server event mmokit.PlayerEntityAssigned (typeID 0x02a6f7d8). */
  onPlayerEntityAssigned(handler: (msg: PlayerEntityAssigned) => void): () => void {
    return this.typedEvents.on(PlayerEntityAssigned, handler);
  }

  /** Subscribe to typed server event mmokit.Pong (typeID 0x8527c2fc). */
  onPong(handler: (msg: Pong) => void): () => void {
    return this.typedEvents.on(Pong, handler);
  }

  /** Subscribe to typed server event mmokit.ServerConfig (typeID 0xaa1dd89b). */
  onServerConfig(handler: (msg: ServerConfig) => void): () => void {
    return this.typedEvents.on(ServerConfig, handler);
  }

  /** Subscribe to typed server event mmokit.WorldDelta (typeID 0x065b16f4). */
  onWorldDelta(handler: (msg: WorldDelta) => void): () => void {
    return this.typedEvents.on(WorldDelta, handler);
  }

  private handleOperation(payload: Uint8Array): void {
    if (payload.length === 0) return;
      // Typed-op response: [typeID:u32 LE][request_id:u64 LE][bodyLen:u32 LE][body].
      if (payload.length < 16) {
        console.warn(`typed-op frame: truncated header (len=${payload.length})`);
        return;
      }
      const opDV = new DataView(payload.buffer, payload.byteOffset, payload.byteLength);
      const resTypeID = opDV.getUint32(0, true);
      const reqID = opDV.getBigUint64(4, true);
      const bodyLen = opDV.getUint32(12, true);
      if (16 + bodyLen > payload.length) {
        console.warn(`typed-op frame: truncated body for typeID=0x${resTypeID.toString(16)}`);
        return;
      }
      const body = payload.subarray(16, 16 + bodyLen);
      const pending = this.pendingTypedOps.get(reqID);
      if (!pending) {
        console.warn(`typed-op response for unknown request_id ${reqID}`);
        return;
      }
      this.pendingTypedOps.delete(reqID);
      if (resTypeID === OperationError.typeID) {
        const err = OperationError.decode(body);
        pending.reject(new Error(`OperationError code=${err.code}: ${err.message}`));
        return;
      }
      pending.resolve(pending.resCls.decode(body));
    return;
  }

  /** Private helper: encode + send a typed-op request, return a
   *  Promise that resolves with the decoded Response. */
  private callOp<Req extends { encode(): Uint8Array }, Res>(
    req: Req,
    resCls: { typeID: number; decode(buf: Uint8Array): Res }
  ): Promise<Res> {
    const reqID = this.nextTypedOpRequestID++;
    const reqTypeID = (req.constructor as unknown as { typeID: number }).typeID;
    const body = req.encode();
    const frame = new Uint8Array(1 + 4 + 8 + 4 + body.length);
    const dv = new DataView(frame.buffer);
    frame[0] = 0x01;
    dv.setUint32(1, reqTypeID, true);
    dv.setBigUint64(5, reqID, true);
    dv.setUint32(13, body.length, true);
    frame.set(body, 17);
    return new Promise<Res>((resolve, reject) => {
      this.pendingTypedOps.set(reqID, { resolve, reject, resCls });
      this.transport.sendRaw(frame);
    });
  }

  /** Typed op auth.AuthChangePasswordRequest → auth.AuthChangePasswordResponse (kind=gateway-local). */
  authChangePassword(req: AuthChangePasswordRequest): Promise<AuthChangePasswordResponse> {
    return this.callOp<AuthChangePasswordRequest, AuthChangePasswordResponse>(req, AuthChangePasswordResponse);
  }

  /** Typed op auth.AuthLoginRequest → auth.AuthLoginResponse (kind=gateway-local). */
  authLogin(req: AuthLoginRequest): Promise<AuthLoginResponse> {
    return this.callOp<AuthLoginRequest, AuthLoginResponse>(req, AuthLoginResponse);
  }

  /** Typed op auth.AuthLogoutRequest → auth.AuthLogoutResponse (kind=gateway-local). */
  authLogout(req: AuthLogoutRequest): Promise<AuthLogoutResponse> {
    return this.callOp<AuthLogoutRequest, AuthLogoutResponse>(req, AuthLogoutResponse);
  }

  /** Typed op auth.AuthRegisterRequest → auth.AuthRegisterResponse (kind=gateway-local). */
  authRegister(req: AuthRegisterRequest): Promise<AuthRegisterResponse> {
    return this.callOp<AuthRegisterRequest, AuthRegisterResponse>(req, AuthRegisterResponse);
  }

  /** Typed op auth.AuthValidateTokenRequest → auth.AuthValidateTokenResponse (kind=gateway-local). */
  authValidateToken(req: AuthValidateTokenRequest): Promise<AuthValidateTokenResponse> {
    return this.callOp<AuthValidateTokenRequest, AuthValidateTokenResponse>(req, AuthValidateTokenResponse);
  }

  /** Typed op game.BankRequest → game.BankResponse (kind=player-cell). */
  bank(req: BankRequest): Promise<BankResponse> {
    return this.callOp<BankRequest, BankResponse>(req, BankResponse);
  }

  /** Typed op game.RepairRequest → game.RepairResponse (kind=player-cell). */
  repair(req: RepairRequest): Promise<RepairResponse> {
    return this.callOp<RepairRequest, RepairResponse>(req, RepairResponse);
  }

  /** Typed op marketplace.MarketBrowseRequest → marketplace.MarketOrderBookResponse (kind=player-cell). */
  marketBrowse(req: MarketBrowseRequest): Promise<MarketOrderBookResponse> {
    return this.callOp<MarketBrowseRequest, MarketOrderBookResponse>(req, MarketOrderBookResponse);
  }

  /** Typed op marketplace.MarketCancelOrderRequest → marketplace.MarketOrderResultResponse (kind=player-cell). */
  marketCancelOrder(req: MarketCancelOrderRequest): Promise<MarketOrderResultResponse> {
    return this.callOp<MarketCancelOrderRequest, MarketOrderResultResponse>(req, MarketOrderResultResponse);
  }

  /** Typed op marketplace.MarketCreateOrderRequest → marketplace.MarketOrderResultResponse (kind=player-cell). */
  marketCreateOrder(req: MarketCreateOrderRequest): Promise<MarketOrderResultResponse> {
    return this.callOp<MarketCreateOrderRequest, MarketOrderResultResponse>(req, MarketOrderResultResponse);
  }

  /** Typed op marketplace.MarketInstantTradeRequest → marketplace.MarketOrderResultResponse (kind=player-cell). */
  marketInstantTrade(req: MarketInstantTradeRequest): Promise<MarketOrderResultResponse> {
    return this.callOp<MarketInstantTradeRequest, MarketOrderResultResponse>(req, MarketOrderResultResponse);
  }

  /** Typed op marketplace.MarketMyOrdersRequest → marketplace.MarketMyOrdersResponse (kind=player-cell). */
  marketMyOrders(req: MarketMyOrdersRequest): Promise<MarketMyOrdersResponse> {
    return this.callOp<MarketMyOrdersRequest, MarketMyOrdersResponse>(req, MarketMyOrdersResponse);
  }

  /** Clear delta baselines (call on cell change / reconnect). */
  clearBaselines(): void { this.decoder.clear(); }
}
