// GENERATED by sdkgen — do not edit.

const CH_EVENT = 0x00;
const CH_OPERATION = 0x01;

export type MessageHandler = (data: Uint8Array) => void;

export class Transport {
  private ws: WebSocket | null = null;
  private eventHandlers: MessageHandler[] = [];
  private operationHandlers: MessageHandler[] = [];

  constructor(private url: string) {}

  connect(): void {
    this.ws = new WebSocket(this.url);
    this.ws.binaryType = "arraybuffer";
    this.ws.onmessage = (ev) => {
      const data = new Uint8Array(ev.data as ArrayBuffer);
      if (data.length < 1) return;
      const channel = data[0];
      const payload = data.subarray(1);
      if (channel === CH_EVENT) {
        for (const h of this.eventHandlers) h(payload);
      } else if (channel === CH_OPERATION) {
        for (const h of this.operationHandlers) h(payload);
      }
    };
  }

  get socket(): WebSocket | null { return this.ws; }
  get connected(): boolean { return this.ws?.readyState === WebSocket.OPEN; }

  close(): void { this.ws?.close(); this.ws = null; }

  sendEvent(data: Uint8Array): void {
    if (!this.ws || this.ws.readyState !== WebSocket.OPEN) return;
    const frame = new Uint8Array(1 + data.length);
    frame[0] = CH_EVENT;
    frame.set(data, 1);
    this.ws.send(frame);
  }

  sendOperation(data: Uint8Array): void {
    if (!this.ws || this.ws.readyState !== WebSocket.OPEN) return;
    const frame = new Uint8Array(1 + data.length);
    frame[0] = CH_OPERATION;
    frame.set(data, 1);
    this.ws.send(frame);
  }

  /**
   * Send a fully-built frame as-is (no channel-byte prefix added). The
   * caller is responsible for the entire wire layout including the channel
   * byte. Used by the typed-op Promise correlator in <Game>Client, which
   * builds the full [0x01][typeID][requestID][bodyLen][body] frame in one
   * allocation rather than two.
   *
   * The parameter is Uint8Array<ArrayBuffer> rather than a bare Uint8Array
   * because this is the only send path taking a caller-supplied array. Since
   * TypeScript 5.7 the bare form widens to Uint8Array<ArrayBufferLike>, which
   * admits SharedArrayBuffer-backed views that WebSocket.send cannot accept —
   * TypeScript 6 rejects it outright. Any normally allocated array satisfies
   * this; the sibling methods allocate their own frames and infer it.
   */
  sendRaw(frame: Uint8Array<ArrayBuffer>): void {
    if (!this.ws || this.ws.readyState !== WebSocket.OPEN) return;
    this.ws.send(frame);
  }

  /**
   * Send a typed client-input frame (mmokit.HandleClient registry).
   * Wire layout: [byte 0x00][u32 typeID][u32 bodyLen][body bytes].
   * Body is produced by the matching TS class's encode() instance method;
   * the server resolves typeID back to the registered Go type and decodes
   * the body via the same reflection codec used for broadcast events.
   *
   * Inputs and server events both ride channel 0x00 — they're
   * distinguished server-side by typeID via the typed dispatcher.
   */
  sendClientInput(typeID: number, body: Uint8Array): void {
    if (!this.ws || this.ws.readyState !== WebSocket.OPEN) return;
    const frame = new Uint8Array(1 + 4 + 4 + body.length);
    const dv = new DataView(frame.buffer);
    frame[0] = CH_EVENT;
    dv.setUint32(1, typeID, true);
    dv.setUint32(5, body.length, true);
    frame.set(body, 9);
    this.ws.send(frame);
  }

  onEvent(handler: MessageHandler): void { this.eventHandlers.push(handler); }
  onOperation(handler: MessageHandler): void { this.operationHandlers.push(handler); }
}
