// GENERATED by sdkgen — do not edit.

// Typed broadcast events. Wire format mirrors the reflect-codec layout
// in pkg/universe/reflect_marshal.go: fields encoded in source order,
// little-endian, no padding. mmokit.Entity → 4-byte NetID.

/** Broadcast-eligible event mmokit.CellChange (typeID 0x474e8b92). */
export class CellChange {
  static readonly typeID = 0x474e8b92;
  cellX: number = 0;
  cellY: number = 0;

  static decode(buf: Uint8Array): CellChange {
    const dv = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
    let off = 0;
    const m = new CellChange();
    m.cellX = dv.getInt32(off, true); off += 4;
    m.cellY = dv.getInt32(off, true); off += 4;
    return m;
  }
}

/** Broadcast-eligible event mmokit.DebugInfo (typeID 0x83f2dca1). */
export class DebugInfo {
  static readonly typeID = 0x83f2dca1;
  topology: { cells: { cellX: number; cellY: number; depth: number; size: number; originX: number; originY: number; nodeID: string }[]; gridW: number; gridH: number; baseCellSize: number } = { cells: [], gridW: 0, gridH: 0, baseCellSize: 0 };
  aoIRadius: number = 0;

  static decode(buf: Uint8Array): DebugInfo {
    const dv = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
    let off = 0;
    const m = new DebugInfo();
    {
      const sliceLen = dv.getUint16(off, true); off += 2;
      for (let i = 0; i < sliceLen; i++) {
        const item: { cellX: number; cellY: number; depth: number; size: number; originX: number; originY: number; nodeID: string } = { cellX: 0, cellY: 0, depth: 0, size: 0, originX: 0, originY: 0, nodeID: "" };
            item.cellX = dv.getInt32(off, true); off += 4;
            item.cellY = dv.getInt32(off, true); off += 4;
            item.depth = dv.getUint32(off, true); off += 4;
            item.size = dv.getFloat32(off, true); off += 4;
            item.originX = dv.getFloat32(off, true); off += 4;
            item.originY = dv.getFloat32(off, true); off += 4;
    {
      const sl = dv.getUint16(off, true); off += 2;
              item.nodeID = new TextDecoder().decode(buf.subarray(off, off + sl)); off += sl;
    }
        m.topology.cells.push(item);
      }
    }
    m.topology.gridW = dv.getInt32(off, true); off += 4;
    m.topology.gridH = dv.getInt32(off, true); off += 4;
    m.topology.baseCellSize = dv.getFloat32(off, true); off += 4;
    m.aoIRadius = dv.getFloat32(off, true); off += 4;
    return m;
  }
}

/** Broadcast-eligible event mmokit.OperationError (typeID 0x3d88aecb). */
export class OperationError {
  static readonly typeID = 0x3d88aecb;
  code: number = 0;
  message: string = "";

  static decode(buf: Uint8Array): OperationError {
    const dv = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
    let off = 0;
    const m = new OperationError();
    m.code = dv.getUint32(off, true); off += 4;
    {
      const sl = dv.getUint16(off, true); off += 2;
      m.message = new TextDecoder().decode(buf.subarray(off, off + sl)); off += sl;
    }
    return m;
  }
}

/** Broadcast-eligible event mmokit.PlayerEntityAssigned (typeID 0x02a6f7d8). */
export class PlayerEntityAssigned {
  static readonly typeID = 0x2a6f7d8;
  entityNetID: number = 0;
  worldX: number = 0;
  worldY: number = 0;

  static decode(buf: Uint8Array): PlayerEntityAssigned {
    const dv = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
    let off = 0;
    const m = new PlayerEntityAssigned();
    m.entityNetID = dv.getUint32(off, true); off += 4;
    m.worldX = dv.getFloat32(off, true); off += 4;
    m.worldY = dv.getFloat32(off, true); off += 4;
    return m;
  }
}

/** Broadcast-eligible event mmokit.Pong (typeID 0x8527c2fc). */
export class Pong {
  static readonly typeID = 0x8527c2fc;
  clientTime: number = 0;
  serverTime: number = 0;

  static decode(buf: Uint8Array): Pong {
    const dv = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
    let off = 0;
    const m = new Pong();
    m.clientTime = Number(dv.getBigInt64(off, true)); off += 8;
    m.serverTime = Number(dv.getBigInt64(off, true)); off += 8;
    return m;
  }
}

/** Broadcast-eligible event mmokit.ServerConfig (typeID 0xaa1dd89b). */
export class ServerConfig {
  static readonly typeID = 0xaa1dd89b;
  tickRate: number = 0;
  schemaHash: number = 0;

  static decode(buf: Uint8Array): ServerConfig {
    const dv = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
    let off = 0;
    const m = new ServerConfig();
    m.tickRate = dv.getUint32(off, true); off += 4;
    m.schemaHash = dv.getUint32(off, true); off += 4;
    return m;
  }
}

/** Broadcast-eligible event mmokit.WorldDelta (typeID 0x065b16f4). */
export class WorldDelta {
  static readonly typeID = 0x65b16f4;
  body: Uint8Array = new Uint8Array(0);
  streamEpoch: number = 0;

  static decode(buf: Uint8Array): WorldDelta {
    const dv = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
    let off = 0;
    const m = new WorldDelta();
    {
      const bl = dv.getUint32(off, true); off += 4;
      m.body = buf.slice(off, off + bl); off += bl;
    }
    m.streamEpoch = dv.getUint32(off, true); off += 4;
    return m;
  }
}

/** Dispatches incoming TypedEvent (typeID + body bytes) to typed handlers. */
export class TypedDispatcher {
  private handlers = new Map<number, (raw: Uint8Array) => void>();

  /** Register a handler for broadcasts of class T. The class must expose
   *  static readonly typeID and static decode(buf): T. */
  on<T>(cls: { typeID: number; decode(buf: Uint8Array): T }, fn: (msg: T) => void): () => void {
    const handler = (raw: Uint8Array) => fn(cls.decode(raw));
    this.handlers.set(cls.typeID, handler);
    return () => { if (this.handlers.get(cls.typeID) === handler) this.handlers.delete(cls.typeID); };
  }

  /** Dispatch one incoming wire event. No-op if no handler is registered for typeID. */
  dispatch(typeID: number, body: Uint8Array): void {
    const fn = this.handlers.get(typeID);
    if (fn) fn(body);
  }
}
