// GENERATED by sdkgen — do not edit.

import { Transport } from "./transport.js";
import { Cube3dDeltaDecoder } from "./delta-decoder.js";
import { TypedDispatcher, CellChange, DebugInfo, OperationError, PlayerEntityAssigned, Pong, ServerConfig, WorldDelta } from "./broadcasts.js";

/** Structural fingerprint of the protocol this SDK was generated from.
 *  Sent at connection setup; the server refuses a mismatch. */
export const SCHEMA_FINGERPRINT = "73007764";

/** Appends the schema fingerprint to a connect URL, preserving any
 *  query the caller already put there. */
function withSchemaFingerprint(url: string): string {
  const u = new URL(url);
  u.searchParams.set("schema", SCHEMA_FINGERPRINT);
  return u.toString();
}

export interface Cube3dClientOptions {
  url: string;
  onOpen?: () => void;
  onClose?: (ev: CloseEvent) => void;
  onError?: (ev: Event) => void;
  /** Fires when the server reports a protocol fingerprint other than the
   *  one this SDK was generated from. The connection-setup gate refuses a
   *  stale CLIENT before the upgrade, so reaching here means the SERVER is
   *  older than this SDK and ignored the fingerprint we sent. */
  onSchemaMismatch?: (serverFingerprint: string, clientFingerprint: string) => void;
}

export class Cube3dClient {
  private transport: Transport;
  private decoder = new Cube3dDeltaDecoder();
  /** Typed broadcast dispatcher — register handlers for AoI-filtered
   *  events emitted by the server's HandleAll[T] machinery. */
  readonly typedEvents = new TypedDispatcher();

  constructor(private options: Cube3dClientOptions) {
    this.transport = new Transport(withSchemaFingerprint(options.url));
  }

  connect(): void {
    this.transport.connect();
    const ws = this.transport.socket!;
    if (this.options.onOpen) ws.onopen = this.options.onOpen;
    if (this.options.onClose) ws.onclose = this.options.onClose;
    if (this.options.onError) ws.onerror = this.options.onError;
    this.typedEvents.on(ServerConfig, (cfg) => {
      const server = (cfg.schemaHash >>> 0).toString(16).padStart(8, "0");
      if (cfg.schemaHash !== 0 && server !== SCHEMA_FINGERPRINT) {
        this.options.onSchemaMismatch?.(server, SCHEMA_FINGERPRINT);
      }
    });
    this.transport.onEvent((payload) => this.handleEvent(payload));
  }

  disconnect(): void { this.transport.close(); }
  get connected(): boolean { return this.transport.connected; }

  /** Raw transport handle for advanced use (operations channel,
   *  custom protocol extensions). Most app code should use the typed
   *  send* / on* methods on this class instead. */
  get rawTransport(): Transport { return this.transport; }

  private handleEvent(payload: Uint8Array): void {
    if (payload.length === 0) return;
    let off = 0;
    while (off + 8 <= payload.length) {
      const view = new DataView(payload.buffer, payload.byteOffset + off, 8);
      const typeID = view.getUint32(0, true);
      const bodyLen = view.getUint32(4, true);
      off += 8;
      if (off + bodyLen > payload.length) {
        console.warn(`typed-event frame: truncated body for typeID=0x${typeID.toString(16)}`);
        return;
      }
      const body = payload.subarray(off, off + bodyLen);
      off += bodyLen;
      this.typedEvents.dispatch(typeID, body);
    }
  }

  /** Send a typed client-input message (mmokit.HandleClient).
   *
   *  msg must be an instance of a class generated into inputs.ts —
   *  exposing static typeID and instance encode(): Uint8Array. The
   *  resulting wire frame is dispatched server-side to the matching
   *  HandleClient[T] handler. */
  send(msg: { encode(): Uint8Array }): void {
    const ctor = msg.constructor as unknown as { typeID: number };
    this.transport.sendClientInput(ctor.typeID, msg.encode());
  }

  /** Subscribe to typed server event mmokit.CellChange (typeID 0x474e8b92). */
  onCellChange(handler: (msg: CellChange) => void): () => void {
    return this.typedEvents.on(CellChange, handler);
  }

  /** Subscribe to typed server event mmokit.DebugInfo (typeID 0x83f2dca1). */
  onDebugInfo(handler: (msg: DebugInfo) => void): () => void {
    return this.typedEvents.on(DebugInfo, handler);
  }

  /** Subscribe to typed server event mmokit.OperationError (typeID 0x3d88aecb). */
  onOperationError(handler: (msg: OperationError) => void): () => void {
    return this.typedEvents.on(OperationError, handler);
  }

  /** Subscribe to typed server event mmokit.PlayerEntityAssigned (typeID 0x02a6f7d8). */
  onPlayerEntityAssigned(handler: (msg: PlayerEntityAssigned) => void): () => void {
    return this.typedEvents.on(PlayerEntityAssigned, handler);
  }

  /** Subscribe to typed server event mmokit.Pong (typeID 0x8527c2fc). */
  onPong(handler: (msg: Pong) => void): () => void {
    return this.typedEvents.on(Pong, handler);
  }

  /** Subscribe to typed server event mmokit.ServerConfig (typeID 0xaa1dd89b). */
  onServerConfig(handler: (msg: ServerConfig) => void): () => void {
    return this.typedEvents.on(ServerConfig, handler);
  }

  /** Subscribe to typed server event mmokit.WorldDelta (typeID 0x065b16f4). */
  onWorldDelta(handler: (msg: WorldDelta) => void): () => void {
    return this.typedEvents.on(WorldDelta, handler);
  }

  /** Clear delta baselines (call on cell change / reconnect). */
  clearBaselines(): void { this.decoder.clear(); }
}
