// GENERATED by sdkgen — do not edit.

// Typed client-input messages. Wire format mirrors the reflect-codec
// layout in pkg/universe/reflect_marshal.go: fields encoded in source
// order, little-endian, no padding. mmokit.Entity → 4-byte NetID.
//
// SpaceClient.send(msg) wraps the encoded body in the [0x00][u32 typeID]
// [u32 bodyLen][body] frame consumed by the server's HandleClient dispatch.

/** Client-input message main.FlyInput (typeID 0xa7dd1e99). */
export class FlyInput {
  static readonly typeID = 0xa7dd1e99;
  forward: number = 0;
  strafe: number = 0;
  lift: number = 0;
  yaw: number = 0;
  pitch: number = 0;

  constructor(init?: Partial<FlyInput>) {
    if (init) Object.assign(this, init);
  }

  encode(): Uint8Array {
    const buf = new Uint8Array(20);
    const dv = new DataView(buf.buffer);
    let off = 0;
    dv.setFloat32(off, this.forward, true); off += 4;
    dv.setFloat32(off, this.strafe, true); off += 4;
    dv.setFloat32(off, this.lift, true); off += 4;
    dv.setFloat32(off, this.yaw, true); off += 4;
    dv.setFloat32(off, this.pitch, true); off += 4;
    return buf;
  }
}

/** Client-input message mmokit.Ping (typeID 0x8c171206). */
export class Ping {
  static readonly typeID = 0x8c171206;
  clientTime: number = 0;

  constructor(init?: Partial<Ping>) {
    if (init) Object.assign(this, init);
  }

  encode(): Uint8Array {
    const buf = new Uint8Array(8);
    const dv = new DataView(buf.buffer);
    let off = 0;
    dv.setBigInt64(off, BigInt(this.clientTime), true); off += 8;
    return buf;
  }
}

/** Client-input message mmokit.ReplicationAck (typeID 0xecfd3f69). */
export class ReplicationAck {
  static readonly typeID = 0xecfd3f69;
  streamEpoch: number = 0;
  seq: number = 0;

  constructor(init?: Partial<ReplicationAck>) {
    if (init) Object.assign(this, init);
  }

  encode(): Uint8Array {
    const buf = new Uint8Array(8);
    const dv = new DataView(buf.buffer);
    let off = 0;
    dv.setUint32(off, this.streamEpoch, true); off += 4;
    dv.setUint32(off, this.seq, true); off += 4;
    return buf;
  }
}

