// GENERATED by sdkgen — do not edit.

import { create, toBinary, fromBinary } from "@bufbuild/protobuf";
import { LoginMsgSchema, MoveTargetMsgSchema } from "@gen/basicpb/basic_pb.js";
import { CellChangeMsgSchema, CellTopologyMsgSchema, LoginRejectedMsgSchema, PingMsgSchema, PongMsgSchema, ServerConfigMsgSchema, SpawnedMsgSchema } from "@gen/enginepb/engine_pb.js";
import type { CellChangeMsg, CellTopologyMsg, LoginRejectedMsg, PongMsg, ServerConfigMsg, SpawnedMsg } from "@gen/enginepb/engine_pb.js";
import { Transport } from "./transport.js";
import { BasicDeltaDecoder } from "./delta-decoder.js";
import type { DeltaWorldUpdate } from "./entities.js";
import { ClientEventSchema, ServerEventSchema, type ServerEvent } from "@gen/enginepb/engine_pb.js";

export interface BasicClientOptions {
  url: string;
  onOpen?: () => void;
  onClose?: (ev: CloseEvent) => void;
  onError?: (ev: Event) => void;
}

export class BasicClient {
  private transport: Transport;
  private decoder = new BasicDeltaDecoder();
  private eventHandlers = new Map<number, ((data: Uint8Array) => void)[]>();
  private rawEventHandlers: ((code: number, data: Uint8Array) => void)[] = [];

  constructor(private options: BasicClientOptions) {
    this.transport = new Transport(options.url);
  }

  connect(): void {
    this.transport.connect();
    const ws = this.transport.socket!;
    if (this.options.onOpen) ws.onopen = this.options.onOpen;
    if (this.options.onClose) ws.onclose = this.options.onClose;
    if (this.options.onError) ws.onerror = this.options.onError;
    this.transport.onEvent((payload) => this.handleEvent(payload));
  }

  disconnect(): void { this.transport.close(); }
  get connected(): boolean { return this.transport.connected; }

  private handleEvent(payload: Uint8Array): void {
    const evt = fromBinary(ServerEventSchema, payload) as ServerEvent;
    const handlers = this.eventHandlers.get(evt.code);
    if (handlers) {
      for (const h of handlers) h(evt.data);
    }
    for (const h of this.rawEventHandlers) h(evt.code, evt.data);
  }

  private on(code: number, handler: (data: Uint8Array) => void): () => void {
    let arr = this.eventHandlers.get(code);
    if (!arr) { arr = []; this.eventHandlers.set(code, arr); }
    arr.push(handler);
    return () => { const idx = arr!.indexOf(handler); if (idx >= 0) arr!.splice(idx, 1); };
  }

  private sendEvent(code: number, data: Uint8Array): void {
    const evt = create(ClientEventSchema, { code, data });
    this.transport.sendEvent(toBinary(ClientEventSchema, evt));
  }

  /** Send PingMsg (code 1). */
  sendPing(params: { clientTime: bigint }): void {
    const data = toBinary(PingMsgSchema, create(PingMsgSchema, params));
    this.sendEvent(1, data);
  }

  /** Send LoginMsg (code 101). */
  sendLogin(params: { name: string }): void {
    const data = toBinary(LoginMsgSchema, create(LoginMsgSchema, params));
    this.sendEvent(101, data);
  }

  /** Send MoveTargetMsg (code 102). */
  sendMoveTarget(params: { targetX: number; targetY: number; sequence: number }): void {
    const data = toBinary(MoveTargetMsgSchema, create(MoveTargetMsgSchema, params));
    this.sendEvent(102, data);
  }

  /** Subscribe to playerSpawned (code 1). */
  onPlayerSpawned(handler: (msg: SpawnedMsg) => void): () => void {
    return this.on(1, (data) => handler(fromBinary(SpawnedMsgSchema, data)));
  }

  /** Subscribe to pong (code 2). */
  onPong(handler: (msg: PongMsg) => void): () => void {
    return this.on(2, (data) => handler(fromBinary(PongMsgSchema, data)));
  }

  /** Subscribe to loginRejected (code 3). */
  onLoginRejected(handler: (msg: LoginRejectedMsg) => void): () => void {
    return this.on(3, (data) => handler(fromBinary(LoginRejectedMsgSchema, data)));
  }

  /** Subscribe to cellChange (code 12). */
  onCellChange(handler: (msg: CellChangeMsg) => void): () => void {
    return this.on(12, (data) => handler(fromBinary(CellChangeMsgSchema, data)));
  }

  /** Subscribe to cellTopology (code 14). */
  onCellTopology(handler: (msg: CellTopologyMsg) => void): () => void {
    return this.on(14, (data) => handler(fromBinary(CellTopologyMsgSchema, data)));
  }

  /** Subscribe to serverConfig (code 15). */
  onServerConfig(handler: (msg: ServerConfigMsg) => void): () => void {
    return this.on(15, (data) => handler(fromBinary(ServerConfigMsgSchema, data)));
  }

  /** Subscribe to deltaWorldUpdate (code 13, binary). */
  onDeltaWorldUpdate(handler: (update: DeltaWorldUpdate) => void): () => void {
    return this.on(13, (data) => handler(this.decoder.decode(data)));
  }

  /** Catch-all for unhandled server events. */
  onRawEvent(handler: (code: number, data: Uint8Array) => void): () => void {
    this.rawEventHandlers.push(handler);
    return () => {
      const idx = this.rawEventHandlers.indexOf(handler);
      if (idx >= 0) this.rawEventHandlers.splice(idx, 1);
    };
  }

  /** Clear delta baselines (call on cell change / reconnect). */
  clearBaselines(): void { this.decoder.clear(); }
}
