// GENERATED by sdkgen — do not edit.

import { Transport } from "./transport.js";
import { BasicDeltaDecoder } from "./delta-decoder.js";
import { TypedDispatcher, ChatBannedEvent, ChatChannelGoneEvent, ChatChannelUpdatedEvent, ChatChannelsHydratedEvent, ChatDMEvent, ChatKickedEvent, ChatMemberJoinedEvent, ChatMemberLeftEvent, ChatMemberRoleChangedEvent, ChatMessageDeletedEvent, ChatMessageEvent, ChatMutedEvent, ChatRateLimitedEvent, ChatUnmutedEvent, CellChange, DebugInfo, OperationError, PlayerEntityAssigned, Pong, ServerConfig, WorldDelta } from "./broadcasts.js";
import { AuthChangePasswordRequest, AuthChangePasswordResponse, AuthLoginRequest, AuthLoginResponse, AuthLogoutRequest, AuthLogoutResponse, AuthRegisterRequest, AuthRegisterResponse, AuthValidateTokenRequest, AuthValidateTokenResponse, ChatAddMemberRequest, ChatAddMemberResponse, ChatBanRequest, ChatBanResponse, ChatBroadcastRequest, ChatBroadcastResponse, ChatBulkSetMembersRequest, ChatBulkSetMembersResponse, ChatCreateRequest, ChatCreateResponse, ChatDeleteMessageRequest, ChatDeleteMessageResponse, ChatJoinRequest, ChatJoinResponse, ChatKickRequest, ChatKickResponse, ChatLeaveRequest, ChatLeaveResponse, ChatListChannelsRequest, ChatListChannelsResponse, ChatListMembersRequest, ChatListMembersResponse, ChatMuteUserRequest, ChatMuteUserResponse, ChatRegisterChannelRequest, ChatRegisterChannelResponse, ChatRemoveMemberRequest, ChatRemoveMemberResponse, ChatRenameChannelRequest, ChatRenameChannelResponse, ChatSendDMRequest, ChatSendDMResponse, ChatSendRequest, ChatSendResponse, ChatSetMemberRoleRequest, ChatSetMemberRoleResponse, ChatSetSlowModeRequest, ChatSetSlowModeResponse, ChatSetTopicRequest, ChatSetTopicResponse, ChatUnbanRequest, ChatUnbanResponse, ChatUnmuteUserRequest, ChatUnmuteUserResponse, ChatUnregisterChannelRequest, ChatUnregisterChannelResponse, EchoFetchRequest, EchoFetchResponse, EchoPersistRequest, EchoPersistResponse, EchoPingRequest, EchoPingResponse } from "./operations.js";

/** Structural fingerprint of the protocol this SDK was generated from.
 *  Sent at connection setup; the server refuses a mismatch. */
export const SCHEMA_FINGERPRINT = "7d803a3c";

/** Appends the schema fingerprint to a connect URL, preserving any
 *  query the caller already put there. */
function withSchemaFingerprint(url: string): string {
  const u = new URL(url);
  u.searchParams.set("schema", SCHEMA_FINGERPRINT);
  return u.toString();
}

export interface BasicClientOptions {
  url: string;
  onOpen?: () => void;
  onClose?: (ev: CloseEvent) => void;
  onError?: (ev: Event) => void;
  /** Fires when the server reports a protocol fingerprint other than the
   *  one this SDK was generated from. The connection-setup gate refuses a
   *  stale CLIENT before the upgrade, so reaching here means the SERVER is
   *  older than this SDK and ignored the fingerprint we sent. */
  onSchemaMismatch?: (serverFingerprint: string, clientFingerprint: string) => void;
}

export class BasicClient {
  private transport: Transport;
  private decoder = new BasicDeltaDecoder();
  /** Typed broadcast dispatcher — register handlers for AoI-filtered
   *  events emitted by the server's HandleAll[T] machinery. */
  readonly typedEvents = new TypedDispatcher();
  private pendingTypedOps = new Map<bigint, { resolve: (msg: any) => void; reject: (err: Error) => void; resCls: { typeID: number; decode(buf: Uint8Array): any } }>();
  private nextTypedOpRequestID: bigint = 1n;

  constructor(private options: BasicClientOptions) {
    this.transport = new Transport(withSchemaFingerprint(options.url));
  }

  connect(): void {
    this.transport.connect();
    const ws = this.transport.socket!;
    if (this.options.onOpen) ws.onopen = this.options.onOpen;
    if (this.options.onClose) ws.onclose = this.options.onClose;
    if (this.options.onError) ws.onerror = this.options.onError;
    this.typedEvents.on(ServerConfig, (cfg) => {
      const server = (cfg.schemaHash >>> 0).toString(16).padStart(8, "0");
      if (cfg.schemaHash !== 0 && server !== SCHEMA_FINGERPRINT) {
        this.options.onSchemaMismatch?.(server, SCHEMA_FINGERPRINT);
      }
    });
    this.transport.onEvent((payload) => this.handleEvent(payload));
    this.transport.onOperation((payload) => this.handleOperation(payload));
  }

  disconnect(): void {
    // Reject any pending operations.
    for (const pending of this.pendingTypedOps.values()) {
      pending.reject(new Error("client disconnected"));
    }
    this.pendingTypedOps.clear();
    this.transport.close();
  }
  get connected(): boolean { return this.transport.connected; }

  /** Raw transport handle for advanced use (operations channel,
   *  custom protocol extensions). Most app code should use the typed
   *  send* / on* methods on this class instead. */
  get rawTransport(): Transport { return this.transport; }

  private handleEvent(payload: Uint8Array): void {
    if (payload.length === 0) return;
    let off = 0;
    while (off + 8 <= payload.length) {
      const view = new DataView(payload.buffer, payload.byteOffset + off, 8);
      const typeID = view.getUint32(0, true);
      const bodyLen = view.getUint32(4, true);
      off += 8;
      if (off + bodyLen > payload.length) {
        console.warn(`typed-event frame: truncated body for typeID=0x${typeID.toString(16)}`);
        return;
      }
      const body = payload.subarray(off, off + bodyLen);
      off += bodyLen;
      this.typedEvents.dispatch(typeID, body);
    }
  }

  /** Send a typed client-input message (mmokit.HandleClient).
   *
   *  msg must be an instance of a class generated into inputs.ts —
   *  exposing static typeID and instance encode(): Uint8Array. The
   *  resulting wire frame is dispatched server-side to the matching
   *  HandleClient[T] handler. */
  send(msg: { encode(): Uint8Array }): void {
    const ctor = msg.constructor as unknown as { typeID: number };
    this.transport.sendClientInput(ctor.typeID, msg.encode());
  }

  /** Subscribe to typed server event chat.ChatBannedEvent (typeID 0xf9fe667f). */
  onChatBannedEvent(handler: (msg: ChatBannedEvent) => void): () => void {
    return this.typedEvents.on(ChatBannedEvent, handler);
  }

  /** Subscribe to typed server event chat.ChatChannelGoneEvent (typeID 0x74d67ad5). */
  onChatChannelGoneEvent(handler: (msg: ChatChannelGoneEvent) => void): () => void {
    return this.typedEvents.on(ChatChannelGoneEvent, handler);
  }

  /** Subscribe to typed server event chat.ChatChannelUpdatedEvent (typeID 0x03481835). */
  onChatChannelUpdatedEvent(handler: (msg: ChatChannelUpdatedEvent) => void): () => void {
    return this.typedEvents.on(ChatChannelUpdatedEvent, handler);
  }

  /** Subscribe to typed server event chat.ChatChannelsHydratedEvent (typeID 0xa70de1b8). */
  onChatChannelsHydratedEvent(handler: (msg: ChatChannelsHydratedEvent) => void): () => void {
    return this.typedEvents.on(ChatChannelsHydratedEvent, handler);
  }

  /** Subscribe to typed server event chat.ChatDMEvent (typeID 0x62aa45c2). */
  onChatDMEvent(handler: (msg: ChatDMEvent) => void): () => void {
    return this.typedEvents.on(ChatDMEvent, handler);
  }

  /** Subscribe to typed server event chat.ChatKickedEvent (typeID 0x87e2fcc6). */
  onChatKickedEvent(handler: (msg: ChatKickedEvent) => void): () => void {
    return this.typedEvents.on(ChatKickedEvent, handler);
  }

  /** Subscribe to typed server event chat.ChatMemberJoinedEvent (typeID 0x2ccc8a4a). */
  onChatMemberJoinedEvent(handler: (msg: ChatMemberJoinedEvent) => void): () => void {
    return this.typedEvents.on(ChatMemberJoinedEvent, handler);
  }

  /** Subscribe to typed server event chat.ChatMemberLeftEvent (typeID 0xf1bee142). */
  onChatMemberLeftEvent(handler: (msg: ChatMemberLeftEvent) => void): () => void {
    return this.typedEvents.on(ChatMemberLeftEvent, handler);
  }

  /** Subscribe to typed server event chat.ChatMemberRoleChangedEvent (typeID 0x1da61d0b). */
  onChatMemberRoleChangedEvent(handler: (msg: ChatMemberRoleChangedEvent) => void): () => void {
    return this.typedEvents.on(ChatMemberRoleChangedEvent, handler);
  }

  /** Subscribe to typed server event chat.ChatMessageDeletedEvent (typeID 0x8b8245df). */
  onChatMessageDeletedEvent(handler: (msg: ChatMessageDeletedEvent) => void): () => void {
    return this.typedEvents.on(ChatMessageDeletedEvent, handler);
  }

  /** Subscribe to typed server event chat.ChatMessageEvent (typeID 0xbe1d1360). */
  onChatMessageEvent(handler: (msg: ChatMessageEvent) => void): () => void {
    return this.typedEvents.on(ChatMessageEvent, handler);
  }

  /** Subscribe to typed server event chat.ChatMutedEvent (typeID 0xfd6c9d54). */
  onChatMutedEvent(handler: (msg: ChatMutedEvent) => void): () => void {
    return this.typedEvents.on(ChatMutedEvent, handler);
  }

  /** Subscribe to typed server event chat.ChatRateLimitedEvent (typeID 0x48eeebed). */
  onChatRateLimitedEvent(handler: (msg: ChatRateLimitedEvent) => void): () => void {
    return this.typedEvents.on(ChatRateLimitedEvent, handler);
  }

  /** Subscribe to typed server event chat.ChatUnmutedEvent (typeID 0xf8dbe7d3). */
  onChatUnmutedEvent(handler: (msg: ChatUnmutedEvent) => void): () => void {
    return this.typedEvents.on(ChatUnmutedEvent, handler);
  }

  /** Subscribe to typed server event mmokit.CellChange (typeID 0x474e8b92). */
  onCellChange(handler: (msg: CellChange) => void): () => void {
    return this.typedEvents.on(CellChange, handler);
  }

  /** Subscribe to typed server event mmokit.DebugInfo (typeID 0x83f2dca1). */
  onDebugInfo(handler: (msg: DebugInfo) => void): () => void {
    return this.typedEvents.on(DebugInfo, handler);
  }

  /** Subscribe to typed server event mmokit.OperationError (typeID 0x3d88aecb). */
  onOperationError(handler: (msg: OperationError) => void): () => void {
    return this.typedEvents.on(OperationError, handler);
  }

  /** Subscribe to typed server event mmokit.PlayerEntityAssigned (typeID 0x02a6f7d8). */
  onPlayerEntityAssigned(handler: (msg: PlayerEntityAssigned) => void): () => void {
    return this.typedEvents.on(PlayerEntityAssigned, handler);
  }

  /** Subscribe to typed server event mmokit.Pong (typeID 0x8527c2fc). */
  onPong(handler: (msg: Pong) => void): () => void {
    return this.typedEvents.on(Pong, handler);
  }

  /** Subscribe to typed server event mmokit.ServerConfig (typeID 0xaa1dd89b). */
  onServerConfig(handler: (msg: ServerConfig) => void): () => void {
    return this.typedEvents.on(ServerConfig, handler);
  }

  /** Subscribe to typed server event mmokit.WorldDelta (typeID 0x065b16f4). */
  onWorldDelta(handler: (msg: WorldDelta) => void): () => void {
    return this.typedEvents.on(WorldDelta, handler);
  }

  private handleOperation(payload: Uint8Array): void {
    if (payload.length === 0) return;
      // Typed-op response: [typeID:u32 LE][request_id:u64 LE][bodyLen:u32 LE][body].
      if (payload.length < 16) {
        console.warn(`typed-op frame: truncated header (len=${payload.length})`);
        return;
      }
      const opDV = new DataView(payload.buffer, payload.byteOffset, payload.byteLength);
      const resTypeID = opDV.getUint32(0, true);
      const reqID = opDV.getBigUint64(4, true);
      const bodyLen = opDV.getUint32(12, true);
      if (16 + bodyLen > payload.length) {
        console.warn(`typed-op frame: truncated body for typeID=0x${resTypeID.toString(16)}`);
        return;
      }
      const body = payload.subarray(16, 16 + bodyLen);
      const pending = this.pendingTypedOps.get(reqID);
      if (!pending) {
        console.warn(`typed-op response for unknown request_id ${reqID}`);
        return;
      }
      this.pendingTypedOps.delete(reqID);
      if (resTypeID === OperationError.typeID) {
        const err = OperationError.decode(body);
        pending.reject(new Error(`OperationError code=${err.code}: ${err.message}`));
        return;
      }
      pending.resolve(pending.resCls.decode(body));
    return;
  }

  /** Private helper: encode + send a typed-op request, return a
   *  Promise that resolves with the decoded Response. */
  private callOp<Req extends { encode(): Uint8Array }, Res>(
    req: Req,
    resCls: { typeID: number; decode(buf: Uint8Array): Res }
  ): Promise<Res> {
    const reqID = this.nextTypedOpRequestID++;
    const reqTypeID = (req.constructor as unknown as { typeID: number }).typeID;
    const body = req.encode();
    const frame = new Uint8Array(1 + 4 + 8 + 4 + body.length);
    const dv = new DataView(frame.buffer);
    frame[0] = 0x01;
    dv.setUint32(1, reqTypeID, true);
    dv.setBigUint64(5, reqID, true);
    dv.setUint32(13, body.length, true);
    frame.set(body, 17);
    return new Promise<Res>((resolve, reject) => {
      this.pendingTypedOps.set(reqID, { resolve, reject, resCls });
      this.transport.sendRaw(frame);
    });
  }

  /** Typed op auth.AuthChangePasswordRequest → auth.AuthChangePasswordResponse (kind=gateway-local). */
  authChangePassword(req: AuthChangePasswordRequest): Promise<AuthChangePasswordResponse> {
    return this.callOp<AuthChangePasswordRequest, AuthChangePasswordResponse>(req, AuthChangePasswordResponse);
  }

  /** Typed op auth.AuthLoginRequest → auth.AuthLoginResponse (kind=gateway-local). */
  authLogin(req: AuthLoginRequest): Promise<AuthLoginResponse> {
    return this.callOp<AuthLoginRequest, AuthLoginResponse>(req, AuthLoginResponse);
  }

  /** Typed op auth.AuthLogoutRequest → auth.AuthLogoutResponse (kind=gateway-local). */
  authLogout(req: AuthLogoutRequest): Promise<AuthLogoutResponse> {
    return this.callOp<AuthLogoutRequest, AuthLogoutResponse>(req, AuthLogoutResponse);
  }

  /** Typed op auth.AuthRegisterRequest → auth.AuthRegisterResponse (kind=gateway-local). */
  authRegister(req: AuthRegisterRequest): Promise<AuthRegisterResponse> {
    return this.callOp<AuthRegisterRequest, AuthRegisterResponse>(req, AuthRegisterResponse);
  }

  /** Typed op auth.AuthValidateTokenRequest → auth.AuthValidateTokenResponse (kind=gateway-local). */
  authValidateToken(req: AuthValidateTokenRequest): Promise<AuthValidateTokenResponse> {
    return this.callOp<AuthValidateTokenRequest, AuthValidateTokenResponse>(req, AuthValidateTokenResponse);
  }

  /** Typed op chat.ChatAddMemberRequest → chat.ChatAddMemberResponse (kind=gateway-local). */
  chatAddMember(req: ChatAddMemberRequest): Promise<ChatAddMemberResponse> {
    return this.callOp<ChatAddMemberRequest, ChatAddMemberResponse>(req, ChatAddMemberResponse);
  }

  /** Typed op chat.ChatBanRequest → chat.ChatBanResponse (kind=gateway-local). */
  chatBan(req: ChatBanRequest): Promise<ChatBanResponse> {
    return this.callOp<ChatBanRequest, ChatBanResponse>(req, ChatBanResponse);
  }

  /** Typed op chat.ChatBroadcastRequest → chat.ChatBroadcastResponse (kind=gateway-local). */
  chatBroadcast(req: ChatBroadcastRequest): Promise<ChatBroadcastResponse> {
    return this.callOp<ChatBroadcastRequest, ChatBroadcastResponse>(req, ChatBroadcastResponse);
  }

  /** Typed op chat.ChatBulkSetMembersRequest → chat.ChatBulkSetMembersResponse (kind=gateway-local). */
  chatBulkSetMembers(req: ChatBulkSetMembersRequest): Promise<ChatBulkSetMembersResponse> {
    return this.callOp<ChatBulkSetMembersRequest, ChatBulkSetMembersResponse>(req, ChatBulkSetMembersResponse);
  }

  /** Typed op chat.ChatCreateRequest → chat.ChatCreateResponse (kind=gateway-local). */
  chatCreate(req: ChatCreateRequest): Promise<ChatCreateResponse> {
    return this.callOp<ChatCreateRequest, ChatCreateResponse>(req, ChatCreateResponse);
  }

  /** Typed op chat.ChatDeleteMessageRequest → chat.ChatDeleteMessageResponse (kind=gateway-local). */
  chatDeleteMessage(req: ChatDeleteMessageRequest): Promise<ChatDeleteMessageResponse> {
    return this.callOp<ChatDeleteMessageRequest, ChatDeleteMessageResponse>(req, ChatDeleteMessageResponse);
  }

  /** Typed op chat.ChatJoinRequest → chat.ChatJoinResponse (kind=gateway-local). */
  chatJoin(req: ChatJoinRequest): Promise<ChatJoinResponse> {
    return this.callOp<ChatJoinRequest, ChatJoinResponse>(req, ChatJoinResponse);
  }

  /** Typed op chat.ChatKickRequest → chat.ChatKickResponse (kind=gateway-local). */
  chatKick(req: ChatKickRequest): Promise<ChatKickResponse> {
    return this.callOp<ChatKickRequest, ChatKickResponse>(req, ChatKickResponse);
  }

  /** Typed op chat.ChatLeaveRequest → chat.ChatLeaveResponse (kind=gateway-local). */
  chatLeave(req: ChatLeaveRequest): Promise<ChatLeaveResponse> {
    return this.callOp<ChatLeaveRequest, ChatLeaveResponse>(req, ChatLeaveResponse);
  }

  /** Typed op chat.ChatListChannelsRequest → chat.ChatListChannelsResponse (kind=gateway-local). */
  chatListChannels(req: ChatListChannelsRequest): Promise<ChatListChannelsResponse> {
    return this.callOp<ChatListChannelsRequest, ChatListChannelsResponse>(req, ChatListChannelsResponse);
  }

  /** Typed op chat.ChatListMembersRequest → chat.ChatListMembersResponse (kind=gateway-local). */
  chatListMembers(req: ChatListMembersRequest): Promise<ChatListMembersResponse> {
    return this.callOp<ChatListMembersRequest, ChatListMembersResponse>(req, ChatListMembersResponse);
  }

  /** Typed op chat.ChatMuteUserRequest → chat.ChatMuteUserResponse (kind=gateway-local). */
  chatMuteUser(req: ChatMuteUserRequest): Promise<ChatMuteUserResponse> {
    return this.callOp<ChatMuteUserRequest, ChatMuteUserResponse>(req, ChatMuteUserResponse);
  }

  /** Typed op chat.ChatRegisterChannelRequest → chat.ChatRegisterChannelResponse (kind=gateway-local). */
  chatRegisterChannel(req: ChatRegisterChannelRequest): Promise<ChatRegisterChannelResponse> {
    return this.callOp<ChatRegisterChannelRequest, ChatRegisterChannelResponse>(req, ChatRegisterChannelResponse);
  }

  /** Typed op chat.ChatRemoveMemberRequest → chat.ChatRemoveMemberResponse (kind=gateway-local). */
  chatRemoveMember(req: ChatRemoveMemberRequest): Promise<ChatRemoveMemberResponse> {
    return this.callOp<ChatRemoveMemberRequest, ChatRemoveMemberResponse>(req, ChatRemoveMemberResponse);
  }

  /** Typed op chat.ChatRenameChannelRequest → chat.ChatRenameChannelResponse (kind=gateway-local). */
  chatRenameChannel(req: ChatRenameChannelRequest): Promise<ChatRenameChannelResponse> {
    return this.callOp<ChatRenameChannelRequest, ChatRenameChannelResponse>(req, ChatRenameChannelResponse);
  }

  /** Typed op chat.ChatSendDMRequest → chat.ChatSendDMResponse (kind=gateway-local). */
  chatSendDM(req: ChatSendDMRequest): Promise<ChatSendDMResponse> {
    return this.callOp<ChatSendDMRequest, ChatSendDMResponse>(req, ChatSendDMResponse);
  }

  /** Typed op chat.ChatSendRequest → chat.ChatSendResponse (kind=gateway-local). */
  chatSend(req: ChatSendRequest): Promise<ChatSendResponse> {
    return this.callOp<ChatSendRequest, ChatSendResponse>(req, ChatSendResponse);
  }

  /** Typed op chat.ChatSetMemberRoleRequest → chat.ChatSetMemberRoleResponse (kind=gateway-local). */
  chatSetMemberRole(req: ChatSetMemberRoleRequest): Promise<ChatSetMemberRoleResponse> {
    return this.callOp<ChatSetMemberRoleRequest, ChatSetMemberRoleResponse>(req, ChatSetMemberRoleResponse);
  }

  /** Typed op chat.ChatSetSlowModeRequest → chat.ChatSetSlowModeResponse (kind=gateway-local). */
  chatSetSlowMode(req: ChatSetSlowModeRequest): Promise<ChatSetSlowModeResponse> {
    return this.callOp<ChatSetSlowModeRequest, ChatSetSlowModeResponse>(req, ChatSetSlowModeResponse);
  }

  /** Typed op chat.ChatSetTopicRequest → chat.ChatSetTopicResponse (kind=gateway-local). */
  chatSetTopic(req: ChatSetTopicRequest): Promise<ChatSetTopicResponse> {
    return this.callOp<ChatSetTopicRequest, ChatSetTopicResponse>(req, ChatSetTopicResponse);
  }

  /** Typed op chat.ChatUnbanRequest → chat.ChatUnbanResponse (kind=gateway-local). */
  chatUnban(req: ChatUnbanRequest): Promise<ChatUnbanResponse> {
    return this.callOp<ChatUnbanRequest, ChatUnbanResponse>(req, ChatUnbanResponse);
  }

  /** Typed op chat.ChatUnmuteUserRequest → chat.ChatUnmuteUserResponse (kind=gateway-local). */
  chatUnmuteUser(req: ChatUnmuteUserRequest): Promise<ChatUnmuteUserResponse> {
    return this.callOp<ChatUnmuteUserRequest, ChatUnmuteUserResponse>(req, ChatUnmuteUserResponse);
  }

  /** Typed op chat.ChatUnregisterChannelRequest → chat.ChatUnregisterChannelResponse (kind=gateway-local). */
  chatUnregisterChannel(req: ChatUnregisterChannelRequest): Promise<ChatUnregisterChannelResponse> {
    return this.callOp<ChatUnregisterChannelRequest, ChatUnregisterChannelResponse>(req, ChatUnregisterChannelResponse);
  }

  /** Typed op echo.EchoFetchRequest → echo.EchoFetchResponse (kind=gateway-local). */
  echoFetch(req: EchoFetchRequest): Promise<EchoFetchResponse> {
    return this.callOp<EchoFetchRequest, EchoFetchResponse>(req, EchoFetchResponse);
  }

  /** Typed op echo.EchoPersistRequest → echo.EchoPersistResponse (kind=gateway-local). */
  echoPersist(req: EchoPersistRequest): Promise<EchoPersistResponse> {
    return this.callOp<EchoPersistRequest, EchoPersistResponse>(req, EchoPersistResponse);
  }

  /** Typed op echo.EchoPingRequest → echo.EchoPingResponse (kind=gateway-local). */
  echoPing(req: EchoPingRequest): Promise<EchoPingResponse> {
    return this.callOp<EchoPingRequest, EchoPingResponse>(req, EchoPingResponse);
  }

  /** Clear delta baselines (call on cell change / reconnect). */
  clearBaselines(): void { this.decoder.clear(); }
}
