// GENERATED by sdkgen — do not edit.

import {
  readFloat32, readInt16, readUint16, readUint32,
  unAngle, unNorm, unVel,
  decodeFrameHeader, decodeFullEntry, decodeDeltaEntry, decodeRemovedIDs,
  applyDelta, BaselineStore,
  decodeLengthPrefixedStringU8,
} from "./_core/delta-decoder-core.js";
import type { PlayerEntity, AnyEntity, DeltaWorldUpdate } from "./entities.js";

const PLAYERENTITY_FIELD_SIZES = [4, 4, 2, 2, 2, 2, 2, 1, 1, 4];
const PLAYERENTITY_HAS_VAR_TAIL = false;

function decodePlayerEntitySnapshot(snap: Uint8Array, initial: Uint8Array | null, existing?: PlayerEntity): PlayerEntity {
  let o = 0;
  const worldX = readFloat32(snap, o); o += 4;
  const worldY = readFloat32(snap, o); o += 4;
  const velX = unVel(readInt16(snap, o), 2000); o += 2;
  const velY = unVel(readInt16(snap, o), 2000); o += 2;
  const radius = unVel(readInt16(snap, o), 500); o += 2;
  const width = unVel(readInt16(snap, o), 500); o += 2;
  const height = unVel(readInt16(snap, o), 500); o += 2;
  const meshState = snap[o]; o += 1;
  const ownerNode = snap[o]; o += 1;
  const aoIRadius = readFloat32(snap, o); o += 4;
  const name = initial ? decodeLengthPrefixedStringU8(initial) : (existing?.name ?? "");
  return { netID: 0, entityType: 1, worldX, worldY, velX, velY, radius, width, height, meshState, ownerNode, name, aoIRadius };
}

export class BasicDeltaDecoder {
  private baselines = new BaselineStore<{ type: number; name?: string }>();

  clear(): void { this.baselines.clear(); }

  decode(data: Uint8Array): DeltaWorldUpdate {
    const { header, offset: pos0 } = decodeFrameHeader(data, 0);
    let pos = pos0;

    const entered: AnyEntity[] = [];
    const updated: AnyEntity[] = [];

    for (let i = 0; i < header.fullCount; i++) {
      const { entry, offset: next } = decodeFullEntry(data, pos);
      pos = next;
      this.baselines.set(entry.netID, entry.snapshot, { type: entry.entityType });
      const entity = this.decodeEntity(entry.entityType, entry.snapshot, entry.initialData, entry.netID);
      if (entity) entered.push(entity);
    }

    for (let i = 0; i < header.deltaCount; i++) {
      const { entry, offset: next } = decodeDeltaEntry(data, pos);
      pos = next;
      const bl = this.baselines.get(entry.netID);
      if (!bl) continue;
      const fieldSizes = this.fieldSizesFor(entry.entityType);
      const hasVarTail = this.hasVarTailFor(entry.entityType);
      const newSnap = applyDelta(fieldSizes, hasVarTail, bl.snapshot, entry.deltaData);
      this.baselines.set(entry.netID, newSnap, bl.meta);
      const entity = this.decodeEntity(entry.entityType, newSnap, null, entry.netID);
      if (entity) updated.push(entity);
    }

    const { ids: removed, offset: pos2 } = decodeRemovedIDs(data, pos, header.removedCount);
    const { ids: exited } = decodeRemovedIDs(data, pos2, header.exitedCount);

    for (const id of removed) this.baselines.delete(id);
    for (const id of exited) this.baselines.delete(id);

    return {
      tick: header.tick, seq: header.seq,
      viewerX: header.viewerX, viewerY: header.viewerY,
      entered, updated, removed, exited,
    };
  }

  private decodeEntity(type_: number, snap: Uint8Array, initial: Uint8Array | null, netID: number): AnyEntity | null {
    switch (type_) {
      case 1: { const e = decodePlayerEntitySnapshot(snap, initial); e.netID = netID; return e; }
      default: return null;
    }
  }

  private fieldSizesFor(type_: number): number[] {
    switch (type_) {
      case 1: return PLAYERENTITY_FIELD_SIZES;
      default: return [];
    }
  }

  private hasVarTailFor(type_: number): boolean {
    switch (type_) {
      case 1: return PLAYERENTITY_HAS_VAR_TAIL;
      default: return false;
    }
  }
}
