// GENERATED by sdkgen — do not edit.

/** Entity kind 1. */
export interface PlayerEntity {
  netID: number;
  entityType: 1;
  worldX: number;
  worldY: number;
  velX: number;
  velY: number;
  radius: number;
  state: number;
  ownerNode: number;
  name: string;
}

export type AnyEntity = PlayerEntity;

export interface DeltaWorldUpdate {
  tick: number;
  seq: number;
  viewerX: number;
  viewerY: number;
  entered: AnyEntity[];
  updated: AnyEntity[];
  removed: number[];
  exited: number[];
}
