// GENERATED by sdkgen — do not edit.

/** Entity kind 1. */
export interface PlayerEntity {
  netID: number;
  /** Authority generation for this netID (uint32 serial). */
  authorityEpoch: number;
  entityType: 1;
  /**
   * Cluster-clock stamp (Unix ms) from the authoritative producer at
   * the moment this state was emitted. Preserves the producer's
   * timeline through any relay hops. Used as the per-entity time-base
   * for snapshot interpolation.
   */
  producedAtMs: number;
  worldX: number;
  worldY: number;
  velX: number;
  velY: number;
  radius: number;
  width: number;
  height: number;
  r: number;
  g: number;
  b: number;
  name: string;
}

/** Entity kind 2. */
export interface BotEntity {
  netID: number;
  /** Authority generation for this netID (uint32 serial). */
  authorityEpoch: number;
  entityType: 2;
  /**
   * Cluster-clock stamp (Unix ms) from the authoritative producer at
   * the moment this state was emitted. Preserves the producer's
   * timeline through any relay hops. Used as the per-entity time-base
   * for snapshot interpolation.
   */
  producedAtMs: number;
  worldX: number;
  worldY: number;
  velX: number;
  velY: number;
  radius: number;
  width: number;
  height: number;
  r: number;
  g: number;
  b: number;
  name: string;
}

export type AnyEntity = PlayerEntity | BotEntity;

export interface DeltaWorldUpdate {
  tick: number;
  seq: number;
  /**
   * Set when the server's ReplicationSystem sent this frame as the
   * first frame to this connection — i.e. on initial login or on every
   * cross-cell handoff. The SDK decoder clears its per-entity baselines
   * before applying the frame; clients should treat the frame's Entered
   * list as the authoritative current entity set and drop any stale
   * entities they retained from before. Topology-transparent: clients
   * never learn about cells, authority transfers, or server boundaries.
   */
  freshSnapshot: boolean;
  /** True when the decoder adopted a new explicit stream generation. */
  streamChanged: boolean;
  /** Input sequence causally reflected by this frame; null on legacy/unsequenced streams. */
  processedInputSeq: number | null;
  entered: AnyEntity[];
  updated: AnyEntity[];
  removed: number[];
  exited: number[];
}
