// GENERATED by sdkgen — do not edit.

// Entity-kind wire bytes. The values match the kindID arg passed to
// mmokit.RegisterKind[T] on the Go side; the names match the second
// arg (display name) of the same call.

export const EntityType = {
    Player: 1,
    Bot: 2,
} as const;

export type EntityTypeValue = typeof EntityType[keyof typeof EntityType];
