// GENERATED by sdkgen — do not edit.

import { create, toBinary, fromBinary } from "@bufbuild/protobuf";
import { CellChangeMsgSchema, LoginMsgSchema, PingMsgSchema, ServerConfigMsgSchema } from "@gen/enginepb/engine_pb.js";
import { MarketBrowseRequestSchema, MarketCancelOrderRequestSchema, MarketCreateOrderRequestSchema, MarketInstantTradeRequestSchema, MarketMyOrdersRequestSchema, MarketMyOrdersResponseSchema, MarketOrderBookResponseSchema, MarketOrderResultResponseSchema, WorldUpdateMsgSchema } from "@gen/gamepb/game_pb.js";
import type { CellChangeMsg, ServerConfigMsg } from "@gen/enginepb/engine_pb.js";
import type { MarketMyOrdersResponse, MarketOrderBookResponse, MarketOrderResultResponse, WorldUpdateMsg } from "@gen/gamepb/game_pb.js";
import { Transport } from "./transport.js";
import { SpaceDeltaDecoder } from "./delta-decoder.js";
import type { DeltaWorldUpdate } from "./entities.js";
import { TypedDispatcher, BankContents, CurrencyUpdate, Docked, DockingState, EquipResult, MapData, PlayerDied, PlayerOwnState, PlayerSpawned, TransferResult, DebugInfo, LoginRejected, Pong, WorldDelta } from "./broadcasts.js";
import { ClientEventSchema, ServerEventSchema, type ServerEvent, OperationRequestSchema, OperationResponseSchema, type OperationResponse } from "@gen/enginepb/engine_pb.js";

export interface SpaceClientOptions {
  url: string;
  onOpen?: () => void;
  onClose?: (ev: CloseEvent) => void;
  onError?: (ev: Event) => void;
}

export class SpaceClient {
  private transport: Transport;
  private decoder = new SpaceDeltaDecoder();
  private eventHandlers = new Map<number, ((data: Uint8Array) => void)[]>();
  private rawEventHandlers: ((code: number, data: Uint8Array) => void)[] = [];
  /** Typed broadcast dispatcher — register handlers for AoI-filtered
   *  events emitted by the server's HandleAll[T] machinery. */
  readonly typedEvents = new TypedDispatcher();
  private pendingOps = new Map<number, { resolve: (data: Uint8Array) => void; reject: (err: Error) => void }>();
  private pushHandlers = new Map<number, ((data: Uint8Array) => void)[]>();
  private nextRequestID = 1;

  constructor(private options: SpaceClientOptions) {
    this.transport = new Transport(options.url);
  }

  connect(): void {
    this.transport.connect();
    const ws = this.transport.socket!;
    if (this.options.onOpen) ws.onopen = this.options.onOpen;
    if (this.options.onClose) ws.onclose = this.options.onClose;
    if (this.options.onError) ws.onerror = this.options.onError;
    this.transport.onEvent((payload) => this.handleEvent(payload));
    this.transport.onOperation((payload) => this.handleOperation(payload));
  }

  disconnect(): void {
    // Reject any pending operations.
    for (const pending of this.pendingOps.values()) {
      pending.reject(new Error("client disconnected"));
    }
    this.pendingOps.clear();
    this.transport.close();
  }
  get connected(): boolean { return this.transport.connected; }

  /** Raw transport handle for advanced use (operations channel,
   *  custom protocol extensions). Most app code should use the typed
   *  send* / on* methods on this class instead. */
  get rawTransport(): Transport { return this.transport; }

  private handleEvent(payload: Uint8Array): void {
    if (payload.length === 0) return;
    if (payload[0] !== 0x08) {
      // Typed-event frame: repeated [typeID:u32 LE][body_len:u32 LE][body].
      let off = 0;
      while (off + 8 <= payload.length) {
        const view = new DataView(payload.buffer, payload.byteOffset + off, 8);
        const typeID = view.getUint32(0, true);
        const bodyLen = view.getUint32(4, true);
        off += 8;
        if (off + bodyLen > payload.length) {
          console.warn(`typed-event frame: truncated body for typeID=0x${typeID.toString(16)}`);
          return;
        }
        const body = payload.subarray(off, off + bodyLen);
        off += bodyLen;
        this.typedEvents.dispatch(typeID, body);
      }
      return;
    }
    let evt: ServerEvent;
    try {
      evt = fromBinary(ServerEventSchema, payload) as ServerEvent;
    } catch (err) {
      console.warn(`legacy ServerEvent decode failed (first byte 0x${payload[0].toString(16)}); this might be a typed-event frame whose typeID's low byte is 0x08 — rename the offending Go type. err=${err}`);
      return;
    }
    const handlers = this.eventHandlers.get(evt.code);
    if (handlers) {
      for (const h of handlers) h(evt.data);
    }
    for (const h of this.rawEventHandlers) h(evt.code, evt.data);
  }

  private on(code: number, handler: (data: Uint8Array) => void): () => void {
    let arr = this.eventHandlers.get(code);
    if (!arr) { arr = []; this.eventHandlers.set(code, arr); }
    arr.push(handler);
    return () => { const idx = arr!.indexOf(handler); if (idx >= 0) arr!.splice(idx, 1); };
  }

  private sendEvent(code: number, data: Uint8Array): void {
    const evt = create(ClientEventSchema, { code, data });
    this.transport.sendEvent(toBinary(ClientEventSchema, evt));
  }

  /** Send a typed client-input message (mmokit.HandleClient).
   *
   *  msg must be an instance of a class generated into inputs.ts —
   *  exposing static typeID and instance encode(): Uint8Array. The
   *  resulting wire frame is dispatched server-side to the matching
   *  HandleClient[T] handler. */
  send(msg: { encode(): Uint8Array }): void {
    const ctor = msg.constructor as unknown as { typeID: number };
    this.transport.sendClientInput(ctor.typeID, msg.encode());
  }

  /** Send PingMsg (code 1). */
  sendPing(params: { clientTime: bigint }): void {
    const data = toBinary(PingMsgSchema, create(PingMsgSchema, params));
    this.sendEvent(1, data);
  }

  /** Send LoginMsg (code 2). */
  sendLogin(params: { username: string }): void {
    const data = toBinary(LoginMsgSchema, create(LoginMsgSchema, params));
    this.sendEvent(2, data);
  }

  /** Subscribe to worldUpdate (code 0). */
  onWorldUpdate(handler: (msg: WorldUpdateMsg) => void): () => void {
    return this.on(0, (data) => handler(fromBinary(WorldUpdateMsgSchema, data)));
  }

  /** Subscribe to cellChange (code 5). */
  onCellChange(handler: (msg: CellChangeMsg) => void): () => void {
    return this.on(5, (data) => handler(fromBinary(CellChangeMsgSchema, data)));
  }

  /** Subscribe to serverConfig (code 8). */
  onServerConfig(handler: (msg: ServerConfigMsg) => void): () => void {
    return this.on(8, (data) => handler(fromBinary(ServerConfigMsgSchema, data)));
  }

  /** Subscribe to typed server event game.BankContents (typeID 0xce9d072f). */
  onBankContents(handler: (msg: BankContents) => void): () => void {
    return this.typedEvents.on(BankContents, handler);
  }

  /** Subscribe to typed server event game.CurrencyUpdate (typeID 0x722e1d79). */
  onCurrencyUpdate(handler: (msg: CurrencyUpdate) => void): () => void {
    return this.typedEvents.on(CurrencyUpdate, handler);
  }

  /** Subscribe to typed server event game.Docked (typeID 0x8bf5541d). */
  onDocked(handler: (msg: Docked) => void): () => void {
    return this.typedEvents.on(Docked, handler);
  }

  /** Subscribe to typed server event game.DockingState (typeID 0x5c80df11). */
  onDockingState(handler: (msg: DockingState) => void): () => void {
    return this.typedEvents.on(DockingState, handler);
  }

  /** Subscribe to typed server event game.EquipResult (typeID 0x50af4abc). */
  onEquipResult(handler: (msg: EquipResult) => void): () => void {
    return this.typedEvents.on(EquipResult, handler);
  }

  /** Subscribe to typed server event game.MapData (typeID 0xc16d89a3). */
  onMapData(handler: (msg: MapData) => void): () => void {
    return this.typedEvents.on(MapData, handler);
  }

  /** Subscribe to typed server event game.PlayerDied (typeID 0xef56f740). */
  onPlayerDied(handler: (msg: PlayerDied) => void): () => void {
    return this.typedEvents.on(PlayerDied, handler);
  }

  /** Subscribe to typed server event game.PlayerOwnState (typeID 0xa01e17d7). */
  onPlayerOwnState(handler: (msg: PlayerOwnState) => void): () => void {
    return this.typedEvents.on(PlayerOwnState, handler);
  }

  /** Subscribe to typed server event game.PlayerSpawned (typeID 0xafa7d058). */
  onPlayerSpawned(handler: (msg: PlayerSpawned) => void): () => void {
    return this.typedEvents.on(PlayerSpawned, handler);
  }

  /** Subscribe to typed server event game.TransferResult (typeID 0xed313859). */
  onTransferResult(handler: (msg: TransferResult) => void): () => void {
    return this.typedEvents.on(TransferResult, handler);
  }

  /** Subscribe to typed server event mmokit.DebugInfo (typeID 0x83f2dca1). */
  onDebugInfo(handler: (msg: DebugInfo) => void): () => void {
    return this.typedEvents.on(DebugInfo, handler);
  }

  /** Subscribe to typed server event mmokit.LoginRejected (typeID 0x62f41d81). */
  onLoginRejected(handler: (msg: LoginRejected) => void): () => void {
    return this.typedEvents.on(LoginRejected, handler);
  }

  /** Subscribe to typed server event mmokit.Pong (typeID 0x8527c2fc). */
  onPong(handler: (msg: Pong) => void): () => void {
    return this.typedEvents.on(Pong, handler);
  }

  /** Subscribe to typed server event mmokit.WorldDelta (typeID 0x065b16f4). */
  onWorldDelta(handler: (msg: WorldDelta) => void): () => void {
    return this.typedEvents.on(WorldDelta, handler);
  }

  private handleOperation(payload: Uint8Array): void {
    const resp = fromBinary(OperationResponseSchema, payload) as OperationResponse;
    if (resp.requestId !== 0) {
      const pending = this.pendingOps.get(resp.requestId);
      if (pending) {
        this.pendingOps.delete(resp.requestId);
        if (resp.returnCode !== 0) {
          pending.reject(new Error(resp.errorMsg || `op error code ${resp.returnCode}`));
        } else {
          pending.resolve(resp.data);
        }
      }
      return;
    }
    const handlers = this.pushHandlers.get(resp.code);
    if (handlers) for (const h of handlers) h(resp.data);
  }

  private onPush(code: number, handler: (data: Uint8Array) => void): () => void {
    let arr = this.pushHandlers.get(code);
    if (!arr) { arr = []; this.pushHandlers.set(code, arr); }
    arr.push(handler);
    return () => { const idx = arr!.indexOf(handler); if (idx >= 0) arr!.splice(idx, 1); };
  }

  /** Send a raw op (code, data) and await raw response bytes. For ops not in the typed schema. */
  sendOp(code: number, data: Uint8Array): Promise<Uint8Array> {
    const requestId = this.nextRequestID++;
    const req = create(OperationRequestSchema, { code, requestId, data });
    this.transport.sendOperation(toBinary(OperationRequestSchema, req));
    return new Promise((resolve, reject) => {
      this.pendingOps.set(requestId, { resolve, reject });
    });
  }

  /** Send marketBrowse request (op code 0), await typed MarketOrderBookResponse. */
  sendMarketBrowse(params: { itemId: number }): Promise<MarketOrderBookResponse> {
    const data = toBinary(MarketBrowseRequestSchema, create(MarketBrowseRequestSchema, params));
    const requestId = this.nextRequestID++;
    const req = create(OperationRequestSchema, { code: 0, requestId, data });
    this.transport.sendOperation(toBinary(OperationRequestSchema, req));
    return new Promise((resolve, reject) => {
      this.pendingOps.set(requestId, {
        resolve: (d) => resolve(fromBinary(MarketOrderBookResponseSchema, d) as MarketOrderBookResponse),
        reject,
      });
    });
  }

  /** Subscribe to unsolicited marketBrowse pushes (op code 0, requestId=0). */
  onMarketBrowsePush(handler: (msg: MarketOrderBookResponse) => void): () => void {
    return this.onPush(0, (data) => handler(fromBinary(MarketOrderBookResponseSchema, data) as MarketOrderBookResponse));
  }

  /** Send marketCreateOrder request (op code 1), await typed MarketOrderResultResponse. */
  sendMarketCreateOrder(params: { itemId: number; isBuy: boolean; pricePerUnit: bigint; quantity: number }): Promise<MarketOrderResultResponse> {
    const data = toBinary(MarketCreateOrderRequestSchema, create(MarketCreateOrderRequestSchema, params));
    const requestId = this.nextRequestID++;
    const req = create(OperationRequestSchema, { code: 1, requestId, data });
    this.transport.sendOperation(toBinary(OperationRequestSchema, req));
    return new Promise((resolve, reject) => {
      this.pendingOps.set(requestId, {
        resolve: (d) => resolve(fromBinary(MarketOrderResultResponseSchema, d) as MarketOrderResultResponse),
        reject,
      });
    });
  }

  /** Subscribe to unsolicited marketCreateOrder pushes (op code 1, requestId=0). */
  onMarketCreateOrderPush(handler: (msg: MarketOrderResultResponse) => void): () => void {
    return this.onPush(1, (data) => handler(fromBinary(MarketOrderResultResponseSchema, data) as MarketOrderResultResponse));
  }

  /** Send marketCancelOrder request (op code 2), await typed MarketOrderResultResponse. */
  sendMarketCancelOrder(params: { orderId: bigint }): Promise<MarketOrderResultResponse> {
    const data = toBinary(MarketCancelOrderRequestSchema, create(MarketCancelOrderRequestSchema, params));
    const requestId = this.nextRequestID++;
    const req = create(OperationRequestSchema, { code: 2, requestId, data });
    this.transport.sendOperation(toBinary(OperationRequestSchema, req));
    return new Promise((resolve, reject) => {
      this.pendingOps.set(requestId, {
        resolve: (d) => resolve(fromBinary(MarketOrderResultResponseSchema, d) as MarketOrderResultResponse),
        reject,
      });
    });
  }

  /** Subscribe to unsolicited marketCancelOrder pushes (op code 2, requestId=0). */
  onMarketCancelOrderPush(handler: (msg: MarketOrderResultResponse) => void): () => void {
    return this.onPush(2, (data) => handler(fromBinary(MarketOrderResultResponseSchema, data) as MarketOrderResultResponse));
  }

  /** Send marketMyOrders request (op code 3), await typed MarketMyOrdersResponse. */
  sendMarketMyOrders(params: {  }): Promise<MarketMyOrdersResponse> {
    const data = toBinary(MarketMyOrdersRequestSchema, create(MarketMyOrdersRequestSchema, params));
    const requestId = this.nextRequestID++;
    const req = create(OperationRequestSchema, { code: 3, requestId, data });
    this.transport.sendOperation(toBinary(OperationRequestSchema, req));
    return new Promise((resolve, reject) => {
      this.pendingOps.set(requestId, {
        resolve: (d) => resolve(fromBinary(MarketMyOrdersResponseSchema, d) as MarketMyOrdersResponse),
        reject,
      });
    });
  }

  /** Subscribe to unsolicited marketMyOrders pushes (op code 3, requestId=0). */
  onMarketMyOrdersPush(handler: (msg: MarketMyOrdersResponse) => void): () => void {
    return this.onPush(3, (data) => handler(fromBinary(MarketMyOrdersResponseSchema, data) as MarketMyOrdersResponse));
  }

  /** Send marketInstantTrade request (op code 4), await typed MarketOrderResultResponse. */
  sendMarketInstantTrade(params: { itemId: number; isBuy: boolean; quantity: number }): Promise<MarketOrderResultResponse> {
    const data = toBinary(MarketInstantTradeRequestSchema, create(MarketInstantTradeRequestSchema, params));
    const requestId = this.nextRequestID++;
    const req = create(OperationRequestSchema, { code: 4, requestId, data });
    this.transport.sendOperation(toBinary(OperationRequestSchema, req));
    return new Promise((resolve, reject) => {
      this.pendingOps.set(requestId, {
        resolve: (d) => resolve(fromBinary(MarketOrderResultResponseSchema, d) as MarketOrderResultResponse),
        reject,
      });
    });
  }

  /** Subscribe to unsolicited marketInstantTrade pushes (op code 4, requestId=0). */
  onMarketInstantTradePush(handler: (msg: MarketOrderResultResponse) => void): () => void {
    return this.onPush(4, (data) => handler(fromBinary(MarketOrderResultResponseSchema, data) as MarketOrderResultResponse));
  }

  /** Catch-all for unhandled server events. */
  onRawEvent(handler: (code: number, data: Uint8Array) => void): () => void {
    this.rawEventHandlers.push(handler);
    return () => {
      const idx = this.rawEventHandlers.indexOf(handler);
      if (idx >= 0) this.rawEventHandlers.splice(idx, 1);
    };
  }

  /** Clear delta baselines (call on cell change / reconnect). */
  clearBaselines(): void { this.decoder.clear(); }
}
