// GENERATED by sdkgen — do not edit.

import { create, toBinary, fromBinary } from "@bufbuild/protobuf";
import { CellChangeMsgSchema, PingMsgSchema, ServerConfigMsgSchema, SpawnedMsgSchema } from "@gen/enginepb/engine_pb.js";
import type { CellChangeMsg, ServerConfigMsg, SpawnedMsg } from "@gen/enginepb/engine_pb.js";
import { Transport } from "./transport.js";
import { SpaceDeltaDecoder } from "./delta-decoder.js";
import type { DeltaWorldUpdate } from "./entities.js";
import { TypedDispatcher, BankContents, CurrencyUpdate, Docked, DockingState, EquipResult, MapData, PlayerDied, PlayerOwnState, PlayerSpawned, TransferResult, DebugInfo, OperationError, Pong, WorldDelta } from "./broadcasts.js";
import { BankRequest, BankResponse, MarketBrowseRequest, MarketCancelOrderRequest, MarketCreateOrderRequest, MarketInstantTradeRequest, MarketMyOrdersRequest, MarketMyOrdersResponse, MarketOrderBookResponse, MarketOrderResultResponse } from "./operations.js";
import { ClientEventSchema, ServerEventSchema, type ServerEvent } from "@gen/enginepb/engine_pb.js";

export interface SpaceClientOptions {
  url: string;
  onOpen?: () => void;
  onClose?: (ev: CloseEvent) => void;
  onError?: (ev: Event) => void;
}

export class SpaceClient {
  private transport: Transport;
  private decoder = new SpaceDeltaDecoder();
  private eventHandlers = new Map<number, ((data: Uint8Array) => void)[]>();
  private rawEventHandlers: ((code: number, data: Uint8Array) => void)[] = [];
  /** Typed broadcast dispatcher — register handlers for AoI-filtered
   *  events emitted by the server's HandleAll[T] machinery. */
  readonly typedEvents = new TypedDispatcher();
  private pendingTypedOps = new Map<bigint, { resolve: (msg: any) => void; reject: (err: Error) => void; resCls: { typeID: number; decode(buf: Uint8Array): any } }>();
  private nextTypedOpRequestID: bigint = 1n;

  constructor(private options: SpaceClientOptions) {
    this.transport = new Transport(options.url);
  }

  connect(): void {
    this.transport.connect();
    const ws = this.transport.socket!;
    if (this.options.onOpen) ws.onopen = this.options.onOpen;
    if (this.options.onClose) ws.onclose = this.options.onClose;
    if (this.options.onError) ws.onerror = this.options.onError;
    this.transport.onEvent((payload) => this.handleEvent(payload));
    this.transport.onOperation((payload) => this.handleOperation(payload));
  }

  disconnect(): void {
    // Reject any pending operations.
    for (const pending of this.pendingTypedOps.values()) {
      pending.reject(new Error("client disconnected"));
    }
    this.pendingTypedOps.clear();
    this.transport.close();
  }
  get connected(): boolean { return this.transport.connected; }

  /** Raw transport handle for advanced use (operations channel,
   *  custom protocol extensions). Most app code should use the typed
   *  send* / on* methods on this class instead. */
  get rawTransport(): Transport { return this.transport; }

  private handleEvent(payload: Uint8Array): void {
    if (payload.length === 0) return;
    if (payload[0] !== 0x08) {
      // Typed-event frame: repeated [typeID:u32 LE][body_len:u32 LE][body].
      let off = 0;
      while (off + 8 <= payload.length) {
        const view = new DataView(payload.buffer, payload.byteOffset + off, 8);
        const typeID = view.getUint32(0, true);
        const bodyLen = view.getUint32(4, true);
        off += 8;
        if (off + bodyLen > payload.length) {
          console.warn(`typed-event frame: truncated body for typeID=0x${typeID.toString(16)}`);
          return;
        }
        const body = payload.subarray(off, off + bodyLen);
        off += bodyLen;
        this.typedEvents.dispatch(typeID, body);
      }
      return;
    }
    let evt: ServerEvent;
    try {
      evt = fromBinary(ServerEventSchema, payload) as ServerEvent;
    } catch (err) {
      console.warn(`legacy ServerEvent decode failed (first byte 0x${payload[0].toString(16)}); this might be a typed-event frame whose typeID's low byte is 0x08 — rename the offending Go type. err=${err}`);
      return;
    }
    const handlers = this.eventHandlers.get(evt.code);
    if (handlers) {
      for (const h of handlers) h(evt.data);
    }
    for (const h of this.rawEventHandlers) h(evt.code, evt.data);
  }

  private on(code: number, handler: (data: Uint8Array) => void): () => void {
    let arr = this.eventHandlers.get(code);
    if (!arr) { arr = []; this.eventHandlers.set(code, arr); }
    arr.push(handler);
    return () => { const idx = arr!.indexOf(handler); if (idx >= 0) arr!.splice(idx, 1); };
  }

  private sendEvent(code: number, data: Uint8Array): void {
    const evt = create(ClientEventSchema, { code, data });
    this.transport.sendEvent(toBinary(ClientEventSchema, evt));
  }

  /** Send a typed client-input message (mmokit.HandleClient).
   *
   *  msg must be an instance of a class generated into inputs.ts —
   *  exposing static typeID and instance encode(): Uint8Array. The
   *  resulting wire frame is dispatched server-side to the matching
   *  HandleClient[T] handler. */
  send(msg: { encode(): Uint8Array }): void {
    const ctor = msg.constructor as unknown as { typeID: number };
    this.transport.sendClientInput(ctor.typeID, msg.encode());
  }

  /** Send PingMsg (code 1). */
  sendPing(params: { clientTime: bigint }): void {
    const data = toBinary(PingMsgSchema, create(PingMsgSchema, params));
    this.sendEvent(1, data);
  }

  /** Subscribe to playerEntityAssigned (code 1). */
  onPlayerEntityAssigned(handler: (msg: SpawnedMsg) => void): () => void {
    return this.on(1, (data) => handler(fromBinary(SpawnedMsgSchema, data)));
  }

  /** Subscribe to cellChange (code 2). */
  onCellChange(handler: (msg: CellChangeMsg) => void): () => void {
    return this.on(2, (data) => handler(fromBinary(CellChangeMsgSchema, data)));
  }

  /** Subscribe to serverConfig (code 3). */
  onServerConfig(handler: (msg: ServerConfigMsg) => void): () => void {
    return this.on(3, (data) => handler(fromBinary(ServerConfigMsgSchema, data)));
  }

  /** Subscribe to typed server event game.BankContents (typeID 0xce9d072f). */
  onBankContents(handler: (msg: BankContents) => void): () => void {
    return this.typedEvents.on(BankContents, handler);
  }

  /** Subscribe to typed server event game.CurrencyUpdate (typeID 0x722e1d79). */
  onCurrencyUpdate(handler: (msg: CurrencyUpdate) => void): () => void {
    return this.typedEvents.on(CurrencyUpdate, handler);
  }

  /** Subscribe to typed server event game.Docked (typeID 0x8bf5541d). */
  onDocked(handler: (msg: Docked) => void): () => void {
    return this.typedEvents.on(Docked, handler);
  }

  /** Subscribe to typed server event game.DockingState (typeID 0x5c80df11). */
  onDockingState(handler: (msg: DockingState) => void): () => void {
    return this.typedEvents.on(DockingState, handler);
  }

  /** Subscribe to typed server event game.EquipResult (typeID 0x50af4abc). */
  onEquipResult(handler: (msg: EquipResult) => void): () => void {
    return this.typedEvents.on(EquipResult, handler);
  }

  /** Subscribe to typed server event game.MapData (typeID 0xc16d89a3). */
  onMapData(handler: (msg: MapData) => void): () => void {
    return this.typedEvents.on(MapData, handler);
  }

  /** Subscribe to typed server event game.PlayerDied (typeID 0xef56f740). */
  onPlayerDied(handler: (msg: PlayerDied) => void): () => void {
    return this.typedEvents.on(PlayerDied, handler);
  }

  /** Subscribe to typed server event game.PlayerOwnState (typeID 0xa01e17d7). */
  onPlayerOwnState(handler: (msg: PlayerOwnState) => void): () => void {
    return this.typedEvents.on(PlayerOwnState, handler);
  }

  /** Subscribe to typed server event game.PlayerSpawned (typeID 0xafa7d058). */
  onPlayerSpawned(handler: (msg: PlayerSpawned) => void): () => void {
    return this.typedEvents.on(PlayerSpawned, handler);
  }

  /** Subscribe to typed server event game.TransferResult (typeID 0xed313859). */
  onTransferResult(handler: (msg: TransferResult) => void): () => void {
    return this.typedEvents.on(TransferResult, handler);
  }

  /** Subscribe to typed server event mmokit.DebugInfo (typeID 0x83f2dca1). */
  onDebugInfo(handler: (msg: DebugInfo) => void): () => void {
    return this.typedEvents.on(DebugInfo, handler);
  }

  /** Subscribe to typed server event mmokit.OperationError (typeID 0x3d88aecb). */
  onOperationError(handler: (msg: OperationError) => void): () => void {
    return this.typedEvents.on(OperationError, handler);
  }

  /** Subscribe to typed server event mmokit.Pong (typeID 0x8527c2fc). */
  onPong(handler: (msg: Pong) => void): () => void {
    return this.typedEvents.on(Pong, handler);
  }

  /** Subscribe to typed server event mmokit.WorldDelta (typeID 0x065b16f4). */
  onWorldDelta(handler: (msg: WorldDelta) => void): () => void {
    return this.typedEvents.on(WorldDelta, handler);
  }

  private handleOperation(payload: Uint8Array): void {
    if (payload.length === 0) return;
      // Typed-op response: [typeID:u32 LE][request_id:u64 LE][bodyLen:u32 LE][body].
      if (payload.length < 16) {
        console.warn(`typed-op frame: truncated header (len=${payload.length})`);
        return;
      }
      const opDV = new DataView(payload.buffer, payload.byteOffset, payload.byteLength);
      const resTypeID = opDV.getUint32(0, true);
      const reqID = opDV.getBigUint64(4, true);
      const bodyLen = opDV.getUint32(12, true);
      if (16 + bodyLen > payload.length) {
        console.warn(`typed-op frame: truncated body for typeID=0x${resTypeID.toString(16)}`);
        return;
      }
      const body = payload.subarray(16, 16 + bodyLen);
      const pending = this.pendingTypedOps.get(reqID);
      if (!pending) {
        console.warn(`typed-op response for unknown request_id ${reqID}`);
        return;
      }
      this.pendingTypedOps.delete(reqID);
      if (resTypeID === OperationError.typeID) {
        const err = OperationError.decode(body);
        pending.reject(new Error(`OperationError code=${err.code}: ${err.message}`));
        return;
      }
      pending.resolve(pending.resCls.decode(body));
    return;
  }

  /** Private helper: encode + send a typed-op request, return a
   *  Promise that resolves with the decoded Response. */
  private callOp<Req extends { encode(): Uint8Array }, Res>(
    req: Req,
    resCls: { typeID: number; decode(buf: Uint8Array): Res }
  ): Promise<Res> {
    const reqID = this.nextTypedOpRequestID++;
    const reqTypeID = (req.constructor as unknown as { typeID: number }).typeID;
    const body = req.encode();
    const frame = new Uint8Array(1 + 4 + 8 + 4 + body.length);
    const dv = new DataView(frame.buffer);
    frame[0] = 0x01;
    dv.setUint32(1, reqTypeID, true);
    dv.setBigUint64(5, reqID, true);
    dv.setUint32(13, body.length, true);
    frame.set(body, 17);
    return new Promise<Res>((resolve, reject) => {
      this.pendingTypedOps.set(reqID, { resolve, reject, resCls });
      this.transport.sendRaw(frame);
    });
  }

  /** Typed op game.BankRequest → game.BankResponse (kind=player-cell). */
  bank(req: BankRequest): Promise<BankResponse> {
    return this.callOp<BankRequest, BankResponse>(req, BankResponse);
  }

  /** Typed op marketplace.MarketBrowseRequest → marketplace.MarketOrderBookResponse (kind=player-cell). */
  marketBrowse(req: MarketBrowseRequest): Promise<MarketOrderBookResponse> {
    return this.callOp<MarketBrowseRequest, MarketOrderBookResponse>(req, MarketOrderBookResponse);
  }

  /** Typed op marketplace.MarketCancelOrderRequest → marketplace.MarketOrderResultResponse (kind=player-cell). */
  marketCancelOrder(req: MarketCancelOrderRequest): Promise<MarketOrderResultResponse> {
    return this.callOp<MarketCancelOrderRequest, MarketOrderResultResponse>(req, MarketOrderResultResponse);
  }

  /** Typed op marketplace.MarketCreateOrderRequest → marketplace.MarketOrderResultResponse (kind=player-cell). */
  marketCreateOrder(req: MarketCreateOrderRequest): Promise<MarketOrderResultResponse> {
    return this.callOp<MarketCreateOrderRequest, MarketOrderResultResponse>(req, MarketOrderResultResponse);
  }

  /** Typed op marketplace.MarketInstantTradeRequest → marketplace.MarketOrderResultResponse (kind=player-cell). */
  marketInstantTrade(req: MarketInstantTradeRequest): Promise<MarketOrderResultResponse> {
    return this.callOp<MarketInstantTradeRequest, MarketOrderResultResponse>(req, MarketOrderResultResponse);
  }

  /** Typed op marketplace.MarketMyOrdersRequest → marketplace.MarketMyOrdersResponse (kind=player-cell). */
  marketMyOrders(req: MarketMyOrdersRequest): Promise<MarketMyOrdersResponse> {
    return this.callOp<MarketMyOrdersRequest, MarketMyOrdersResponse>(req, MarketMyOrdersResponse);
  }

  /** Catch-all for unhandled server events. */
  onRawEvent(handler: (code: number, data: Uint8Array) => void): () => void {
    this.rawEventHandlers.push(handler);
    return () => {
      const idx = this.rawEventHandlers.indexOf(handler);
      if (idx >= 0) this.rawEventHandlers.splice(idx, 1);
    };
  }

  /** Clear delta baselines (call on cell change / reconnect). */
  clearBaselines(): void { this.decoder.clear(); }
}
