// GENERATED by sdkgen — do not edit.

import {
  readFloat32, readInt16, readUint16, readUint32,
  unAngle, unNorm, unVel,
  decodeFrameHeader, decodeFullEntry, decodeDeltaEntry, decodeRemovedIDs,
  applyDelta, BaselineStore,
  decodeLengthPrefixedStringU8,
} from "./_core/delta-decoder-core.js";
import type { NPCEntity, LootCrateEntity, ShipEntity, AsteroidEntity, StationEntity, AnyEntity, DeltaWorldUpdate } from "./entities.js";

const NPCENTITY_FIELD_SIZES = [4, 4, 2, 2, 2, 2, 2, 4, 4, 4, 4];
const NPCENTITY_HAS_VAR_TAIL = false;

function decodeNPCEntitySnapshot(snap: Uint8Array, initial: Uint8Array | null, existing?: NPCEntity): NPCEntity {
  let o = 0;
  const worldX = readFloat32(snap, o); o += 4;
  const worldY = readFloat32(snap, o); o += 4;
  const velX = unVel(readInt16(snap, o), 2000); o += 2;
  const velY = unVel(readInt16(snap, o), 2000); o += 2;
  const radius = unVel(readInt16(snap, o), 500); o += 2;
  const width = unVel(readInt16(snap, o), 500); o += 2;
  const height = unVel(readInt16(snap, o), 500); o += 2;
  const healthCurrent = readFloat32(snap, o); o += 4;
  const healthMax = readFloat32(snap, o); o += 4;
  const shieldCurrent = readFloat32(snap, o); o += 4;
  const shieldMax = readFloat32(snap, o); o += 4;
  return { netID: 0, entityType: 5, worldX, worldY, velX, velY, radius, width, height, healthCurrent, healthMax, shieldCurrent, shieldMax };
}

const LOOTCRATEENTITY_FIELD_SIZES = [4, 4, 2, 2, 2, 2, 2];
const LOOTCRATEENTITY_HAS_VAR_TAIL = false;

function decodeLootCrateEntitySnapshot(snap: Uint8Array, initial: Uint8Array | null, existing?: LootCrateEntity): LootCrateEntity {
  let o = 0;
  const worldX = readFloat32(snap, o); o += 4;
  const worldY = readFloat32(snap, o); o += 4;
  const velX = unVel(readInt16(snap, o), 100); o += 2;
  const velY = unVel(readInt16(snap, o), 100); o += 2;
  const radius = unVel(readInt16(snap, o), 100); o += 2;
  const width = unVel(readInt16(snap, o), 100); o += 2;
  const height = unVel(readInt16(snap, o), 100); o += 2;
  return { netID: 0, entityType: 4, worldX, worldY, velX, velY, radius, width, height };
}

const SHIPENTITY_FIELD_SIZES = [4, 4, 2, 2, 2, 2, 2, 4, 4, 4, 4];
const SHIPENTITY_HAS_VAR_TAIL = false;

function decodeShipEntitySnapshot(snap: Uint8Array, initial: Uint8Array | null, existing?: ShipEntity): ShipEntity {
  let o = 0;
  const worldX = readFloat32(snap, o); o += 4;
  const worldY = readFloat32(snap, o); o += 4;
  const velX = unVel(readInt16(snap, o), 2000); o += 2;
  const velY = unVel(readInt16(snap, o), 2000); o += 2;
  const radius = unVel(readInt16(snap, o), 500); o += 2;
  const width = unVel(readInt16(snap, o), 500); o += 2;
  const height = unVel(readInt16(snap, o), 500); o += 2;
  const healthCurrent = readFloat32(snap, o); o += 4;
  const healthMax = readFloat32(snap, o); o += 4;
  const shieldCurrent = readFloat32(snap, o); o += 4;
  const shieldMax = readFloat32(snap, o); o += 4;
  const name = initial ? decodeLengthPrefixedStringU8(initial) : (existing?.name ?? "");
  return { netID: 0, entityType: 0, worldX, worldY, velX, velY, radius, width, height, name, healthCurrent, healthMax, shieldCurrent, shieldMax };
}

const ASTEROIDENTITY_FIELD_SIZES = [4, 4, 2, 2, 2, 2, 2, 4, 4];
const ASTEROIDENTITY_HAS_VAR_TAIL = false;

function decodeAsteroidEntitySnapshot(snap: Uint8Array, initial: Uint8Array | null, existing?: AsteroidEntity): AsteroidEntity {
  let o = 0;
  const worldX = readFloat32(snap, o); o += 4;
  const worldY = readFloat32(snap, o); o += 4;
  const velX = unVel(readInt16(snap, o), 100); o += 2;
  const velY = unVel(readInt16(snap, o), 100); o += 2;
  const radius = unVel(readInt16(snap, o), 500); o += 2;
  const width = unVel(readInt16(snap, o), 500); o += 2;
  const height = unVel(readInt16(snap, o), 500); o += 2;
  const itemID = readUint32(snap, o); o += 4;
  const remaining = readFloat32(snap, o); o += 4;
  return { netID: 0, entityType: 1, worldX, worldY, velX, velY, radius, width, height, itemID, remaining };
}

const STATIONENTITY_FIELD_SIZES = [4, 4, 2, 2, 2, 2, 2];
const STATIONENTITY_HAS_VAR_TAIL = false;

function decodeStationEntitySnapshot(snap: Uint8Array, initial: Uint8Array | null, existing?: StationEntity): StationEntity {
  let o = 0;
  const worldX = readFloat32(snap, o); o += 4;
  const worldY = readFloat32(snap, o); o += 4;
  const velX = unVel(readInt16(snap, o), 100); o += 2;
  const velY = unVel(readInt16(snap, o), 100); o += 2;
  const radius = unVel(readInt16(snap, o), 500); o += 2;
  const width = unVel(readInt16(snap, o), 500); o += 2;
  const height = unVel(readInt16(snap, o), 500); o += 2;
  return { netID: 0, entityType: 3, worldX, worldY, velX, velY, radius, width, height };
}

export class SpaceDeltaDecoder {
  private baselines = new BaselineStore<{ type: number; name?: string }>();

  clear(): void { this.baselines.clear(); }

  decode(data: Uint8Array): DeltaWorldUpdate {
    const { header, offset: pos0 } = decodeFrameHeader(data, 0);
    let pos = pos0;

    const entered: AnyEntity[] = [];
    const updated: AnyEntity[] = [];

    for (let i = 0; i < header.fullCount; i++) {
      const { entry, offset: next } = decodeFullEntry(data, pos);
      pos = next;
      this.baselines.set(entry.netID, entry.snapshot, { type: entry.entityType });
      const entity = this.decodeEntity(entry.entityType, entry.snapshot, entry.initialData, entry.netID);
      if (entity) entered.push(entity);
    }

    for (let i = 0; i < header.deltaCount; i++) {
      const { entry, offset: next } = decodeDeltaEntry(data, pos);
      pos = next;
      const bl = this.baselines.get(entry.netID);
      if (!bl) continue;
      const fieldSizes = this.fieldSizesFor(entry.entityType);
      const hasVarTail = this.hasVarTailFor(entry.entityType);
      const newSnap = applyDelta(fieldSizes, hasVarTail, bl.snapshot, entry.deltaData);
      this.baselines.set(entry.netID, newSnap, bl.meta);
      const entity = this.decodeEntity(entry.entityType, newSnap, null, entry.netID);
      if (entity) updated.push(entity);
    }

    const { ids: removed, offset: pos2 } = decodeRemovedIDs(data, pos, header.removedCount);
    const { ids: exited } = decodeRemovedIDs(data, pos2, header.exitedCount);

    for (const id of removed) this.baselines.delete(id);
    for (const id of exited) this.baselines.delete(id);

    return {
      tick: header.tick, seq: header.seq,
      viewerX: header.viewerX, viewerY: header.viewerY,
      entered, updated, removed, exited,
    };
  }

  private decodeEntity(type_: number, snap: Uint8Array, initial: Uint8Array | null, netID: number): AnyEntity | null {
    switch (type_) {
      case 5: { const e = decodeNPCEntitySnapshot(snap, initial); e.netID = netID; return e; }
      case 4: { const e = decodeLootCrateEntitySnapshot(snap, initial); e.netID = netID; return e; }
      case 0: { const e = decodeShipEntitySnapshot(snap, initial); e.netID = netID; return e; }
      case 1: { const e = decodeAsteroidEntitySnapshot(snap, initial); e.netID = netID; return e; }
      case 3: { const e = decodeStationEntitySnapshot(snap, initial); e.netID = netID; return e; }
      default: return null;
    }
  }

  private fieldSizesFor(type_: number): number[] {
    switch (type_) {
      case 5: return NPCENTITY_FIELD_SIZES;
      case 4: return LOOTCRATEENTITY_FIELD_SIZES;
      case 0: return SHIPENTITY_FIELD_SIZES;
      case 1: return ASTEROIDENTITY_FIELD_SIZES;
      case 3: return STATIONENTITY_FIELD_SIZES;
      default: return [];
    }
  }

  private hasVarTailFor(type_: number): boolean {
    switch (type_) {
      case 5: return NPCENTITY_HAS_VAR_TAIL;
      case 4: return LOOTCRATEENTITY_HAS_VAR_TAIL;
      case 0: return SHIPENTITY_HAS_VAR_TAIL;
      case 1: return ASTEROIDENTITY_HAS_VAR_TAIL;
      case 3: return STATIONENTITY_HAS_VAR_TAIL;
      default: return false;
    }
  }
}
