// GENERATED by sdkgen — do not edit.

/** Entity kind 0. */
export interface ShipEntity {
  netID: number;
  entityType: 0;
  worldX: number;
  worldY: number;
  velX: number;
  velY: number;
  radius: number;
  width: number;
  height: number;
  healthCurrent: number;
  healthMax: number;
  shieldCurrent: number;
  shieldMax: number;
  lockerNetID: number;
  lockerProgress: number;
  name: string;
}

/** Entity kind 1. */
export interface AsteroidEntity {
  netID: number;
  entityType: 1;
  worldX: number;
  worldY: number;
  velX: number;
  velY: number;
  radius: number;
  width: number;
  height: number;
  itemID: number;
  remaining: number;
  lockerNetID: number;
  lockerProgress: number;
}

/** Entity kind 3. */
export interface StationEntity {
  netID: number;
  entityType: 3;
  worldX: number;
  worldY: number;
  velX: number;
  velY: number;
  radius: number;
  width: number;
  height: number;
}

/** Entity kind 4. */
export interface LootCrateEntity {
  netID: number;
  entityType: 4;
  worldX: number;
  worldY: number;
  velX: number;
  velY: number;
  radius: number;
  width: number;
  height: number;
}

/** Entity kind 5. */
export interface NPCEntity {
  netID: number;
  entityType: 5;
  worldX: number;
  worldY: number;
  velX: number;
  velY: number;
  radius: number;
  width: number;
  height: number;
  healthCurrent: number;
  healthMax: number;
  shieldCurrent: number;
  shieldMax: number;
  lockerNetID: number;
  lockerProgress: number;
}

export type AnyEntity = ShipEntity | AsteroidEntity | StationEntity | LootCrateEntity | NPCEntity;

export interface DeltaWorldUpdate {
  tick: number;
  seq: number;
  viewerX: number;
  viewerY: number;
  entered: AnyEntity[];
  updated: AnyEntity[];
  removed: number[];
  exited: number[];
}
