// GENERATED by sdkgen — do not edit.

/**
 * Client render mode declared by the server's protocol schema.
 *
 * - "interpolated": use per-entity producedAtMs to build a sample
 *   ring; interpolate with RENDER_DELAY lag; run client-side
 *   prediction for the local player. Smooth motion, ~100ms
 *   visual lag, complex reconciliation.
 *
 * - "snap": render at the latest-received worldX/worldY. No sample
 *   ring, no lerp, no prediction. Input latency is visible but
 *   motion is always authoritative. League-of-Legends model.
 *
 * Game code should branch on this constant to enable/disable the
 * prediction and interp paths.
 */
export const CLIENT_RENDER_MODE = "interpolated" as const;
export type ClientRenderMode = typeof CLIENT_RENDER_MODE;

export function isSnapMode(): boolean {
  return (CLIENT_RENDER_MODE as string) === "snap";
}

export function isInterpolatedMode(): boolean {
  return (CLIENT_RENDER_MODE as string) === "interpolated";
}

/** Entity kind 0. */
export interface ShipEntity {
  netID: number;
  entityType: 0;
  /**
   * Cluster-clock stamp (Unix ms) from the authoritative producer at
   * the moment this state was emitted. Preserves the producer's
   * timeline through any relay hops. Used as the per-entity time-base
   * for snapshot interpolation.
   */
  producedAtMs: number;
  worldX: number;
  worldY: number;
  velX: number;
  velY: number;
  radius: number;
  width: number;
  height: number;
  meshState: number;
  ownerNode: number;
  angle: number;
  healthCurrent: number;
  healthMax: number;
  shieldCurrent: number;
  shieldMax: number;
  lockerNetID: number;
  lockerProgress: number;
  beam0Active: boolean;
  beam1Active: boolean;
  miningTargetNetID: number;
  name: string;
  statusEffects: ShipStatusEffectsItem[];
}

/** Item record for ShipEntity.statusEffects var-tail. */
export interface ShipStatusEffectsItem {
  type: number;
  duration: number;
}

/** Entity kind 1. */
export interface AsteroidEntity {
  netID: number;
  entityType: 1;
  /**
   * Cluster-clock stamp (Unix ms) from the authoritative producer at
   * the moment this state was emitted. Preserves the producer's
   * timeline through any relay hops. Used as the per-entity time-base
   * for snapshot interpolation.
   */
  producedAtMs: number;
  worldX: number;
  worldY: number;
  velX: number;
  velY: number;
  radius: number;
  width: number;
  height: number;
  meshState: number;
  ownerNode: number;
  itemID: number;
  remaining: number;
}

/** Entity kind 3. */
export interface StationEntity {
  netID: number;
  entityType: 3;
  /**
   * Cluster-clock stamp (Unix ms) from the authoritative producer at
   * the moment this state was emitted. Preserves the producer's
   * timeline through any relay hops. Used as the per-entity time-base
   * for snapshot interpolation.
   */
  producedAtMs: number;
  worldX: number;
  worldY: number;
  velX: number;
  velY: number;
  radius: number;
  width: number;
  height: number;
  meshState: number;
  ownerNode: number;
}

/** Entity kind 4. */
export interface LootCrateEntity {
  netID: number;
  entityType: 4;
  /**
   * Cluster-clock stamp (Unix ms) from the authoritative producer at
   * the moment this state was emitted. Preserves the producer's
   * timeline through any relay hops. Used as the per-entity time-base
   * for snapshot interpolation.
   */
  producedAtMs: number;
  worldX: number;
  worldY: number;
  velX: number;
  velY: number;
  radius: number;
  width: number;
  height: number;
  meshState: number;
  ownerNode: number;
  items: LootCrateItemsItem[];
}

/** Item record for LootCrateEntity.items var-tail. */
export interface LootCrateItemsItem {
  itemId: number;
  quantity: number;
}

/** Entity kind 5. */
export interface NPCEntity {
  netID: number;
  entityType: 5;
  /**
   * Cluster-clock stamp (Unix ms) from the authoritative producer at
   * the moment this state was emitted. Preserves the producer's
   * timeline through any relay hops. Used as the per-entity time-base
   * for snapshot interpolation.
   */
  producedAtMs: number;
  worldX: number;
  worldY: number;
  velX: number;
  velY: number;
  radius: number;
  width: number;
  height: number;
  meshState: number;
  ownerNode: number;
  healthCurrent: number;
  healthMax: number;
  shieldCurrent: number;
  shieldMax: number;
  statusEffects: NPCStatusEffectsItem[];
}

/** Item record for NPCEntity.statusEffects var-tail. */
export interface NPCStatusEffectsItem {
  type: number;
  duration: number;
}

export type AnyEntity = ShipEntity | AsteroidEntity | StationEntity | LootCrateEntity | NPCEntity;

export interface DeltaWorldUpdate {
  tick: number;
  seq: number;
  /**
   * Set when the server's ReplicationSystem sent this frame as the
   * first frame to this connection — i.e. on initial login or on every
   * cross-cell handoff. The SDK decoder clears its per-entity baselines
   * before applying the frame; clients should treat the frame's Entered
   * list as the authoritative current entity set and drop any stale
   * entities they retained from before. Topology-transparent: clients
   * never learn about cells, authority transfers, or server boundaries.
   */
  freshSnapshot: boolean;
  entered: AnyEntity[];
  updated: AnyEntity[];
  removed: number[];
  exited: number[];
}
