// GENERATED by sdkgen — do not edit.

// Typed client-input messages. Wire format mirrors the reflect-codec
// layout in pkg/universe/reflect_marshal.go: fields encoded in source
// order, little-endian, no padding. mmokit.Entity → 4-byte NetID.
//
// SpaceClient.send(msg) wraps the encoded body in the [0x00][u32 typeID]
// [u32 bodyLen][body] frame consumed by the server's HandleClient dispatch.

/** Client-input message game.CastAbility (typeID 0x16eb7722). */
export class CastAbility {
  static readonly typeID = 0x16eb7722;
  sequence: number = 0;
  slot: number = 0;

  constructor(init?: Partial<CastAbility>) {
    if (init) Object.assign(this, init);
  }

  encode(): Uint8Array {
    const buf = new Uint8Array(5);
    const dv = new DataView(buf.buffer);
    let off = 0;
    dv.setUint32(off, this.sequence, true); off += 4;
    dv.setUint8(off, this.slot); off += 1;
    return buf;
  }
}

/** Client-input message game.Dock (typeID 0xb4f7752c). */
export class Dock {
  static readonly typeID = 0xb4f7752c;
  sequence: number = 0;

  constructor(init?: Partial<Dock>) {
    if (init) Object.assign(this, init);
  }

  encode(): Uint8Array {
    const buf = new Uint8Array(4);
    const dv = new DataView(buf.buffer);
    let off = 0;
    dv.setUint32(off, this.sequence, true); off += 4;
    return buf;
  }
}

/** Client-input message game.Equip (typeID 0x89d56e6d). */
export class Equip {
  static readonly typeID = 0x89d56e6d;
  sequence: number = 0;
  itemID: number = 0;
  slot: number = 0;
  targetBank: boolean = false;

  constructor(init?: Partial<Equip>) {
    if (init) Object.assign(this, init);
  }

  encode(): Uint8Array {
    const buf = new Uint8Array(10);
    const dv = new DataView(buf.buffer);
    let off = 0;
    dv.setUint32(off, this.sequence, true); off += 4;
    dv.setUint32(off, this.itemID, true); off += 4;
    dv.setUint8(off, this.slot); off += 1;
    dv.setUint8(off, this.targetBank ? 1 : 0); off += 1;
    return buf;
  }
}

/** Client-input message game.InventoryTransfer (typeID 0x268558e6). */
export class InventoryTransfer {
  static readonly typeID = 0x268558e6;
  sequence: number = 0;
  itemID: number = 0;
  quantity: number = 0;
  deposit: boolean = false;

  constructor(init?: Partial<InventoryTransfer>) {
    if (init) Object.assign(this, init);
  }

  encode(): Uint8Array {
    const buf = new Uint8Array(13);
    const dv = new DataView(buf.buffer);
    let off = 0;
    dv.setUint32(off, this.sequence, true); off += 4;
    dv.setUint32(off, this.itemID, true); off += 4;
    dv.setInt32(off, this.quantity, true); off += 4;
    dv.setUint8(off, this.deposit ? 1 : 0); off += 1;
    return buf;
  }
}

/** Client-input message game.JettisonItem (typeID 0xc252af38). */
export class JettisonItem {
  static readonly typeID = 0xc252af38;
  sequence: number = 0;
  itemID: number = 0;

  constructor(init?: Partial<JettisonItem>) {
    if (init) Object.assign(this, init);
  }

  encode(): Uint8Array {
    const buf = new Uint8Array(8);
    const dv = new DataView(buf.buffer);
    let off = 0;
    dv.setUint32(off, this.sequence, true); off += 4;
    dv.setUint32(off, this.itemID, true); off += 4;
    return buf;
  }
}

/** Client-input message game.LockTarget (typeID 0x23808aed). */
export class LockTarget {
  static readonly typeID = 0x23808aed;
  sequence: number = 0;
  netID: number = 0;

  constructor(init?: Partial<LockTarget>) {
    if (init) Object.assign(this, init);
  }

  encode(): Uint8Array {
    const buf = new Uint8Array(8);
    const dv = new DataView(buf.buffer);
    let off = 0;
    dv.setUint32(off, this.sequence, true); off += 4;
    dv.setUint32(off, this.netID, true); off += 4;
    return buf;
  }
}

/** Client-input message game.LootAll (typeID 0xff864c74). */
export class LootAll {
  static readonly typeID = 0xff864c74;
  sequence: number = 0;
  crateNetID: number = 0;

  constructor(init?: Partial<LootAll>) {
    if (init) Object.assign(this, init);
  }

  encode(): Uint8Array {
    const buf = new Uint8Array(8);
    const dv = new DataView(buf.buffer);
    let off = 0;
    dv.setUint32(off, this.sequence, true); off += 4;
    dv.setUint32(off, this.crateNetID, true); off += 4;
    return buf;
  }
}

/** Client-input message game.LootItem (typeID 0x8dd8ab16). */
export class LootItem {
  static readonly typeID = 0x8dd8ab16;
  sequence: number = 0;
  crateNetID: number = 0;
  itemID: number = 0;

  constructor(init?: Partial<LootItem>) {
    if (init) Object.assign(this, init);
  }

  encode(): Uint8Array {
    const buf = new Uint8Array(12);
    const dv = new DataView(buf.buffer);
    let off = 0;
    dv.setUint32(off, this.sequence, true); off += 4;
    dv.setUint32(off, this.crateNetID, true); off += 4;
    dv.setUint32(off, this.itemID, true); off += 4;
    return buf;
  }
}

/** Client-input message game.Respawn (typeID 0x20581121). */
export class Respawn {
  static readonly typeID = 0x20581121;
  sequence: number = 0;

  constructor(init?: Partial<Respawn>) {
    if (init) Object.assign(this, init);
  }

  encode(): Uint8Array {
    const buf = new Uint8Array(4);
    const dv = new DataView(buf.buffer);
    let off = 0;
    dv.setUint32(off, this.sequence, true); off += 4;
    return buf;
  }
}

/** Client-input message game.SetActiveTarget (typeID 0xe3c5227e). */
export class SetActiveTarget {
  static readonly typeID = 0xe3c5227e;
  sequence: number = 0;
  netID: number = 0;

  constructor(init?: Partial<SetActiveTarget>) {
    if (init) Object.assign(this, init);
  }

  encode(): Uint8Array {
    const buf = new Uint8Array(8);
    const dv = new DataView(buf.buffer);
    let off = 0;
    dv.setUint32(off, this.sequence, true); off += 4;
    dv.setUint32(off, this.netID, true); off += 4;
    return buf;
  }
}

/** Client-input message game.SetMoveTarget (typeID 0x4026b5a1). */
export class SetMoveTarget {
  static readonly typeID = 0x4026b5a1;
  sequence: number = 0;
  active: boolean = false;
  x: number = 0;
  y: number = 0;

  constructor(init?: Partial<SetMoveTarget>) {
    if (init) Object.assign(this, init);
  }

  encode(): Uint8Array {
    const buf = new Uint8Array(13);
    const dv = new DataView(buf.buffer);
    let off = 0;
    dv.setUint32(off, this.sequence, true); off += 4;
    dv.setUint8(off, this.active ? 1 : 0); off += 1;
    dv.setFloat32(off, this.x, true); off += 4;
    dv.setFloat32(off, this.y, true); off += 4;
    return buf;
  }
}

/** Client-input message game.Undock (typeID 0x149cc6db). */
export class Undock {
  static readonly typeID = 0x149cc6db;
  sequence: number = 0;

  constructor(init?: Partial<Undock>) {
    if (init) Object.assign(this, init);
  }

  encode(): Uint8Array {
    const buf = new Uint8Array(4);
    const dv = new DataView(buf.buffer);
    let off = 0;
    dv.setUint32(off, this.sequence, true); off += 4;
    return buf;
  }
}

/** Client-input message game.UnlockTarget (typeID 0x23935f96). */
export class UnlockTarget {
  static readonly typeID = 0x23935f96;
  sequence: number = 0;
  netID: number = 0;

  constructor(init?: Partial<UnlockTarget>) {
    if (init) Object.assign(this, init);
  }

  encode(): Uint8Array {
    const buf = new Uint8Array(8);
    const dv = new DataView(buf.buffer);
    let off = 0;
    dv.setUint32(off, this.sequence, true); off += 4;
    dv.setUint32(off, this.netID, true); off += 4;
    return buf;
  }
}

/** Client-input message mmokit.Ping (typeID 0x8c171206). */
export class Ping {
  static readonly typeID = 0x8c171206;
  clientTime: number = 0;

  constructor(init?: Partial<Ping>) {
    if (init) Object.assign(this, init);
  }

  encode(): Uint8Array {
    const buf = new Uint8Array(8);
    const dv = new DataView(buf.buffer);
    let off = 0;
    dv.setBigInt64(off, BigInt(this.clientTime), true); off += 8;
    return buf;
  }
}

