// GENERATED by sdkgen — do not edit.

// Typed operation Request + Response classes. Wire format:
//   [0x01][typeID:u32 LE][request_id:u64 LE][body_len:u32 LE][body]
// Bodies use the reflect-codec layout from pkg/universe/reflect_marshal.go
// (matches broadcasts.ts and inputs.ts).

/** Broadcast-eligible event auth.AuthChangePasswordRequest (typeID 0x8a04aa69). */
export class AuthChangePasswordRequest {
  static readonly typeID = 0x8a04aa69;
  currentPassword: string = "";
  newPassword: string = "";

  constructor(init?: Partial<AuthChangePasswordRequest>) {
    if (init) Object.assign(this, init);
  }

  static decode(buf: Uint8Array): AuthChangePasswordRequest {
    const dv = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
    let off = 0;
    const m = new AuthChangePasswordRequest();
    {
      const sl = dv.getUint16(off, true); off += 2;
      m.currentPassword = new TextDecoder().decode(buf.subarray(off, off + sl)); off += sl;
    }
    {
      const sl = dv.getUint16(off, true); off += 2;
      m.newPassword = new TextDecoder().decode(buf.subarray(off, off + sl)); off += sl;
    }
    return m;
  }

  encode(): Uint8Array {
    const _currentPassword = new TextEncoder().encode(this.currentPassword);
    const _newPassword = new TextEncoder().encode(this.newPassword);
    const buf = new Uint8Array(0 + 2 + _currentPassword.length + 2 + _newPassword.length);
    const dv = new DataView(buf.buffer);
    let off = 0;
    dv.setUint16(off, _currentPassword.length, true); off += 2;
    buf.set(_currentPassword, off); off += _currentPassword.length;
    dv.setUint16(off, _newPassword.length, true); off += 2;
    buf.set(_newPassword, off); off += _newPassword.length;
    return buf;
  }
}

/** Broadcast-eligible event auth.AuthChangePasswordResponse (typeID 0x61dd7957). */
export class AuthChangePasswordResponse {
  static readonly typeID = 0x61dd7957;
  errorCode: number = 0;
  errorMessage: string = "";

  static decode(buf: Uint8Array): AuthChangePasswordResponse {
    const dv = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
    let off = 0;
    const m = new AuthChangePasswordResponse();
    m.errorCode = dv.getUint32(off, true); off += 4;
    {
      const sl = dv.getUint16(off, true); off += 2;
      m.errorMessage = new TextDecoder().decode(buf.subarray(off, off + sl)); off += sl;
    }
    return m;
  }
}

/** Broadcast-eligible event auth.AuthLoginRequest (typeID 0xfbd15167). */
export class AuthLoginRequest {
  static readonly typeID = 0xfbd15167;
  username: string = "";
  password: string = "";
  mfaCode: string = "";

  constructor(init?: Partial<AuthLoginRequest>) {
    if (init) Object.assign(this, init);
  }

  static decode(buf: Uint8Array): AuthLoginRequest {
    const dv = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
    let off = 0;
    const m = new AuthLoginRequest();
    {
      const sl = dv.getUint16(off, true); off += 2;
      m.username = new TextDecoder().decode(buf.subarray(off, off + sl)); off += sl;
    }
    {
      const sl = dv.getUint16(off, true); off += 2;
      m.password = new TextDecoder().decode(buf.subarray(off, off + sl)); off += sl;
    }
    {
      const sl = dv.getUint16(off, true); off += 2;
      m.mfaCode = new TextDecoder().decode(buf.subarray(off, off + sl)); off += sl;
    }
    return m;
  }

  encode(): Uint8Array {
    const _username = new TextEncoder().encode(this.username);
    const _password = new TextEncoder().encode(this.password);
    const _mfaCode = new TextEncoder().encode(this.mfaCode);
    const buf = new Uint8Array(0 + 2 + _username.length + 2 + _password.length + 2 + _mfaCode.length);
    const dv = new DataView(buf.buffer);
    let off = 0;
    dv.setUint16(off, _username.length, true); off += 2;
    buf.set(_username, off); off += _username.length;
    dv.setUint16(off, _password.length, true); off += 2;
    buf.set(_password, off); off += _password.length;
    dv.setUint16(off, _mfaCode.length, true); off += 2;
    buf.set(_mfaCode, off); off += _mfaCode.length;
    return buf;
  }
}

/** Broadcast-eligible event auth.AuthLoginResponse (typeID 0xc905cafd). */
export class AuthLoginResponse {
  static readonly typeID = 0xc905cafd;
  userID: string = "";
  username: string = "";
  sessionToken: string = "";
  expiresAtMs: number = 0;
  errorCode: number = 0;
  errorMessage: string = "";
  retryAfterMs: number = 0;
  canonical: string = "";

  static decode(buf: Uint8Array): AuthLoginResponse {
    const dv = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
    let off = 0;
    const m = new AuthLoginResponse();
    {
      const sl = dv.getUint16(off, true); off += 2;
      m.userID = new TextDecoder().decode(buf.subarray(off, off + sl)); off += sl;
    }
    {
      const sl = dv.getUint16(off, true); off += 2;
      m.username = new TextDecoder().decode(buf.subarray(off, off + sl)); off += sl;
    }
    {
      const sl = dv.getUint16(off, true); off += 2;
      m.sessionToken = new TextDecoder().decode(buf.subarray(off, off + sl)); off += sl;
    }
    m.expiresAtMs = Number(dv.getBigInt64(off, true)); off += 8;
    m.errorCode = dv.getUint32(off, true); off += 4;
    {
      const sl = dv.getUint16(off, true); off += 2;
      m.errorMessage = new TextDecoder().decode(buf.subarray(off, off + sl)); off += sl;
    }
    m.retryAfterMs = Number(dv.getBigInt64(off, true)); off += 8;
    {
      const sl = dv.getUint16(off, true); off += 2;
      m.canonical = new TextDecoder().decode(buf.subarray(off, off + sl)); off += sl;
    }
    return m;
  }
}

/** Broadcast-eligible event auth.AuthLogoutRequest (typeID 0x885529bc). */
export class AuthLogoutRequest {
  static readonly typeID = 0x885529bc;

  constructor(init?: Partial<AuthLogoutRequest>) {
    if (init) Object.assign(this, init);
  }

  static decode(buf: Uint8Array): AuthLogoutRequest {
    const dv = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
    let off = 0;
    const m = new AuthLogoutRequest();
    return m;
  }

  encode(): Uint8Array {
    const buf = new Uint8Array(0);
    const dv = new DataView(buf.buffer);
    let off = 0;
    return buf;
  }
}

/** Broadcast-eligible event auth.AuthLogoutResponse (typeID 0xb9984dd0). */
export class AuthLogoutResponse {
  static readonly typeID = 0xb9984dd0;
  errorCode: number = 0;
  errorMessage: string = "";

  static decode(buf: Uint8Array): AuthLogoutResponse {
    const dv = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
    let off = 0;
    const m = new AuthLogoutResponse();
    m.errorCode = dv.getUint32(off, true); off += 4;
    {
      const sl = dv.getUint16(off, true); off += 2;
      m.errorMessage = new TextDecoder().decode(buf.subarray(off, off + sl)); off += sl;
    }
    return m;
  }
}

/** Broadcast-eligible event auth.AuthRegisterRequest (typeID 0x322db0e9). */
export class AuthRegisterRequest {
  static readonly typeID = 0x322db0e9;
  username: string = "";
  password: string = "";
  email: string = "";

  constructor(init?: Partial<AuthRegisterRequest>) {
    if (init) Object.assign(this, init);
  }

  static decode(buf: Uint8Array): AuthRegisterRequest {
    const dv = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
    let off = 0;
    const m = new AuthRegisterRequest();
    {
      const sl = dv.getUint16(off, true); off += 2;
      m.username = new TextDecoder().decode(buf.subarray(off, off + sl)); off += sl;
    }
    {
      const sl = dv.getUint16(off, true); off += 2;
      m.password = new TextDecoder().decode(buf.subarray(off, off + sl)); off += sl;
    }
    {
      const sl = dv.getUint16(off, true); off += 2;
      m.email = new TextDecoder().decode(buf.subarray(off, off + sl)); off += sl;
    }
    return m;
  }

  encode(): Uint8Array {
    const _username = new TextEncoder().encode(this.username);
    const _password = new TextEncoder().encode(this.password);
    const _email = new TextEncoder().encode(this.email);
    const buf = new Uint8Array(0 + 2 + _username.length + 2 + _password.length + 2 + _email.length);
    const dv = new DataView(buf.buffer);
    let off = 0;
    dv.setUint16(off, _username.length, true); off += 2;
    buf.set(_username, off); off += _username.length;
    dv.setUint16(off, _password.length, true); off += 2;
    buf.set(_password, off); off += _password.length;
    dv.setUint16(off, _email.length, true); off += 2;
    buf.set(_email, off); off += _email.length;
    return buf;
  }
}

/** Broadcast-eligible event auth.AuthRegisterResponse (typeID 0x9a72b4d7). */
export class AuthRegisterResponse {
  static readonly typeID = 0x9a72b4d7;
  userID: string = "";
  username: string = "";
  sessionToken: string = "";
  expiresAtMs: number = 0;
  errorCode: number = 0;
  errorMessage: string = "";
  retryAfterMs: number = 0;
  canonical: string = "";

  static decode(buf: Uint8Array): AuthRegisterResponse {
    const dv = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
    let off = 0;
    const m = new AuthRegisterResponse();
    {
      const sl = dv.getUint16(off, true); off += 2;
      m.userID = new TextDecoder().decode(buf.subarray(off, off + sl)); off += sl;
    }
    {
      const sl = dv.getUint16(off, true); off += 2;
      m.username = new TextDecoder().decode(buf.subarray(off, off + sl)); off += sl;
    }
    {
      const sl = dv.getUint16(off, true); off += 2;
      m.sessionToken = new TextDecoder().decode(buf.subarray(off, off + sl)); off += sl;
    }
    m.expiresAtMs = Number(dv.getBigInt64(off, true)); off += 8;
    m.errorCode = dv.getUint32(off, true); off += 4;
    {
      const sl = dv.getUint16(off, true); off += 2;
      m.errorMessage = new TextDecoder().decode(buf.subarray(off, off + sl)); off += sl;
    }
    m.retryAfterMs = Number(dv.getBigInt64(off, true)); off += 8;
    {
      const sl = dv.getUint16(off, true); off += 2;
      m.canonical = new TextDecoder().decode(buf.subarray(off, off + sl)); off += sl;
    }
    return m;
  }
}

/** Broadcast-eligible event auth.AuthValidateTokenRequest (typeID 0xf8171c71). */
export class AuthValidateTokenRequest {
  static readonly typeID = 0xf8171c71;
  sessionToken: string = "";

  constructor(init?: Partial<AuthValidateTokenRequest>) {
    if (init) Object.assign(this, init);
  }

  static decode(buf: Uint8Array): AuthValidateTokenRequest {
    const dv = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
    let off = 0;
    const m = new AuthValidateTokenRequest();
    {
      const sl = dv.getUint16(off, true); off += 2;
      m.sessionToken = new TextDecoder().decode(buf.subarray(off, off + sl)); off += sl;
    }
    return m;
  }

  encode(): Uint8Array {
    const _sessionToken = new TextEncoder().encode(this.sessionToken);
    const buf = new Uint8Array(0 + 2 + _sessionToken.length);
    const dv = new DataView(buf.buffer);
    let off = 0;
    dv.setUint16(off, _sessionToken.length, true); off += 2;
    buf.set(_sessionToken, off); off += _sessionToken.length;
    return buf;
  }
}

/** Broadcast-eligible event auth.AuthValidateTokenResponse (typeID 0x94868d2f). */
export class AuthValidateTokenResponse {
  static readonly typeID = 0x94868d2f;
  userID: string = "";
  username: string = "";
  expiresAtMs: number = 0;
  errorCode: number = 0;
  errorMessage: string = "";
  retryAfterMs: number = 0;

  static decode(buf: Uint8Array): AuthValidateTokenResponse {
    const dv = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
    let off = 0;
    const m = new AuthValidateTokenResponse();
    {
      const sl = dv.getUint16(off, true); off += 2;
      m.userID = new TextDecoder().decode(buf.subarray(off, off + sl)); off += sl;
    }
    {
      const sl = dv.getUint16(off, true); off += 2;
      m.username = new TextDecoder().decode(buf.subarray(off, off + sl)); off += sl;
    }
    m.expiresAtMs = Number(dv.getBigInt64(off, true)); off += 8;
    m.errorCode = dv.getUint32(off, true); off += 4;
    {
      const sl = dv.getUint16(off, true); off += 2;
      m.errorMessage = new TextDecoder().decode(buf.subarray(off, off + sl)); off += sl;
    }
    m.retryAfterMs = Number(dv.getBigInt64(off, true)); off += 8;
    return m;
  }
}

/** Broadcast-eligible event game.BankRequest (typeID 0xeaffc856). */
export class BankRequest {
  static readonly typeID = 0xeaffc856;
  sequence: number = 0;

  constructor(init?: Partial<BankRequest>) {
    if (init) Object.assign(this, init);
  }

  static decode(buf: Uint8Array): BankRequest {
    const dv = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
    let off = 0;
    const m = new BankRequest();
    m.sequence = dv.getUint32(off, true); off += 4;
    return m;
  }

  encode(): Uint8Array {
    const buf = new Uint8Array(4);
    const dv = new DataView(buf.buffer);
    let off = 0;
    dv.setUint32(off, this.sequence, true); off += 4;
    return buf;
  }
}

/** Broadcast-eligible event game.BankResponse (typeID 0xcef152aa). */
export class BankResponse {
  static readonly typeID = 0xcef152aa;
  contents: { items: { itemID: number; quantity: number }[]; totalMass: number; maxMass: number; cargoItems: { itemID: number; quantity: number }[]; cargoMass: number; maxCargoMass: number; currencies: { currencyID: number; balance: number }[] } = { items: [], totalMass: 0, maxMass: 0, cargoItems: [], cargoMass: 0, maxCargoMass: 0, currencies: [] };
  error: string = "";

  static decode(buf: Uint8Array): BankResponse {
    const dv = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
    let off = 0;
    const m = new BankResponse();
    {
      const sliceLen = dv.getUint16(off, true); off += 2;
      for (let i = 0; i < sliceLen; i++) {
        const item: { itemID: number; quantity: number } = { itemID: 0, quantity: 0 };
            item.itemID = dv.getUint32(off, true); off += 4;
            item.quantity = dv.getInt32(off, true); off += 4;
        m.contents.items.push(item);
      }
    }
    m.contents.totalMass = dv.getFloat32(off, true); off += 4;
    m.contents.maxMass = dv.getFloat32(off, true); off += 4;
    {
      const sliceLen = dv.getUint16(off, true); off += 2;
      for (let i = 0; i < sliceLen; i++) {
        const item: { itemID: number; quantity: number } = { itemID: 0, quantity: 0 };
            item.itemID = dv.getUint32(off, true); off += 4;
            item.quantity = dv.getInt32(off, true); off += 4;
        m.contents.cargoItems.push(item);
      }
    }
    m.contents.cargoMass = dv.getFloat32(off, true); off += 4;
    m.contents.maxCargoMass = dv.getFloat32(off, true); off += 4;
    {
      const sliceLen = dv.getUint16(off, true); off += 2;
      for (let i = 0; i < sliceLen; i++) {
        const item: { currencyID: number; balance: number } = { currencyID: 0, balance: 0 };
            item.currencyID = dv.getUint32(off, true); off += 4;
            item.balance = Number(dv.getBigInt64(off, true)); off += 8;
        m.contents.currencies.push(item);
      }
    }
    {
      const sl = dv.getUint16(off, true); off += 2;
      m.error = new TextDecoder().decode(buf.subarray(off, off + sl)); off += sl;
    }
    return m;
  }
}

/** Broadcast-eligible event marketplace.MarketBrowseRequest (typeID 0xd952f5a1). */
export class MarketBrowseRequest {
  static readonly typeID = 0xd952f5a1;
  itemID: number = 0;

  constructor(init?: Partial<MarketBrowseRequest>) {
    if (init) Object.assign(this, init);
  }

  static decode(buf: Uint8Array): MarketBrowseRequest {
    const dv = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
    let off = 0;
    const m = new MarketBrowseRequest();
    m.itemID = dv.getUint32(off, true); off += 4;
    return m;
  }

  encode(): Uint8Array {
    const buf = new Uint8Array(4);
    const dv = new DataView(buf.buffer);
    let off = 0;
    dv.setUint32(off, this.itemID, true); off += 4;
    return buf;
  }
}

/** Broadcast-eligible event marketplace.MarketOrderBookResponse (typeID 0xf91acf2c). */
export class MarketOrderBookResponse {
  static readonly typeID = 0xf91acf2c;
  itemID: number = 0;
  sellLevels: { price: number; quantity: number; orderCount: number }[] = [];
  buyLevels: { price: number; quantity: number; orderCount: number }[] = [];

  static decode(buf: Uint8Array): MarketOrderBookResponse {
    const dv = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
    let off = 0;
    const m = new MarketOrderBookResponse();
    m.itemID = dv.getUint32(off, true); off += 4;
    {
      const sliceLen = dv.getUint16(off, true); off += 2;
      for (let i = 0; i < sliceLen; i++) {
        const item: { price: number; quantity: number; orderCount: number } = { price: 0, quantity: 0, orderCount: 0 };
            item.price = Number(dv.getBigInt64(off, true)); off += 8;
            item.quantity = dv.getInt32(off, true); off += 4;
            item.orderCount = dv.getUint32(off, true); off += 4;
        m.sellLevels.push(item);
      }
    }
    {
      const sliceLen = dv.getUint16(off, true); off += 2;
      for (let i = 0; i < sliceLen; i++) {
        const item: { price: number; quantity: number; orderCount: number } = { price: 0, quantity: 0, orderCount: 0 };
            item.price = Number(dv.getBigInt64(off, true)); off += 8;
            item.quantity = dv.getInt32(off, true); off += 4;
            item.orderCount = dv.getUint32(off, true); off += 4;
        m.buyLevels.push(item);
      }
    }
    return m;
  }
}

/** Broadcast-eligible event marketplace.MarketCancelOrderRequest (typeID 0xbba72b09). */
export class MarketCancelOrderRequest {
  static readonly typeID = 0xbba72b09;
  orderID: number = 0;

  constructor(init?: Partial<MarketCancelOrderRequest>) {
    if (init) Object.assign(this, init);
  }

  static decode(buf: Uint8Array): MarketCancelOrderRequest {
    const dv = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
    let off = 0;
    const m = new MarketCancelOrderRequest();
    m.orderID = Number(dv.getBigUint64(off, true)); off += 8;
    return m;
  }

  encode(): Uint8Array {
    const buf = new Uint8Array(8);
    const dv = new DataView(buf.buffer);
    let off = 0;
    dv.setBigUint64(off, BigInt(this.orderID), true); off += 8;
    return buf;
  }
}

/** Broadcast-eligible event marketplace.MarketOrderResultResponse (typeID 0x73dff760). */
export class MarketOrderResultResponse {
  static readonly typeID = 0x73dff760;
  orderID: number = 0;
  filledQty: number = 0;
  avgPrice: number = 0;
  totalCost: number = 0;

  static decode(buf: Uint8Array): MarketOrderResultResponse {
    const dv = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
    let off = 0;
    const m = new MarketOrderResultResponse();
    m.orderID = Number(dv.getBigUint64(off, true)); off += 8;
    m.filledQty = dv.getInt32(off, true); off += 4;
    m.avgPrice = Number(dv.getBigInt64(off, true)); off += 8;
    m.totalCost = Number(dv.getBigInt64(off, true)); off += 8;
    return m;
  }
}

/** Broadcast-eligible event marketplace.MarketCreateOrderRequest (typeID 0x68c76c93). */
export class MarketCreateOrderRequest {
  static readonly typeID = 0x68c76c93;
  itemID: number = 0;
  isBuy: boolean = false;
  pricePerUnit: number = 0;
  quantity: number = 0;

  constructor(init?: Partial<MarketCreateOrderRequest>) {
    if (init) Object.assign(this, init);
  }

  static decode(buf: Uint8Array): MarketCreateOrderRequest {
    const dv = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
    let off = 0;
    const m = new MarketCreateOrderRequest();
    m.itemID = dv.getUint32(off, true); off += 4;
    m.isBuy = dv.getUint8(off) !== 0; off += 1;
    m.pricePerUnit = Number(dv.getBigInt64(off, true)); off += 8;
    m.quantity = dv.getInt32(off, true); off += 4;
    return m;
  }

  encode(): Uint8Array {
    const buf = new Uint8Array(17);
    const dv = new DataView(buf.buffer);
    let off = 0;
    dv.setUint32(off, this.itemID, true); off += 4;
    dv.setUint8(off, this.isBuy ? 1 : 0); off += 1;
    dv.setBigInt64(off, BigInt(this.pricePerUnit), true); off += 8;
    dv.setInt32(off, this.quantity, true); off += 4;
    return buf;
  }
}

/** Broadcast-eligible event marketplace.MarketInstantTradeRequest (typeID 0x866d7e60). */
export class MarketInstantTradeRequest {
  static readonly typeID = 0x866d7e60;
  itemID: number = 0;
  isBuy: boolean = false;
  quantity: number = 0;

  constructor(init?: Partial<MarketInstantTradeRequest>) {
    if (init) Object.assign(this, init);
  }

  static decode(buf: Uint8Array): MarketInstantTradeRequest {
    const dv = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
    let off = 0;
    const m = new MarketInstantTradeRequest();
    m.itemID = dv.getUint32(off, true); off += 4;
    m.isBuy = dv.getUint8(off) !== 0; off += 1;
    m.quantity = dv.getInt32(off, true); off += 4;
    return m;
  }

  encode(): Uint8Array {
    const buf = new Uint8Array(9);
    const dv = new DataView(buf.buffer);
    let off = 0;
    dv.setUint32(off, this.itemID, true); off += 4;
    dv.setUint8(off, this.isBuy ? 1 : 0); off += 1;
    dv.setInt32(off, this.quantity, true); off += 4;
    return buf;
  }
}

/** Broadcast-eligible event marketplace.MarketMyOrdersRequest (typeID 0x28856172). */
export class MarketMyOrdersRequest {
  static readonly typeID = 0x28856172;

  constructor(init?: Partial<MarketMyOrdersRequest>) {
    if (init) Object.assign(this, init);
  }

  static decode(buf: Uint8Array): MarketMyOrdersRequest {
    const dv = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
    let off = 0;
    const m = new MarketMyOrdersRequest();
    return m;
  }

  encode(): Uint8Array {
    const buf = new Uint8Array(0);
    const dv = new DataView(buf.buffer);
    let off = 0;
    return buf;
  }
}

/** Broadcast-eligible event marketplace.MarketMyOrdersResponse (typeID 0x18dac19e). */
export class MarketMyOrdersResponse {
  static readonly typeID = 0x18dac19e;
  orders: { orderID: number; itemID: number; isBuy: boolean; pricePerUnit: number; quantity: number; origQuantity: number; createdAt: number; expiresAt: number }[] = [];

  static decode(buf: Uint8Array): MarketMyOrdersResponse {
    const dv = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
    let off = 0;
    const m = new MarketMyOrdersResponse();
    {
      const sliceLen = dv.getUint16(off, true); off += 2;
      for (let i = 0; i < sliceLen; i++) {
        const item: { orderID: number; itemID: number; isBuy: boolean; pricePerUnit: number; quantity: number; origQuantity: number; createdAt: number; expiresAt: number } = { orderID: 0, itemID: 0, isBuy: false, pricePerUnit: 0, quantity: 0, origQuantity: 0, createdAt: 0, expiresAt: 0 };
            item.orderID = Number(dv.getBigUint64(off, true)); off += 8;
            item.itemID = dv.getUint32(off, true); off += 4;
            item.isBuy = dv.getUint8(off) !== 0; off += 1;
            item.pricePerUnit = Number(dv.getBigInt64(off, true)); off += 8;
            item.quantity = dv.getInt32(off, true); off += 4;
            item.origQuantity = dv.getInt32(off, true); off += 4;
            item.createdAt = Number(dv.getBigInt64(off, true)); off += 8;
            item.expiresAt = Number(dv.getBigInt64(off, true)); off += 8;
        m.orders.push(item);
      }
    }
    return m;
  }
}

