// GENERATED by sdkgen — do not edit.

// Typed operation Request + Response classes. Wire format:
//   [0x01][typeID:u32 LE][request_id:u64 LE][body_len:u32 LE][body]
// Bodies use the reflect-codec layout from pkg/universe/reflect_marshal.go
// (matches broadcasts.ts and inputs.ts).

/** Broadcast-eligible event game.BankRequest (typeID 0xeaffc856). */
export class BankRequest {
  static readonly typeID = 0xeaffc856;
  sequence: number = 0;

  constructor(init?: Partial<BankRequest>) {
    if (init) Object.assign(this, init);
  }

  static decode(buf: Uint8Array): BankRequest {
    const dv = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
    let off = 0;
    const m = new BankRequest();
    m.sequence = dv.getUint32(off, true); off += 4;
    return m;
  }

  encode(): Uint8Array {
    const buf = new Uint8Array(4);
    const dv = new DataView(buf.buffer);
    let off = 0;
    dv.setUint32(off, this.sequence, true); off += 4;
    return buf;
  }
}

/** Broadcast-eligible event game.BankResponse (typeID 0xcef152aa). */
export class BankResponse {
  static readonly typeID = 0xcef152aa;
  contents: { items: { itemID: number; quantity: number }[]; totalMass: number; maxMass: number; cargoItems: { itemID: number; quantity: number }[]; cargoMass: number; maxCargoMass: number; currencies: { currencyID: number; balance: number }[] } = { items: [], totalMass: 0, maxMass: 0, cargoItems: [], cargoMass: 0, maxCargoMass: 0, currencies: [] };
  error: string = "";

  static decode(buf: Uint8Array): BankResponse {
    const dv = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
    let off = 0;
    const m = new BankResponse();
    {
      const sliceLen = dv.getUint16(off, true); off += 2;
      for (let i = 0; i < sliceLen; i++) {
        const item: { itemID: number; quantity: number } = { itemID: 0, quantity: 0 };
            item.itemID = dv.getUint32(off, true); off += 4;
            item.quantity = dv.getInt32(off, true); off += 4;
        m.contents.items.push(item);
      }
    }
    m.contents.totalMass = dv.getFloat32(off, true); off += 4;
    m.contents.maxMass = dv.getFloat32(off, true); off += 4;
    {
      const sliceLen = dv.getUint16(off, true); off += 2;
      for (let i = 0; i < sliceLen; i++) {
        const item: { itemID: number; quantity: number } = { itemID: 0, quantity: 0 };
            item.itemID = dv.getUint32(off, true); off += 4;
            item.quantity = dv.getInt32(off, true); off += 4;
        m.contents.cargoItems.push(item);
      }
    }
    m.contents.cargoMass = dv.getFloat32(off, true); off += 4;
    m.contents.maxCargoMass = dv.getFloat32(off, true); off += 4;
    {
      const sliceLen = dv.getUint16(off, true); off += 2;
      for (let i = 0; i < sliceLen; i++) {
        const item: { currencyID: number; balance: number } = { currencyID: 0, balance: 0 };
            item.currencyID = dv.getUint32(off, true); off += 4;
            item.balance = Number(dv.getBigInt64(off, true)); off += 8;
        m.contents.currencies.push(item);
      }
    }
    {
      const sl = dv.getUint16(off, true); off += 2;
      m.error = new TextDecoder().decode(buf.subarray(off, off + sl)); off += sl;
    }
    return m;
  }
}

/** Broadcast-eligible event marketplace.MarketBrowseRequest (typeID 0xd952f5a1). */
export class MarketBrowseRequest {
  static readonly typeID = 0xd952f5a1;
  itemID: number = 0;

  constructor(init?: Partial<MarketBrowseRequest>) {
    if (init) Object.assign(this, init);
  }

  static decode(buf: Uint8Array): MarketBrowseRequest {
    const dv = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
    let off = 0;
    const m = new MarketBrowseRequest();
    m.itemID = dv.getUint32(off, true); off += 4;
    return m;
  }

  encode(): Uint8Array {
    const buf = new Uint8Array(4);
    const dv = new DataView(buf.buffer);
    let off = 0;
    dv.setUint32(off, this.itemID, true); off += 4;
    return buf;
  }
}

/** Broadcast-eligible event marketplace.MarketOrderBookResponse (typeID 0xf91acf2c). */
export class MarketOrderBookResponse {
  static readonly typeID = 0xf91acf2c;
  itemID: number = 0;
  sellLevels: { price: number; quantity: number; orderCount: number }[] = [];
  buyLevels: { price: number; quantity: number; orderCount: number }[] = [];

  static decode(buf: Uint8Array): MarketOrderBookResponse {
    const dv = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
    let off = 0;
    const m = new MarketOrderBookResponse();
    m.itemID = dv.getUint32(off, true); off += 4;
    {
      const sliceLen = dv.getUint16(off, true); off += 2;
      for (let i = 0; i < sliceLen; i++) {
        const item: { price: number; quantity: number; orderCount: number } = { price: 0, quantity: 0, orderCount: 0 };
            item.price = Number(dv.getBigInt64(off, true)); off += 8;
            item.quantity = dv.getInt32(off, true); off += 4;
            item.orderCount = dv.getUint32(off, true); off += 4;
        m.sellLevels.push(item);
      }
    }
    {
      const sliceLen = dv.getUint16(off, true); off += 2;
      for (let i = 0; i < sliceLen; i++) {
        const item: { price: number; quantity: number; orderCount: number } = { price: 0, quantity: 0, orderCount: 0 };
            item.price = Number(dv.getBigInt64(off, true)); off += 8;
            item.quantity = dv.getInt32(off, true); off += 4;
            item.orderCount = dv.getUint32(off, true); off += 4;
        m.buyLevels.push(item);
      }
    }
    return m;
  }
}

/** Broadcast-eligible event marketplace.MarketCancelOrderRequest (typeID 0xbba72b09). */
export class MarketCancelOrderRequest {
  static readonly typeID = 0xbba72b09;
  orderID: number = 0;

  constructor(init?: Partial<MarketCancelOrderRequest>) {
    if (init) Object.assign(this, init);
  }

  static decode(buf: Uint8Array): MarketCancelOrderRequest {
    const dv = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
    let off = 0;
    const m = new MarketCancelOrderRequest();
    m.orderID = Number(dv.getBigUint64(off, true)); off += 8;
    return m;
  }

  encode(): Uint8Array {
    const buf = new Uint8Array(8);
    const dv = new DataView(buf.buffer);
    let off = 0;
    dv.setBigUint64(off, BigInt(this.orderID), true); off += 8;
    return buf;
  }
}

/** Broadcast-eligible event marketplace.MarketOrderResultResponse (typeID 0x73dff760). */
export class MarketOrderResultResponse {
  static readonly typeID = 0x73dff760;
  orderID: number = 0;
  filledQty: number = 0;
  avgPrice: number = 0;
  totalCost: number = 0;

  static decode(buf: Uint8Array): MarketOrderResultResponse {
    const dv = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
    let off = 0;
    const m = new MarketOrderResultResponse();
    m.orderID = Number(dv.getBigUint64(off, true)); off += 8;
    m.filledQty = dv.getInt32(off, true); off += 4;
    m.avgPrice = Number(dv.getBigInt64(off, true)); off += 8;
    m.totalCost = Number(dv.getBigInt64(off, true)); off += 8;
    return m;
  }
}

/** Broadcast-eligible event marketplace.MarketCreateOrderRequest (typeID 0x68c76c93). */
export class MarketCreateOrderRequest {
  static readonly typeID = 0x68c76c93;
  itemID: number = 0;
  isBuy: boolean = false;
  pricePerUnit: number = 0;
  quantity: number = 0;

  constructor(init?: Partial<MarketCreateOrderRequest>) {
    if (init) Object.assign(this, init);
  }

  static decode(buf: Uint8Array): MarketCreateOrderRequest {
    const dv = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
    let off = 0;
    const m = new MarketCreateOrderRequest();
    m.itemID = dv.getUint32(off, true); off += 4;
    m.isBuy = dv.getUint8(off) !== 0; off += 1;
    m.pricePerUnit = Number(dv.getBigInt64(off, true)); off += 8;
    m.quantity = dv.getInt32(off, true); off += 4;
    return m;
  }

  encode(): Uint8Array {
    const buf = new Uint8Array(17);
    const dv = new DataView(buf.buffer);
    let off = 0;
    dv.setUint32(off, this.itemID, true); off += 4;
    dv.setUint8(off, this.isBuy ? 1 : 0); off += 1;
    dv.setBigInt64(off, BigInt(this.pricePerUnit), true); off += 8;
    dv.setInt32(off, this.quantity, true); off += 4;
    return buf;
  }
}

/** Broadcast-eligible event marketplace.MarketInstantTradeRequest (typeID 0x866d7e60). */
export class MarketInstantTradeRequest {
  static readonly typeID = 0x866d7e60;
  itemID: number = 0;
  isBuy: boolean = false;
  quantity: number = 0;

  constructor(init?: Partial<MarketInstantTradeRequest>) {
    if (init) Object.assign(this, init);
  }

  static decode(buf: Uint8Array): MarketInstantTradeRequest {
    const dv = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
    let off = 0;
    const m = new MarketInstantTradeRequest();
    m.itemID = dv.getUint32(off, true); off += 4;
    m.isBuy = dv.getUint8(off) !== 0; off += 1;
    m.quantity = dv.getInt32(off, true); off += 4;
    return m;
  }

  encode(): Uint8Array {
    const buf = new Uint8Array(9);
    const dv = new DataView(buf.buffer);
    let off = 0;
    dv.setUint32(off, this.itemID, true); off += 4;
    dv.setUint8(off, this.isBuy ? 1 : 0); off += 1;
    dv.setInt32(off, this.quantity, true); off += 4;
    return buf;
  }
}

/** Broadcast-eligible event marketplace.MarketMyOrdersRequest (typeID 0x28856172). */
export class MarketMyOrdersRequest {
  static readonly typeID = 0x28856172;

  constructor(init?: Partial<MarketMyOrdersRequest>) {
    if (init) Object.assign(this, init);
  }

  static decode(buf: Uint8Array): MarketMyOrdersRequest {
    const dv = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
    let off = 0;
    const m = new MarketMyOrdersRequest();
    return m;
  }

  encode(): Uint8Array {
    const buf = new Uint8Array(0);
    const dv = new DataView(buf.buffer);
    let off = 0;
    return buf;
  }
}

/** Broadcast-eligible event marketplace.MarketMyOrdersResponse (typeID 0x18dac19e). */
export class MarketMyOrdersResponse {
  static readonly typeID = 0x18dac19e;
  orders: { orderID: number; itemID: number; isBuy: boolean; pricePerUnit: number; quantity: number; origQuantity: number; createdAt: number; expiresAt: number }[] = [];

  static decode(buf: Uint8Array): MarketMyOrdersResponse {
    const dv = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
    let off = 0;
    const m = new MarketMyOrdersResponse();
    {
      const sliceLen = dv.getUint16(off, true); off += 2;
      for (let i = 0; i < sliceLen; i++) {
        const item: { orderID: number; itemID: number; isBuy: boolean; pricePerUnit: number; quantity: number; origQuantity: number; createdAt: number; expiresAt: number } = { orderID: 0, itemID: 0, isBuy: false, pricePerUnit: 0, quantity: 0, origQuantity: 0, createdAt: 0, expiresAt: 0 };
            item.orderID = Number(dv.getBigUint64(off, true)); off += 8;
            item.itemID = dv.getUint32(off, true); off += 4;
            item.isBuy = dv.getUint8(off) !== 0; off += 1;
            item.pricePerUnit = Number(dv.getBigInt64(off, true)); off += 8;
            item.quantity = dv.getInt32(off, true); off += 4;
            item.origQuantity = dv.getInt32(off, true); off += 4;
            item.createdAt = Number(dv.getBigInt64(off, true)); off += 8;
            item.expiresAt = Number(dv.getBigInt64(off, true)); off += 8;
        m.orders.push(item);
      }
    }
    return m;
  }
}

