// GENERATED by sdkgen — do not edit.

const CH_EVENT = 0x00;
const CH_OPERATION = 0x01;

export type MessageHandler = (data: Uint8Array) => void;

export class Transport {
  private ws: WebSocket | null = null;
  private eventHandlers: MessageHandler[] = [];
  private operationHandlers: MessageHandler[] = [];

  constructor(private url: string) {}

  connect(): void {
    this.ws = new WebSocket(this.url);
    this.ws.binaryType = "arraybuffer";
    this.ws.onmessage = (ev) => {
      const data = new Uint8Array(ev.data as ArrayBuffer);
      if (data.length < 1) return;
      const channel = data[0];
      const payload = data.subarray(1);
      if (channel === CH_EVENT) {
        for (const h of this.eventHandlers) h(payload);
      } else if (channel === CH_OPERATION) {
        for (const h of this.operationHandlers) h(payload);
      }
    };
  }

  get socket(): WebSocket | null { return this.ws; }
  get connected(): boolean { return this.ws?.readyState === WebSocket.OPEN; }

  close(): void { this.ws?.close(); this.ws = null; }

  sendEvent(data: Uint8Array): void {
    if (!this.ws || this.ws.readyState !== WebSocket.OPEN) return;
    const frame = new Uint8Array(1 + data.length);
    frame[0] = CH_EVENT;
    frame.set(data, 1);
    this.ws.send(frame);
  }

  sendOperation(data: Uint8Array): void {
    if (!this.ws || this.ws.readyState !== WebSocket.OPEN) return;
    const frame = new Uint8Array(1 + data.length);
    frame[0] = CH_OPERATION;
    frame.set(data, 1);
    this.ws.send(frame);
  }

  onEvent(handler: MessageHandler): void { this.eventHandlers.push(handler); }
  onOperation(handler: MessageHandler): void { this.operationHandlers.push(handler); }
}
