#!/usr/bin/env python3
"""Synthesise the space example's sound effects and ambient pad.

Every audio file this example ships is generated by this script. Nothing is
sampled, recorded, or downloaded, which makes the whole set original work under
the repository's MIT licence with no third-party provenance to establish. It
also matches how the rest of the example's presentation works: the art is drawn
procedurally with PixiJS Graphics rather than loaded from image files.

    python3 examples/space/web/tools/gen-audio.py

Output goes to examples/space/web/public/audio/. Filenames are the contract —
SoundId in ../src/audio/sounds.ts keys sounds by filename — so the names below
must not change without changing that file too.

Deterministic: noise runs off a fixed seed, so regenerating produces
byte-identical WAV input for a given ffmpeg build. Requires ffmpeg for Vorbis
encoding; everything before that is the Python standard library.
"""

import math
import os
import random
import struct
import subprocess
import sys
import tempfile
import wave

SR = 44100
SEED = 0x5C0DE

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "public", "audio")


# ── synthesis primitives ────────────────────────────────────────────────────

def frames(dur):
    return int(SR * dur)


def silence(dur):
    return [0.0] * frames(dur)


def sine(dur, f0, f1=None, phase=0.0):
    """Sine with an optional exponential pitch sweep from f0 to f1."""
    n = frames(dur)
    f1 = f0 if f1 is None else f1
    out = [0.0] * n
    ph = phase
    for i in range(n):
        t = i / max(n - 1, 1)
        f = f0 * (f1 / f0) ** t if f0 > 0 and f1 > 0 else f0
        ph += 2.0 * math.pi * f / SR
        out[i] = math.sin(ph)
    return out


def saw(dur, f0, f1=None):
    n = frames(dur)
    f1 = f0 if f1 is None else f1
    out = [0.0] * n
    ph = 0.0
    for i in range(n):
        t = i / max(n - 1, 1)
        f = f0 * (f1 / f0) ** t
        ph = (ph + f / SR) % 1.0
        out[i] = 2.0 * ph - 1.0
    return out


def noise(dur, rng):
    return [rng.uniform(-1.0, 1.0) for _ in range(frames(dur))]


def lowpass(sig, cutoff):
    """One-pole lowpass. Cheap, and the character is right for this material."""
    if cutoff <= 0:
        return [0.0] * len(sig)
    a = 1.0 - math.exp(-2.0 * math.pi * cutoff / SR)
    out = [0.0] * len(sig)
    y = 0.0
    for i, x in enumerate(sig):
        y += a * (x - y)
        out[i] = y
    return out


def highpass(sig, cutoff):
    lp = lowpass(sig, cutoff)
    return [x - y for x, y in zip(sig, lp)]


def env_exp(sig, decay, attack=0.004):
    """Percussive envelope: short linear attack, exponential decay."""
    n = len(sig)
    at = max(int(SR * attack), 1)
    out = [0.0] * n
    for i, x in enumerate(sig):
        a = i / at if i < at else math.exp(-(i - at) / (SR * decay))
        out[i] = x * a
    return out


def env_ad(sig, attack, release):
    """Linear attack, linear release, sustain in between."""
    n = len(sig)
    at, rl = max(int(SR * attack), 1), max(int(SR * release), 1)
    out = [0.0] * n
    for i, x in enumerate(sig):
        a = 1.0
        if i < at:
            a = i / at
        elif i > n - rl:
            a = max(n - i, 0) / rl
        out[i] = x * a
    return out


def tremolo(sig, rate, depth=0.5):
    return [x * (1.0 - depth + depth * (0.5 + 0.5 * math.sin(2 * math.pi * rate * i / SR)))
            for i, x in enumerate(sig)]


def mix(*sigs):
    n = max(len(s) for s in sigs)
    out = [0.0] * n
    for s in sigs:
        for i, x in enumerate(s):
            out[i] += x
    return out


def gain(sig, g):
    return [x * g for x in sig]


def normalize(sig, peak=0.89):
    m = max((abs(x) for x in sig), default=0.0)
    return sig if m == 0 else [x * peak / m for x in sig]


def loopify(sig, fade=0.25):
    """Make a buffer seamless by crossfading its tail over its head.

    The three looping sounds (thruster, mining laser, ambient pad) are played
    with loop:true in sounds.ts; without this the wrap produces an audible
    click on every repeat.
    """
    n = len(sig)
    f = min(int(SR * fade), n // 2)
    out = sig[: n - f]
    for i in range(f):
        a = i / f
        out[i] = sig[n - f + i] * (1.0 - a) + out[i] * a
    return out


def write(name, sig, quality="4"):
    path = os.path.join(OUT, name)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    sig = normalize(sig)
    with tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as tmp:
        wav_path = tmp.name
    try:
        with wave.open(wav_path, "wb") as w:
            w.setnchannels(1)
            w.setsampwidth(2)
            w.setframerate(SR)
            w.writeframes(b"".join(
                struct.pack("<h", max(-32768, min(32767, int(x * 32767)))) for x in sig))
        subprocess.run(
            # -ac 2: ffmpeg's native Vorbis encoder refuses mono. The source
            # is mono, so this duplicates the channel; the size cost is small
            # at these durations and it keeps the files Ogg Vorbis, which every
            # current browser decodes.
            ["ffmpeg", "-hide_banner", "-loglevel", "error", "-y",
             "-i", wav_path, "-ac", "2", "-c:a", "vorbis", "-strict", "-2",
             "-q:a", quality, path],
            check=True)
    finally:
        os.unlink(wav_path)
    print(f"  {name:38s} {os.path.getsize(path):>8,d} bytes  {len(sig)/SR:5.2f}s")


# ── the sixteen sounds ──────────────────────────────────────────────────────

def build():
    rng = random.Random(SEED)
    print("sfx/")

    # Weapons.
    write("sfx/missile-launch.ogg", mix(
        env_exp(lowpass(noise(0.9, rng), 2600), 0.30, attack=0.02),
        gain(env_exp(sine(0.9, 180, 60), 0.22), 0.7)))

    write("sfx/railgun-fire.ogg", mix(
        gain(env_exp(highpass(noise(0.45, rng), 1800), 0.05, attack=0.001), 0.9),
        gain(env_exp(sine(0.45, 900, 90), 0.12, attack=0.001), 0.8)))

    write("sfx/ion-burn.ogg", env_ad(
        tremolo(lowpass(mix(saw(0.8, 220), gain(saw(0.8, 223), 0.8)), 2200), 34, 0.55),
        0.05, 0.35))

    write("sfx/plasma-torpedo.ogg", mix(
        env_exp(sine(0.7, 320, 70), 0.20, attack=0.006),
        gain(env_exp(lowpass(noise(0.7, rng), 1400), 0.16), 0.55)))

    # Defence and propulsion.
    write("sfx/shield-activate.ogg", mix(
        env_ad(sine(0.7, 440, 880), 0.02, 0.45),
        gain(env_ad(sine(0.7, 660, 1320), 0.03, 0.45), 0.5),
        gain(env_exp(highpass(noise(0.7, rng), 4000), 0.18), 0.25)))

    write("sfx/afterburner.ogg", env_ad(
        lowpass(noise(1.2, rng), 900), 0.25, 0.5))

    # Looping: seamless.
    write("sfx/thruster.ogg", loopify(
        gain(lowpass(noise(2.0, rng), 520), 0.9), fade=0.4))

    write("sfx/mining-laser.ogg", loopify(mix(
        tremolo(gain(sine(2.0, 330), 0.55), 21, 0.4),
        tremolo(gain(sine(2.0, 495), 0.25), 21, 0.4),
        gain(lowpass(noise(2.0, rng), 3000), 0.18)), fade=0.4))

    # Mining and loot.
    write("sfx/extract-pulse.ogg", env_exp(sine(0.25, 520, 1040), 0.07, attack=0.003))

    write("sfx/loot-pickup.ogg", mix(
        env_exp(sine(0.16, 784), 0.07, attack=0.002),
        silence(0.10) + env_exp(sine(0.25, 1175), 0.09, attack=0.002)))

    # Impacts.
    write("sfx/explosion.ogg", mix(
        env_exp(lowpass(noise(1.4, rng), 1700), 0.34, attack=0.002),
        gain(env_exp(sine(1.4, 110, 34), 0.42, attack=0.002), 0.85)))

    write("sfx/hit-impact.ogg", mix(
        env_exp(highpass(noise(0.2, rng), 1200), 0.045, attack=0.001),
        gain(env_exp(sine(0.2, 260, 110), 0.05, attack=0.001), 0.6)))

    # Utility and UI.
    write("sfx/tractor-beam.ogg", env_ad(
        tremolo(lowpass(mix(saw(1.0, 90), gain(sine(1.0, 45), 0.6)), 700), 6.5, 0.7),
        0.12, 0.3))

    write("sfx/target-lock.ogg", mix(
        env_exp(sine(0.10, 1320), 0.035, attack=0.002),
        silence(0.16) + env_exp(sine(0.14, 1760), 0.045, attack=0.002)))

    write("sfx/ui-click.ogg", env_exp(
        highpass(noise(0.08, rng), 2400), 0.014, attack=0.0006))

    # Ambient pad: quiet, slow, seamless. Kept to 40 s rather than the several
    # minutes a hand-authored track would run — it loops, and every committed
    # byte is in every clone forever.
    print("music/")
    dur = 40.0
    pad = mix(
        gain(sine(dur, 55.0), 0.55),
        gain(sine(dur, 82.5), 0.30),
        gain(sine(dur, 110.0), 0.22),
        gain(sine(dur, 164.8), 0.10),
        gain(lowpass(noise(dur, rng), 220), 0.28))
    # Two detuned slow LFOs so the loop point is hard to hear.
    pad = [x * (0.72
                + 0.18 * math.sin(2 * math.pi * (1 / 20.0) * i / SR)
                + 0.10 * math.sin(2 * math.pi * (1 / 13.0) * i / SR))
           for i, x in enumerate(pad)]
    write("music/space-ambient.ogg", loopify(lowpass(pad, 1200), fade=4.0), quality="2")


if __name__ == "__main__":
    if subprocess.run(["ffmpeg", "-version"], capture_output=True).returncode != 0:
        sys.exit("ffmpeg is required to encode Vorbis")
    print(f"writing to {os.path.normpath(OUT)}")
    build()
    print("done")
